In [2]:
from typing import Dict
from azure.identity import DefaultAzureCredential, get_bearer_token_provider
from langchain_community.callbacks import get_openai_callback
from langchain_openai import AzureChatOpenAI
from pydantic import HttpUrl
from pydantic_settings import BaseSettings, SettingsConfigDict


class AzureDeploymentConfig(BaseSettings):
    model_config = SettingsConfigDict(env_prefix='vk_') #SettingsConfigDict(env_prefix='ka_')  # such that you can overwrite these values with environment 
                                                         # variables. E.g.: KA_AZURE_ENDPOINT=http://some.where will
                                                         # overwrite the azure_endpoint value below.
    azure_endpoint: HttpUrl = "https://payg-kar-d-r1-oai.openai.azure.com"
    deployment_name: str = "default-gpt4-turbo"
    openai_api_version: str = "2024-02-01"
    token_scope: str = "https://cognitiveservices.azure.com/.default"



def get_azure_openai(temperature: float = 0.0, top_p: float = 0.5):
    config = AzureDeploymentConfig()
    token_provider = get_bearer_token_provider(
        DefaultAzureCredential(exclude_interactive_browser_credential=False),config.token_scope
    )
    model = AzureChatOpenAI(
        azure_endpoint=str(config.azure_endpoint),
        deployment_name=config.deployment_name,
        openai_api_version=config.openai_api_version,
        azure_ad_token_provider=token_provider,
        temperature=temperature,
        top_p= top_p
    )
    return model

# in model_kwargs "response_format": {"type": "json_object"}

p1 = """
for the following dictionary input, 
provide the python code to filter the dictionary only keep those L0 keys, who have some impact and remove the L1 keys that have impact value "Empty" , and remove the L0 keys which have all L1 impacts as "Empty" 

excerpt of the input dictionary: 
{"590260523": {"content": "AD 136 - Which system/s will provide operational peril risk for pricing for CGU Direct Home, Motor & Niche?\n\nContext:Refer\u00a0AD 125 - Which system/s will provide operational peril risk for pricing and underwriting?\nProblem:AD 125 - Which system/s will provide operational peril risk for pricing and underwriting? determined that the strategic solution for peril pricing and underwriting was to use the PRICE application. However this system is not ready for production yet. The peril underwriting can be delayed indefinitely, but it is necessary to have peril pricing from the first release. So what should the interim solution be for CGU Direct Home, Motor & Niche?\nSolution & key reason/s:For a more consumable view of the solution, see\u00a0AD136 - Peril Pricing strategic solution overview ", "page_link": "https://iag.atlassian.net/wiki/spaces/SEP/pages/590260523", "l1_capability": {"Customer": {"Web": {"level": 1, "description": "Allows customers to access insurance services through the web", "impact": "Empty"}, "Mobile": {"level": 1, "description": "Allows customers to access insurance services through mobile devices", "impact": "Empty"}, "Assisted": {"level": 1, "description": "Provides assistance to customers in accessing insurance services", "impact": "Empty"}}, "Customer Experience & Management": {"Partner Portals & Integration": {"level": 1, "description": "Enables integration of partner portals for a seamless customer experience", "impact": "Empty"}, "Broker Portals & Integration": {"level": 1, "description": "Enables integration of broker portals for improved customer management", "impact": "Empty"}}, "Policy & Pricing": {"Personal Policy": {"level": 1, "description": "Handles insurance policies for individuals", "impact": "Empty"}, "Personal Pricing": {"level": 1, "description": "Determines the price of insurance policies for individuals", "impact": {"description": "The interim solution for peril pricing will directly impact the Personal Pricing capability as it involves determining the price of insurance policies for CGU Direct Home, Motor & Niche."}}, "Personal Underwriting": {"level": 1, "description": "Assesses the risk of insuring individuals", "impact": "Empty"}, "Commercial Policy": {"level": 1, "description": "Handles insurance policies for businesses", "impact": "Empty"}, "Commercial Pricing": {"level": 1, "description": "Determines the price of insurance policies for businesses", "impact": "Empty"}, "Commercial Underwriting": {"level": 1, "description": "Assesses the risk of insuring businesses", "impact": "Empty"}}, "Claims, Supply Chain, Comms": {"Claims": {"level": 1, "description": "Manages insurance claims from customers", "impact": "Empty"}, "Supply Chain": {"level": 1, "description": "Manages the supply chain of insurance products", "impact": "Empty"}, "Communications": {"level": 1, "description": "Handles communications with customers and partners", "impact": "Empty"}}, "Digital Operations": {"People & Workplace Experience": {"level": 1, "description": "Enhances the digital experience of employees and workplace operations", "impact": "Empty"}, "Finance & Actuarial": {"level": 1, "description": "Handles financial and actuarial operations digitally", "impact": "Empty"}, "Risk & Operations": {"level": 1, "description": "Manages risk and operations digitally", "impact": {"description": "The development of the PRICE application and the determination of an interim solution for peril pricing will impact the Risk & Operations capability, as it involves managing operational risk associated with pricing."}}}
"""
# if __name__ == "__main__":
#     model = get_azure_openai(temperature=1.0)
#     with get_openai_callback() as cb:
#         print(model.invoke(p1))
#         print(f"Total Tokens: {cb.total_tokens}")

/Users/s748779/IAG_test/test1/lib/python3.9/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(

#### azure token expiry

In [80]:
from azure.identity import AzureDeveloperCliCredential
from azure.core.credentials import AccessToken

def get_token():
    credential = AzureDeveloperCliCredential()
    token = credential.get_token("https://graph.microsoft.com/.default")
    return token

def refresh_token_if_needed(token: AccessToken):
    if token.expires_on - time.time() < 300:  # Refresh if less than 5 minutes left
        token = get_token()
    return token

In [88]:
# try 2 for get_token without standard process

def get_token():
    credential = DefaultAzureCredential(exclude_interactive_browser_credential=False)
    token = credential.get_token("https://cognitiveservices.azure.com/.default")
    return token

In [81]:
check = get_token()

In [82]:
check

AccessToken(token='eyJ0eXAiOiJKV1QiLCJub25jZSI6Ii1pSkZwYm9Gd0F2ZmZhbmhBOWtPak1tdWdGMjRrSTcyd0RJR1d6dDhWWlUiLCJhbGciOiJSUzI1NiIsIng1dCI6IktRMnRBY3JFN2xCYVZWR0JtYzVGb2JnZEpvNCIsImtpZCI6IktRMnRBY3JFN2xCYVZWR0JtYzVGb2JnZEpvNCJ9.eyJhdWQiOiJodHRwczovL2dyYXBoLm1pY3Jvc29mdC5jb20iLCJpc3MiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC83ZDg0N2IwMC05Y2IyLTRlOGItOWYxNC1mYjU4ZGU0YmNkZGUvIiwiaWF0IjoxNzI0MTQ1MDI2LCJuYmYiOjE3MjQxNDUwMjYsImV4cCI6MTcyNDE0OTg3MSwiYWNjdCI6MCwiYWNyIjoiMSIsImFjcnMiOlsidXJuOnVzZXI6cmVnaXN0ZXJzZWN1cml0eWluZm8iXSwiYWlvIjoiQVZRQXEvOFhBQUFBRlBvVzNvZnUyaTVoL3hqaTRIK29CL2w2Q09QcG4ydnY3TUhxSWVBTW12SmtsTzRIWVNLdjd6eVd5U0xhTWdJU0poR3pNa0dOL1hCSjlTTFlLeHAyaXdNRUNQc3pTN2k0WGRycElpbnkvUTg9IiwiYW1yIjpbInB3ZCIsIm1mYSJdLCJhcHBfZGlzcGxheW5hbWUiOiJNaWNyb3NvZnQgQXp1cmUgQ0xJIiwiYXBwaWQiOiIwNGIwNzc5NS04ZGRiLTQ2MWEtYmJlZS0wMmY5ZTFiZjdiNDYiLCJhcHBpZGFjciI6IjAiLCJkZXZpY2VpZCI6IjA1Nzk1NDFkLTk1NTYtNDc0Ny05MGU2LTM3M2I3YjNhYzMxZCIsImZhbWlseV9uYW1lIjoiTW9yeWUiLCJnaXZlbl9uYW1lIjoiVmlrZXNoIiwiaWR0eXAiOiJ1c2VyIiwiaXBhZGRyIjoiMjQuMjM5LjEzMy42NiIsIm5hbWUiOiJWaWtlc2ggTW9yeWUiLCJvaWQiOiI4MmQzOTFjMy04MDcyLTQxNzUtODgyYS04MWJkNTE2NTVlODAiLCJvbnByZW1fc2lkIjoiUy0xLTUtMjEtNjgzMjQwMDIxLTIzNDYwNTczNzItMzk4OTI4MzYyMC00NjY2ODIiLCJwbGF0ZiI6IjUiLCJwdWlkIjoiMTAwMzIwMDM3QTM4NkE5QSIsInJoIjoiMC5BVUVBQUh1RWZiS2NpMDZmRlB0WTNrdk4zZ01BQUFBQUFBQUF3QUFBQUFBQUFBQkJBT2suIiwic2NwIjoiQXVkaXRMb2cuUmVhZC5BbGwgRGlyZWN0b3J5LkFjY2Vzc0FzVXNlci5BbGwgZW1haWwgR3JvdXAuUmVhZFdyaXRlLkFsbCBvcGVuaWQgcHJvZmlsZSBVc2VyLlJlYWRXcml0ZS5BbGwiLCJzaWduaW5fc3RhdGUiOlsiZHZjX21uZ2QiLCJkdmNfY21wIiwiaW5rbm93bm50d2siLCJrbXNpIl0sInN1YiI6ImY5RDk1NlRRekNCaWJ1dWJOeVk4dUNMTXE5TUdWVWdjazdXMTJjUXIwNEkiLCJ0ZW5hbnRfcmVnaW9uX3Njb3BlIjoiT0MiLCJ0aWQiOiI3ZDg0N2IwMC05Y2IyLTRlOGItOWYxNC1mYjU4ZGU0YmNkZGUiLCJ1bmlxdWVfbmFtZSI6IlZpa2VzaC5Nb3J5ZUBpYWcuY29tLmF1IiwidXBuIjoiVmlrZXNoLk1vcnllQGlhZy5jb20uYXUiLCJ1dGkiOiJzUU91NFB0QkhrT2Y4T1ZLZy00UkFBIiwidmVyIjoiMS4wIiwid2lkcyI6WyJiNzlmYmY0ZC0zZWY5LTQ2ODktODE0My03NmIxOTRlODU1MDkiXSwieG1zX2lkcmVsIjoiMSAyMiIsInhtc19zdCI6eyJzdWIiOiJocXBpbnpGamhpQTI4WENoQ29yY1FqWFNjd1MwaFVRbVZLMVJSN1BWRERzIn0sInhtc190Y2R0IjoxNDAyMDUxMzE2fQ.QqJWYFgR0Y3WddZEiTbt0V3FugBEyHhr1Z6T2ORDX4htZRIbJjR6gzlPo9HQPNEHA0NcmuPcyGHe_HU4twYg3-r7KfHrkc_hyEpoc_K76k8elYW-TQ85ypRDDoAbzxDIWSCVRGZ2Aejuvvf0tFIP578C7bJWmDt61Eda-FT2mCIoqbwa48BwVXjtUein_vhW4KCXb5_Hqi3dcXiBiFGdpMuFHuqsVElBgXfyiGcKVE1vHQgqjU4ILYDjGDZFYMcGCn1yor__3ODkqobcUS09McdZADXDwOZzBEEV3w-iARnrgfVwwDH6yvArdYyyAGdKYpX2fo3X8NrLboN2PCmYEA', expires_on=1724113870)

In [84]:
check.expires_on

1724113570

In [86]:
import time 
time.time()

1724145433.484758

In [87]:
check.expires_on - time.time()

-31579.14816212654

In [90]:
check2 = get_token()
print(check2)

AccessToken(token='eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6IktRMnRBY3JFN2xCYVZWR0JtYzVGb2JnZEpvNCIsImtpZCI6IktRMnRBY3JFN2xCYVZWR0JtYzVGb2JnZEpvNCJ9.eyJhdWQiOiJodHRwczovL2NvZ25pdGl2ZXNlcnZpY2VzLmF6dXJlLmNvbSIsImlzcyI6Imh0dHBzOi8vc3RzLndpbmRvd3MubmV0LzdkODQ3YjAwLTljYjItNGU4Yi05ZjE0LWZiNThkZTRiY2RkZS8iLCJpYXQiOjE3MjQxNDUyNjUsIm5iZiI6MTcyNDE0NTI2NSwiZXhwIjoxNzI0MTUwNDQ4LCJhY3IiOiIxIiwiYWlvIjoiQVZRQXEvOFhBQUFBWm81YlZjTVdkNG56a0F6djZsTGxMV3hCMVZOak5WMXpNakZtL1ZZTlY5RXFLVGFvN1FIRDNYbC9tcjFvVktQUEh6MCtkN3dwM3B5Y2tCaHMwS041ZkszYTYxTnp4L1o2T2VrSWc5U1V4V0E9IiwiYW1yIjpbInB3ZCIsIm1mYSJdLCJhcHBpZCI6IjA0YjA3Nzk1LThkZGItNDYxYS1iYmVlLTAyZjllMWJmN2I0NiIsImFwcGlkYWNyIjoiMCIsImRldmljZWlkIjoiMDU3OTU0MWQtOTU1Ni00NzQ3LTkwZTYtMzczYjdiM2FjMzFkIiwiZmFtaWx5X25hbWUiOiJNb3J5ZSIsImdpdmVuX25hbWUiOiJWaWtlc2giLCJncm91cHMiOlsiNmYxMDA2MDItZjRmYS00ZDJhLWEyOTktOWJlNmIxMTk5NjhmIiwiMmQyOTFlMGYtMjE4NC00MWVkLThjYzEtODQ0MWI5ODkwNGYwIiwiMTczMDkwMTMtNTc2Mi00ZWEzLWE0NTktNDMwMDE1OTgyY2MzIiwiZTUwYzNmMjUtZGQyMS00Y2Q0LTlhNDktZTkzNDA0NDc1MjA1IiwiMmViYmE0MjUtNzhhZS00NDM1LTliM2MtMGUzYjA5NDQ4YTJlIiwiYWJhMzQzMjgtZTU1Ny00NjM1LWEzMDctYTA5YjY4M2FkNjE1IiwiOTBiZDU2MjktMWQxNi00MmVjLWI4MWMtNWJhZTZkZTFjMmVjIiwiNzJjMDMzNDEtNDA0OC00NTkwLTk2MjItMDBkMWZjZmU5MzcxIiwiNGE2Mjk2NGUtNmI3NS00NjRmLTkwNGMtZjgwM2FjYTM2ZjIzIiwiYmMyNWZiNTEtNjExMS00YjVjLTg1MmEtZDY4NDA0YjE3Y2Q2IiwiMjU0MGUyNWMtZTliOC00ZDBhLTk2Y2EtMjg3YjUyNDVkNjY4IiwiN2FjNGM2NjYtYmMwOC00NDg5LWI5YmMtZTdmMWU0M2E1YTU0IiwiZmNhYWFhNzYtMTg0ZS00M2QxLThlZjgtNmRmODYwNmYxMDg4IiwiZDJiYWI3NzgtZDNmMi00Nzg1LThmYzctMzY0MDYzMzkwMmQ0IiwiNjhlOGRlNzgtZmE3Yy00ZWU3LWI5NDMtNTNkMjc3YjIyMmI4IiwiNDBiNmEyODEtOTI1Zi00NzdjLTkzNjgtNGJlYjU2N2YwNGQzIiwiN2UxMWJlODgtMWIzOC00YTFmLWI5MDEtOGExMjFiZjMyODdlIiwiZTRlOTgwOGMtZmNiMy00YTAwLWE4ODYtNTExYTk1YjcyMzNkIiwiNzU1ZjJlOWUtZGE5OC00ZTE0LWFkNTMtNDc3ZWZiNzE2ZGRmIiwiMWExZWQyOWYtZWQ0Zi00ZGZjLTg1YjQtMDE3NjY4MmU0YmU2IiwiNzdmZDhiYTQtMDYyMi00OGRmLWIxOTItNjNkOTI4NGMyYzk4IiwiYzRhMGM1YTQtZDZkOC00MDkwLWIxZWYtZDNjZjFmY2UwNWFlIiwiYTA2MjE4YWQtY2Y4MS00YzE2LTk1OWMtMDE0ODM3NmIyOTJmIiwiMDE3MDEzYjUtOTAwYS00YmRiLTlhMjUtZThkYWQ5MTQwNTIwIiwiNjQ2NGMwYjgtMjk1YS00MWY0LWI0MmQtNGUzNjVlYmEzNDY0IiwiNjM5ODc3YmMtNTZkZS00NWE0LWJkMmItZjlhYWQ2NDY0NDYyIiwiYmY3NTFjYzAtYTliNC00MTExLWJhZTAtNDQ1NmU3MzdlYWM0IiwiY2MyOThhYzYtZjg4Yy00MDA1LWJkZGQtZjI4ZTA2OTRiY2M5IiwiYzg4YjU3YzctODI2Mi00OGY5LThkNmMtY2VhMmVmYzUyOGQxIiwiOTFjZmVjZDUtYTU4Mi00NTE5LWIzMWMtMjE2YjQyMzQwMzY1IiwiYzc3ZTA3ZDktYWZlYy00OTIwLTlkNzYtNGFhYWM0YzY1YzcwIiwiZjk5NGE0ZGMtOGYxMi00YTRhLTlmZmEtMGNlM2FkMmY2YmZhIiwiNzIwYWVkZTUtOTEwYy00OWU0LWEyZGUtZjBmZjExMDc2NGFiIiwiNTViYmY1ZTgtNmUwYi00ZDdlLWI5YmItZGEyZDY4YTBmNmFkIiwiM2Y4YzFhZWEtNDk4Zi00ZmVlLWJjYjgtZWM5MTZjMjc0YWZlIiwiNDVlNmQzZWUtYmRlZi00NmE0LThkZDItMTFlNWQ4ZmNhYWI4IiwiZTQxMzI1ZjEtMDdlMS00M2RjLTgwYzMtMDRiNDA0NWFiMDEwIiwiMzIzZDY5ZjItM2NjZS00OTZhLTk3YzYtMDAwYjZlZjY4YzhlIl0sImlkdHlwIjoidXNlciIsImlwYWRkciI6IjI0LjIzOS4xMzMuNjYiLCJuYW1lIjoiVmlrZXNoIE1vcnllIiwib2lkIjoiODJkMzkxYzMtODA3Mi00MTc1LTg4MmEtODFiZDUxNjU1ZTgwIiwib25wcmVtX3NpZCI6IlMtMS01LTIxLTY4MzI0MDAyMS0yMzQ2MDU3MzcyLTM5ODkyODM2MjAtNDY2NjgyIiwicHVpZCI6IjEwMDMyMDAzN0EzODZBOUEiLCJyaCI6IjAuQVVFQUFIdUVmYktjaTA2ZkZQdFkza3ZOM3BBaU1YM0lLRHhIb08yT1UzU2JiVzFCQU9rLiIsInNjcCI6InVzZXJfaW1wZXJzb25hdGlvbiIsInN1YiI6ImtrTFlTWkM4NFZmaV8tbmIwTmZ4N2lKU25QQk5jUlROUGxmeG40TkpMZmsiLCJ0aWQiOiI3ZDg0N2IwMC05Y2IyLTRlOGItOWYxNC1mYjU4ZGU0YmNkZGUiLCJ1bmlxdWVfbmFtZSI6IlZpa2VzaC5Nb3J5ZUBpYWcuY29tLmF1IiwidXBuIjoiVmlrZXNoLk1vcnllQGlhZy5jb20uYXUiLCJ1dGkiOiJmVmxCRmNDXzYwQ083LXBTNVRFT0FBIiwidmVyIjoiMS4wIiwid2lkcyI6WyJiNzlmYmY0ZC0zZWY5LTQ2ODktODE0My03NmIxOTRlODU1MDkiXSwieG1zX2lkcmVsIjoiMTIgMSJ9.zFSvWV3N1G7K1sWxtjzvi50e91E87NpXxksvJf8k0OuCthRMF_coOcryCqHuZSLfzG_Gcmaw48SI3kWm8ZlGswwtC47-U89E6SrCh48Xt3rwRY7QrmWMIMsQ7eUExYZPp4BrUpydqxRgA1_3duZAWQV1eEiGKFSYfCyeVrB2Dh27vTL5dKLx38c55FmjZ1eMzNZ8ZBbVCKUt3TGx5xkGjp7dCc6nCHbc5A8ljinh3u6I2DsUKZ7q4vfXcjbCWaFSiqbfkJgID0AnVvyPV-pvyURHDp0XxQgxq2Qe7kA1XgIN2SkdMjldeAponfeNy8qMhuzZcbSEOE6tflDPKRovcA', expires_on=1724114447)

In [91]:

print(check2.expires_on - time.time())

-31140.821228027344

In [98]:
# gpt response with new token access gen function


from pydantic_settings import BaseSettings
from pydantic import HttpUrl

from langchain_openai import AzureChatOpenAI

from azure.identity import AzureDeveloperCliCredential
from azure.core.exceptions import ClientAuthenticationError
from azure.core.credentials import AccessToken

# Function to get and refresh the token
# def get_token():
#     credential = AzureDeveloperCliCredential()
#     token = credential.get_token("https://graph.microsoft.com/.default")
#     return token

def get_token():
    credential = AzureDeveloperCliCredential()
    token = credential.get_token("https://cognitiveservices.azure.com/.default")
    return token
    
# Function to refresh the token if needed
def refresh_token_if_needed(token: AccessToken):
    if token.expires_on - time.time() < 300:  # Refresh if less than 5 minutes left
        token = get_token()
    return token


class AzureDeploymentConfig(BaseSettings):
    model_config = SettingsConfigDict(env_prefix='vk_')
    azure_endpoint: HttpUrl = "https://payg-k-d-r3-oai.openai.azure.com"
    deployment_name: str = "default-gpt4-turbo"
    openai_api_version: str = "2023-02-01"
    token_scope: str = "https://cognitiveservices.azure.com/.default"

def initialize_gpt_models(temperature: float = 0.0, top_p: float = 0.5):
    config = AzureDeploymentConfig()
    token = get_token()

    main_model = AzureChatOpenAI(
        azure_endpoint=str(config.azure_endpoint),
        deployment_name=config.deployment_name,
        openai_api_version=config.openai_api_version,
        azure_ad_token_provider=lambda: refresh_token_if_needed(token),
        temperature=temperature,
        top_p=top_p
    )

    json_model = AzureChatOpenAI(
        azure_endpoint=str(config.azure_endpoint),
        deployment_name=config.deployment_name,
        openai_api_version=config.openai_api_version,
        azure_ad_token_provider=lambda: refresh_token_if_needed(token),
        temperature=temperature,
        top_p=top_p,
        model_kwargs={"response_format": {"type": "json_object"}}
    )
    return main_model, json_model


def get_gpt_model_response(prompt, main_model, json_model):
    token = get_token()
    headers = {"Authorization": f"Bearer {token.token}"}

    try:
        raw = main_model.invoke(prompt, headers=headers)
        raw_text = raw.content
        raw_text_validated = validate_json_gpt_model(raw_text, json_model)
        raw_json = json.loads(raw_text_validated)
        return raw_json
    except ClientAuthenticationError:
        token = refresh_token_if_needed(token)
        headers = {"Authorization": f"Bearer {token.token}"}
        raw = main_model.invoke(prompt, headers=headers)
        raw_text = raw.content
        raw_text_validated = validate_json_gpt_model(raw_text, json_model)
        try:
            raw_json = json.loads(raw_text_validated)
            return raw_json
        except Exception as e:
            print("The json_model failed to return valid json for ", raw_text[:100], ". . .")
            return raw_text
    except Exception as e:
        print("An error occurred: ", str(e))
        return None

In [100]:
mmodel, jmodel = initialize_gpt_models()

In [101]:
df_ex = pd.read_excel("/Users/s748779/IAG_test/aia_cc/final_train_data_df.xlsx")
df_ex

,opportunity_name,problem_statement,outcome,RAID,actual_cost,l1_capabilities,l2_capabilities,cost_rationale
0,Vehicle Fulfilment Platform (Carbar),Problem statement*\nWhat is the business/custo...,Outcomes*\nBased on the business/ customer pro...,Risks – \nTiming. Pending other activity withi...,M,"{'Customer': {'Web': {'level': 1, 'description...","{'Claims, Supply Chain, Comms': {'Supply Chain...",The cost for the Vehicle Fulfilment Platform (...
1,Add 'Channel' as a mandatory CCM Field,What is the business/customer problem we want ...,We are proposing to add Complaints Channel as ...,"\nFunding pathway needs to be confirmed, will ...",M,"{'Customer': {'Web': {'level': 1, 'description...","{'Claims, Supply Chain, Comms': {'Claims': {'l...",The cost for adding 'Channel' as a mandatory C...
2,Consumer Leads in Orbit (Phase 2 + Lifestyle),"Currently, our colleagues face the frustration...","Delivery of the leads capability across Motor,...",RISKS: \nTechnical resourcing availability to ...,M,"{'Customer': {'Web': {'level': 1, 'description...","{'Customer': {'Assisted': {'level': 1, 'descri...",The cost for Consumer Leads in Orbit (Phase 2 ...
3,Digital out of the box,Problem statement*\nWhat is the business/custo...,Based on the business/ customer problem statem...,List any key risks or dependencies that may pr...,M,"{'Customer': {'Web': {'level': 1, 'description...","{'Customer': {'Web': {'level': 1, 'description...",The cost for 'Digital out of the box' is 'Medi...
4,eDocs Uplift: EP PC Preselected Yes to eDocs i...,Problem statement*\nWhat is the business/custo...,Outcomes*\nBased on the business/ customer pro...,Risks / constraints / dependencies / assumptio...,XS,"{'Customer': {'Web': {'level': 1, 'description...","{'Customer': {'Assisted': {'level': 1, 'descri...",The cost for 'eDocs Uplift' is 'Extra_Small_XS...
5,MVB redesign (Initiative from the NRMA),The NRMA would like to change name and price o...,Provides a convenient experience for customers...,NaN,S,"{'Customer': {'Web': {'level': 1, 'description...","{'Customer': {'Web': {'level': 1, 'description...",The cost for 'MVB redesign (Initiative from th...
6,NPCID-2023635,"Problem statement*\n\nTraditionally, excess is...",Outcomes*\nBased on the business/ customer pro...,Risks / constraints / dependencies / assumptio...,S,"{'Customer': {'Web': {'level': 1, 'description...","{\n ""Customer"": {\n ""Web"": {\n ""level...",The cost for 'NPCID-2023635' is 'Small_S' due ...
7,SME API Exposure to partners,IAG is missing out on sales opportunities to r...,Creating the links and information required to...,Ensuring that work doesn’t have to be done mul...,S,"{'Customer': {'Web': {'level': 1, 'description...","{'Customer': {'Web': {'level': 1, 'description...",The cost for 'SME API Exposure to partners' is...
8,Extend Digital Analytics Capability,1. We are limited in our ability to track and ...,1. Refresh the discovery work done 1 year ago ...,Implementation needs to be prior to NRMA NSW E...,S,"{'Customer': {'Web': {'level': 1, 'description...","{'Customer': {'Web': {'level': 1, 'description...",The cost for 'Extend Digital Analytics Capabil...
9,Home Risk Index,For Consumers:\nThere is a lack of quality pub...,For a consumer audience considering a new home...,Peril Data Licensing:\nThe AAL/100k modelling ...,M,"{'Customer': {'Web': {'level': 1, 'description...","{'Customer': {'Web': {'level': 1, 'description...",The cost for 'Home Risk Index' is 'Medium_M' d...

In [ ]:
with get_openai_callback() as cb:
        print(model.invoke(p1))
        print(f"Total Tokens: {cb.total_tokens}")

In [ ]:


def initialize_models(model_name = "gemini-1.5-flash-001"):
    main_model = GenerativeModel(model_name=model_name, 
                             generation_config={"response_mime_type": "application/json"})
    
    
    json_model = GenerativeModel(
                model_name=model_name,
                system_instruction=[
                    "You are a helpful json validator.",
                    "Your mission is to conevrt the input requested into a valid JSON by rectifying the relevant mistakes, if any."
                    ],
                )
    
    return main_model, json_model

In [6]:
# ========= add to aa_utils of archassist folder ====================================
from time import time
from langchain.prompts import PromptTemplate
import json

from typing import Dict
from azure.identity import DefaultAzureCredential, get_bearer_token_provider
from langchain_community.callbacks import get_openai_callback
from langchain_openai import AzureChatOpenAI
from pydantic import HttpUrl
from pydantic_settings import BaseSettings, SettingsConfigDict

# ============= models ========================

class AzureDeploymentConfig(BaseSettings):
    model_config = SettingsConfigDict(env_prefix='vk_') #SettingsConfigDict(env_prefix='ka_')  # such that you can overwrite these values with environment 
                                                         # variables. E.g.: KA_AZURE_ENDPOINT=http://some.where will
                                                         # overwrite the azure_endpoint value below.
    azure_endpoint: HttpUrl = "https://payg-kar-d-r1-oai.openai.azure.com"
    deployment_name: str = "default-gpt4-turbo"
    openai_api_version: str = "2024-02-01"
    token_scope: str = "https://cognitiveservices.azure.com/.default"



def initialize_gpt_models(temperature: float = 0.0, top_p: float = 0.5):
    config = AzureDeploymentConfig()
    token_provider = get_bearer_token_provider(
        DefaultAzureCredential(exclude_interactive_browser_credential=False),config.token_scope
    )
    main_model = AzureChatOpenAI(
        azure_endpoint=str(config.azure_endpoint),
        deployment_name=config.deployment_name,
        openai_api_version=config.openai_api_version,
        azure_ad_token_provider=token_provider,
        temperature=temperature,
        top_p = top_p
    )

    json_model = AzureChatOpenAI(
        azure_endpoint=str(config.azure_endpoint),
        deployment_name=config.deployment_name,
        openai_api_version=config.openai_api_version,
        azure_ad_token_provider=token_provider,
        temperature=temperature,
        top_p = top_p,
        model_kwargs={
                      "response_format": {"type": "json_object"}}
    )
    return main_model, json_model

# modify validaye_json_model 
def validate_json_gpt_model(prompt, json_model):
    if not is_json_gpt(prompt):
        response = json_model.invoke([ ("system",
                                        "Validate the given json string and correct it wherever required to convert it into a valid JSON structure."),
                                        ("human", prompt),
                                     ])
        resp = response.content
        # validated_json_dict = json.loads(resp)
        return resp

    return prompt
    
def is_json_gpt(response_output):
    try:
        json.loads(response_output)
        return True
    except json.JSONDecodeError:
        print("GPT main_model failed to provide valid json.")
        return False


# ============ model outputs ===================

# modify get_gemini_response
def get_gpt_model_response(prompt, main_model, json_model):
    raw = main_model.invoke(prompt)
    raw_text = raw.content
    raw_text_validated = validate_json_gpt_model(raw_text, json_model)
    try:
        raw_json = json.loads(raw_text_validated)
        return raw_json
    except Exception as e:
        print("The json_model failed to return valid json for ", raw_text[:100], ". . .")
        return raw_text


def get_reall_from_input(input_data, pt):

    start = time()
    main_model, json_model = initialize_gpt_models()
    
    p1_1_r = PromptTemplate.from_template(pt["p1"]["get_roles"]).format(inp_ps = input_data)
    role_json = get_gpt_model_response(p1_1_r, main_model, json_model) 
    
    p1_2_e = PromptTemplate.from_template(pt["p1"]["get_events"]).format(inp_ps = input_data)
    events_json = get_gpt_model_response(p1_2_e, main_model, json_model) 
    
    p1_3_a = PromptTemplate.from_template(pt["p1"]["get_activities"]).format(inp_ps = input_data,
                                                                             events_data = events_json)
    activities_json = get_gpt_model_response(p1_3_a, main_model, json_model) 
    
    with open("cpm_ins_L1.json", "r") as fp:
        all_l1_capability_model_json = json.load(fp)
    with open("cpm_ins_L2.json", "r") as fp:
        all_l2_capability_model_json = json.load(fp)

    p1_4_l1 = PromptTemplate.from_template(pt["p1"]["get_l1_cap"]).format(inp_ps = input_data, 
                                                                        roles_data = role_json,
                                                                        events_data = events_json,
                                                                        activities_data = activities_json,
                                                                        level1_capability_model = all_l1_capability_model_json)
     
    l1_json = get_gpt_model_response(p1_4_l1, main_model, json_model)

    if is_json_gpt(json.dumps(l1_json)):
        filtered_l1_capabilities = extract_impacted_capabilities_L1(l1_json)
        relevant_l2_for_l1_json = filter_l2_capabilities_for_l1(filtered_l1_capabilities, all_l2_capability_model_json)

        p1_5_l2 = PromptTemplate.from_template(pt["p1"]["get_l2_cap"]).format(inp_ps = input_data, 
                                                                        roles_data = role_json,
                                                                        events_data = events_json,
                                                                        activities_data = activities_json,
                                                                        sample_l2_cap = pt["p1"]["sample_l2_cap"],
                                                                        filtered_level2_capability_model=relevant_l2_for_l1_json)
        
    else :
        p1_5_l2 = PromptTemplate.from_template(pt["p1"]["get_l2_cap"]).format(inp_ps = input_data, 
                                                                        roles_data = role_json,
                                                                        events_data = events_json,
                                                                        activities_data = activities_json,
                                                                        sample_l2_cap = pt["p1"]["sample_l2_cap"],
                                                                        filtered_level2_capability_model=all_l2_capability_model_json)
        
    
    l2_json = get_gpt_model_response(p1_5_l2, main_model, json_model)

    end = time()

    print(end-start)
    
    return l1_json, l2_json
    
# ========== for final output_dag from input and matched ADs with their l1 l2 provided as input ==============

def get_final_gemini_output(pt, ad_inp_pcs, input_data, inp_l1, inp_l2):
    main_model, json_model = initialize_gpt_models()
    p3_1_f = PromptTemplate.from_template(pt["p3"]["get_final_out"]).format(inp_ps = input_data, 
                                                                                inp_l1 = inp_l1,
                                                                                inp_l2 = inp_l2,
                                                                                top_matched_ads_with_l1_l2 = ad_inp_pcs,
                                                                                sample_final_json_output = pt["p3"]["sample_final_json_output"])

    final_analysis_json = get_gpt_model_response(p3_1_f, main_model, json_model)
    
    return final_analysis_json


# ====================================================
# ======== data handling for l2 l2 ==================
def extract_impacted_capabilities_L1(json_AI_response):
    """ Extract L1 capabilities that are impact - i.e do not have Empty as the impact """
    new_dict = {
        outer_key: {
            inner_key: value
            for inner_key, value in outer_value.items()
            if value['impact'] != 'Empty'
        }

        for outer_key, outer_value in json_AI_response.items()
    }
    return new_dict


def filter_l2_capabilities_for_l1(filtered_l1_capabilities, l2_all_capabilities_json):
    """ Filter out L1 items from the L2 capability model that aren't imacted. I.e. L1 impact is Empty 
        Takes in filtered L1 items and all L2 capabilities to return filtered L2 caps
    """
    reference_l2_capabilities = l2_all_capabilities_json
    filtered_dict = {
        outer_key: {
            inner_key: reference_l2_capabilities[outer_key][inner_key]
            for inner_key in outer_value
            if outer_value[inner_key]['impact'] != 'Empty' and inner_key in reference_l2_capabilities[outer_key]
        }
        for outer_key, outer_value in filtered_l1_capabilities.items()
        if outer_key in reference_l2_capabilities
    }

    return filtered_dict

# =========== data handling for matched ADs ==================

def get_ad_dict(vdb_final_out_json, details):
    merged = {} 
    for key in details:
        merged.update(vdb_final_out_json[key])
    return merged

def get_ad_inp_pcs(merged):
    # make list of ad title, and other data for input to REALL
    subheadings = ["problem", "context", "solution"]
    # ad_inp_list = []
    ad_inp_pcs = {}
    for page_num, payload in merged.items():
        ad_in = payload["ad_ref"] + '\n'
        
        for key in payload["full_adr_content"].keys():
            if any(word in key.lower() for word in subheadings):
                ad_in = ad_in + '\n' + key + ":" + str(' '.join(payload["full_adr_content"][key])) 
                # print(payload["full_adr_content"][key] )
             
        # ad_inp_list.append(ad_in)
        ad_inp_pcs.update({page_num:{"content" : ad_in, "page_link" : payload["page_link"]}})
    
    return ad_inp_pcs

# =========== data handling for final output key replace titles ============

def get_final_output_json_with_title(final_analysis_json, ad_merged_dict):
    '''
    takes in the final gemini output and merged dictionary of details to imoute titles into keys for readability
    '''
    # Initialize an empty dictionary to hold the result
    output_dict = {}

    # Iterate over the outer dictionary in dict1
    for outer_key, inner_dict in final_analysis_json.items():
        # Initialize a nested dictionary for the outer key in output_dict
        if outer_key == "New" :
            output_dict[outer_key] = inner_dict
        if outer_key != "New" :
            output_dict[outer_key] = {}
            # Iterate over the inner dictionary
            for key, value in inner_dict.items():
                print(key, "==")
                # Check if the key exists in dict2 and has a 'title' key
                if str(key) in ad_merged_dict.keys() and 'ad_ref' in ad_merged_dict[str(key)]:
                    # Use the title from dict2 as the new key in output_dict[outer_key]
                    new_key = ad_merged_dict[key]['ad_ref']
                    output_dict[outer_key][new_key] = value
            
        return output_dict

/Users/s748779/IAG_test/test1/lib/python3.9/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(

In [48]:
# apply to dictionary having "Empty" in L1 impact

def filter_impact(input_dict):
    # Dictionary to store the filtered results
    filtered_dict = {}

    # Iterate over the top-level keys (L0)
    for l0_key, l0_value in input_dict.items():
        # Dictionary to store the sub-keys (L1) that have non-empty impact
        l1_with_impact = {}

        # Check if 'l1_capability' exists in the dictionary
        if 'l1_capability' in l0_value:
            # Iterate over the second-level keys (L1)
            for l1_key, l1_value in l0_value['l1_capability'].items():
                # Filter out the keys with 'impact' value 'Empty'
                l1_with_impact[l1_key] = {k: v for k, v in l1_value.items() if not (isinstance(v.get('impact'), str) and v.get('impact') == 'Empty')}

            # Remove L1 keys if they are empty after filtering
            l1_with_impact = {k: v for k, v in l1_with_impact.items() if v}

        # If after filtering, there are L1 keys with impact, add them to the filtered dictionary
        if l1_with_impact:
            # Copy the original L0 values
            filtered_l0_value = l0_value.copy()
            # Update the 'l1_capability' with the filtered L1 keys
            filtered_l0_value['l1_capability'] = l1_with_impact
            # Add the filtered L0 key to the filtered dictionary
            filtered_dict[l0_key] = filtered_l0_value

    return filtered_dict

# ========== try 2 > succeeds 

def filter_impact(input_dict):
    # Dictionary to store the filtered results
    filtered_dict = {}

    # Iterate over the top-level keys (L0)
    for l0_key, l0_value in input_dict.items():
        # Dictionary to store the sub-keys (L1) that have non-empty impact
        l1_with_impact = {}

        # Iterate over the second-level keys (L1)
        for l1_key, l1_value in l0_value.items():
            # Filter out the keys with 'impact' value 'Empty'
            if isinstance(l1_value.get('impact'), str) and l1_value.get('impact') == 'Empty':
                continue
            l1_with_impact[l1_key] = l1_value

        # If after filtering, there are L1 keys with impact, add them to the filtered dictionary
        if l1_with_impact:
            filtered_dict[l0_key] = l1_with_impact

    return filtered_dict

In [49]:
# for k, v in merged_pcs.items():
#     print(k, v["l1_capability"], '\n', '\n')

check = filter_impact(merged_pcs["590119177"]["l1_capability"])
check

{'Enabling Capabilities': {'Data': {'level': 1,
   'description': 'Manages and analyzes data for insurance operations',
   'impact': {'description': 'The project will require enhancements to the data management and analytics capabilities to support the integration of data from both the legacy policy systems and the new Guidewire PolicyCenter for reporting purposes. This includes the design and implementation of data integration patterns and ensuring that the reporting requirements are met during the co-existence phase.'}},
  'Infrastructure': {'level': 1,
   'description': 'Provides the necessary infrastructure to support insurance operations',
   'impact': {'description': 'The infrastructure will need to support the co-existence of the legacy policy systems and the new Guidewire PolicyCenter, including the data integration solutions that will be implemented. This may involve scaling up the infrastructure to handle the additional load and ensuring that it can support the chosen architecture pattern for data integration.'}}}}

In [53]:
with open("../st/files/cpm_ins_L2.json", "r") as fp:
        all_l2_capability_model_json = json.load(fp)
check1_1 = filter_l2_capabilities_for_l1(check, all_l2_capability_model_json)
check1_1

{'Enabling Capabilities': {'Data': {'level': 1,
   'description': 'Manages and analyzes data for insurance operations',
   'L2 capabilities': [{'Data Warehousing & Orchestration': {'level': 2,
      'description': 'Manages the storage and orchestration of data for insurance operations'}},
    {'Analytics & Reporting': {'level': 2,
      'description': 'Performs analytics and generates reports for insurance operations'}},
    {'Archiving': {'level': 2,
      'description': 'Manages the archival of data for insurance operations'}},
    {'Master Data Management': {'level': 2,
      'description': 'Manages the master data for insurance operations'}},
    {'Knowledge Management': {'level': 2,
      'description': 'Manages and shares knowledge within the insurance company'}},
    {'Data Access & Governance': {'level': 2,
      'description': 'Manages access to and governance of data for insurance operations'}}]},
  'Infrastructure': {'level': 1,
   'description': 'Provides the necessary infrastructure to support insurance operations',
   'L2 capabilities': [{'Networking': {'level': 2,
      'description': 'Manages the networking infrastructure for insurance operations'}},
    {'Storage': {'level': 2,
      'description': 'Manages the storage infrastructure for insurance operations'}},
    {'Compute': {'level': 2,
      'description': 'Manages the computing infrastructure for insurance operations'}},
    {'API Management': {'level': 2,
      'description': 'Manages the APIs used for integration in insurance operations'}}]}}}

In [51]:
check2 = extract_impacted_capabilities_L1(merged_pcs["590119177"]["l1_capability"])
check2

{'Customer': {},
 'Customer Experience & Management': {},
 'Policy & Pricing': {},
 'Claims, Supply Chain, Comms': {},
 'Digital Operations': {},
 'Enabling Capabilities': {'Data': {'level': 1,
   'description': 'Manages and analyzes data for insurance operations',
   'impact': {'description': 'The project will require enhancements to the data management and analytics capabilities to support the integration of data from both the legacy policy systems and the new Guidewire PolicyCenter for reporting purposes. This includes the design and implementation of data integration patterns and ensuring that the reporting requirements are met during the co-existence phase.'}},
  'Infrastructure': {'level': 1,
   'description': 'Provides the necessary infrastructure to support insurance operations',
   'impact': {'description': 'The infrastructure will need to support the co-existence of the legacy policy systems and the new Guidewire PolicyCenter, including the data integration solutions that will be implemented. This may involve scaling up the infrastructure to handle the additional load and ensuring that it can support the chosen architecture pattern for data integration.'}}}}

In [54]:
check2_2 =filter_l2_capabilities_for_l1(check2, all_l2_capability_model_json)
check2_2

{'Customer': {},
 'Policy & Pricing': {},
 'Claims, Supply Chain, Comms': {},
 'Digital Operations': {},
 'Enabling Capabilities': {'Data': {'level': 1,
   'description': 'Manages and analyzes data for insurance operations',
   'L2 capabilities': [{'Data Warehousing & Orchestration': {'level': 2,
      'description': 'Manages the storage and orchestration of data for insurance operations'}},
    {'Analytics & Reporting': {'level': 2,
      'description': 'Performs analytics and generates reports for insurance operations'}},
    {'Archiving': {'level': 2,
      'description': 'Manages the archival of data for insurance operations'}},
    {'Master Data Management': {'level': 2,
      'description': 'Manages the master data for insurance operations'}},
    {'Knowledge Management': {'level': 2,
      'description': 'Manages and shares knowledge within the insurance company'}},
    {'Data Access & Governance': {'level': 2,
      'description': 'Manages access to and governance of data for insurance operations'}}]},
  'Infrastructure': {'level': 1,
   'description': 'Provides the necessary infrastructure to support insurance operations',
   'L2 capabilities': [{'Networking': {'level': 2,
      'description': 'Manages the networking infrastructure for insurance operations'}},
    {'Storage': {'level': 2,
      'description': 'Manages the storage infrastructure for insurance operations'}},
    {'Compute': {'level': 2,
      'description': 'Manages the computing infrastructure for insurance operations'}},
    {'API Management': {'level': 2,
      'description': 'Manages the APIs used for integration in insurance operations'}}]}}}

In [47]:
merged_pcs["590119177"]["l1_capability"]

{'Customer': {'Web': {'level': 1,
   'description': 'Allows customers to access insurance services through the web',
   'impact': 'Empty'},
  'Mobile': {'level': 1,
   'description': 'Allows customers to access insurance services through mobile devices',
   'impact': 'Empty'},
  'Assisted': {'level': 1,
   'description': 'Provides assistance to customers in accessing insurance services',
   'impact': 'Empty'}},
 'Customer Experience & Management': {'Partner Portals & Integration': {'level': 1,
   'description': 'Enables integration of partner portals for a seamless customer experience',
   'impact': 'Empty'},
  'Broker Portals & Integration': {'level': 1,
   'description': 'Enables integration of broker portals for improved customer management',
   'impact': 'Empty'}},
 'Policy & Pricing': {'Personal Policy': {'level': 1,
   'description': 'Handles insurance policies for individuals',
   'impact': 'Empty'},
  'Personal Pricing': {'level': 1,
   'description': 'Determines the price of insurance policies for individuals',
   'impact': 'Empty'},
  'Personal Underwriting': {'level': 1,
   'description': 'Assesses the risk of insuring individuals',
   'impact': 'Empty'},
  'Commercial Policy': {'level': 1,
   'description': 'Handles insurance policies for businesses',
   'impact': 'Empty'},
  'Commercial Pricing': {'level': 1,
   'description': 'Determines the price of insurance policies for businesses',
   'impact': 'Empty'},
  'Commercial Underwriting': {'level': 1,
   'description': 'Assesses the risk of insuring businesses',
   'impact': 'Empty'}},
 'Claims, Supply Chain, Comms': {'Claims': {'level': 1,
   'description': 'Manages insurance claims from customers',
   'impact': 'Empty'},
  'Supply Chain': {'level': 1,
   'description': 'Manages the supply chain of insurance products',
   'impact': 'Empty'},
  'Communications': {'level': 1,
   'description': 'Handles communications with customers and partners',
   'impact': 'Empty'}},
 'Digital Operations': {'People & Workplace Experience': {'level': 1,
   'description': 'Enhances the digital experience of employees and workplace operations',
   'impact': 'Empty'},
  'Finance & Actuarial': {'level': 1,
   'description': 'Handles financial and actuarial operations digitally',
   'impact': 'Empty'},
  'Risk & Operations': {'level': 1,
   'description': 'Manages risk and operations digitally',
   'impact': 'Empty'}},
 'Enabling Capabilities': {'Data': {'level': 1,
   'description': 'Manages and analyzes data for insurance operations',
   'impact': {'description': 'The project will require enhancements to the data management and analytics capabilities to support the integration of data from both the legacy policy systems and the new Guidewire PolicyCenter for reporting purposes. This includes the design and implementation of data integration patterns and ensuring that the reporting requirements are met during the co-existence phase.'}},
  'Security': {'level': 1,
   'description': 'Ensures the security and protection of insurance data and systems',
   'impact': 'Empty'},
  'Infrastructure': {'level': 1,
   'description': 'Provides the necessary infrastructure to support insurance operations',
   'impact': {'description': 'The infrastructure will need to support the co-existence of the legacy policy systems and the new Guidewire PolicyCenter, including the data integration solutions that will be implemented. This may involve scaling up the infrastructure to handle the additional load and ensuring that it can support the chosen architecture pattern for data integration.'}}}}

In [59]:
all_l2_capability_model_json

{'Customer': {'Web': {'level': 1,
   'description': 'Allows customers to access insurance services through the web',
   'L2 capabilities': [{'Web Sales (Quote and Buy)': {'level': 2,
      'description': 'Enables customers to obtain quotes and purchase insurance policies online'}},
    {'Web Self Service': {'level': 2,
      'description': 'Provides self-service options for customers to manage their insurance policies online'}},
    {'Web Claims': {'level': 2,
      'description': 'Allows customers to submit and track insurance claims through the web'}},
    {'Web Content Management': {'level': 2,
      'description': 'Manages and updates the content displayed on the web portal'}},
    {'Web Behavioural Analytics': {'level': 2,
      'description': 'Analyzes customer behavior on the web portal to improve marketing strategies'}}]},
  'Mobile': {'level': 1,
   'description': 'Allows customers to access insurance services through mobile devices',
   'L2 capabilities': [{'Mobile Sales (Quote and Buy)': {'level': 2,
      'description': 'Enables customers to obtain quotes and purchase insurance policies through mobile apps'}},
    {'Mobile Self Service': {'level': 2,
      'description': 'Provides self-service options for customers to manage their insurance policies through mobile apps'}},
    {'Mobile Claims': {'level': 2,
      'description': 'Allows customers to submit and track insurance claims through mobile apps'}},
    {'Mobile Content Management': {'level': 2,
      'description': 'Manages and updates the content displayed on the mobile app'}},
    {'Mobile Behavioural Analytics': {'level': 2,
      'description': 'Analyzes customer behavior on the mobile app to improve marketing strategies'}}]},
  'Assisted': {'level': 1,
   'description': 'Provides assistance to customers in accessing insurance services',
   'L2 capabilities': [{'Customer Engagement Management (CRM)': {'level': 2,
      'description': 'Manages customer interactions and relationships through a CRM system'}},
    {'Contact Centre & Telephony': {'level': 2,
      'description': 'Handles customer inquiries and support via contact center and telephony systems'}},
    {'Branch Management': {'level': 2,
      'description': 'Manages physical branches and customer interactions at branch locations'}},
    {'Webchat': {'level': 2,
      'description': 'Provides live chat support to customers on the website'}},
    {'Virtual Agent': {'level': 2,
      'description': 'Utilizes AI technology to provide automated assistance to customers'}},
    {'Social Engagement Management': {'level': 2,
      'description': 'Manages customer engagement through social media platforms'}}]},
  'Customer Experience & Management': {'level': 1,
   'description': 'Involves managing marketing activities, customer personalisation, and creating an exceptional customer journey to foster long-term relationships.',
   'L2 capabilities': [{'Marketing': {'level': 2,
      'description': 'Manages marketing activities and campaigns to attract and retain customers'}},
    {'Customer Identity': {'level': 2,
      'description': 'Manages customer identities and ensures privacy and security of customer information'}},
    {'Customer Consent': {'level': 2,
      'description': 'Obtains and manages customer consent for data usage and communication preferences'}},
    {'Customer Loyalty': {'level': 2,
      'description': 'Builds and maintains customer loyalty through rewards and incentives'}},
    {'CMDM': {'level': 2,
      'description': 'Manages customer data for a unified and consistent view across the organization'}},
    {'Personalisation': {'level': 2,
      'description': 'Delivers personalized experiences and offers to customers based on their preferences and behavior'}},
    {'Customer Payments': {'level': 2,
      'description': 'Manages customer payments and billing processes'}}]},
  'Partner Portals & Integration': {'level': 1,
   'description': 'Provides platform for partner organisations to access and manage insurance services, while also integrating these offerings into their products or platforms.',
   'L2 capabilities': [{'Partner Portal': {'level': 2,
      'description': 'Provides a portal for partners to access insurance services and collaborate with the company'}},
    {'Partner Management': {'level': 2,
      'description': 'Manages relationships and interactions with partner organizations'}},
    {'Assisted Experience': {'level': 2,
      'description': 'Provides a seamless and convenient experience for partners accessing insurance services with assistance if needed'}},
    {'Self-service Experience': {'level': 2,
      'description': 'Provides a self-service experience for partners to access and manage insurance services independently'}},
    {'Embedded Insurance': {'level': 2,
      'description': 'Integrates insurance offerings into partner products or platforms for a seamless customer experience'}}]},
  'Broker Portals & Integration': {'level': 1,
   'description': "Supports operations by providing a portal for brokers to access insurance services and manage policies, while also managing relationships and integrating with broker's CRM systems for enhanced efficiency",
   'L2 capabilities': [{'Broker Portal': {'level': 2,
      'description': "Provides a portal for brokers to access insurance services and manage their clients' policies"}},
    {'Broker Management': {'level': 2,
      'description': 'Manages relationships and interactions with broker organizations'}},
    {'Broker Integration': {'level': 2,
      'description': "Integrates brokerage systems with the company's insurance services for streamlined operations"}}]}},
 'Policy & Pricing': {'Personal Policy': {'level': 1,
   'description': 'Handles insurance policies for individuals',
   'L2 capabilities': [{'Policy Management': {'level': 2,
      'description': 'Manages and administers individual insurance policies'}},
    {'Insurance Product Management': {'level': 2,
      'description': 'Manages and updates insurance products for individuals'}},
    {'Billing Management': {'level': 2,
      'description': 'Manages billing and premium collection for individual insurance policies'}},
    {'Reinsurance': {'level': 2,
      'description': 'Manages reinsurance contracts for individual insurance policies'}}]},
  'Personal Pricing': {'level': 1,
   'description': 'Determines the price of insurance policies for individuals',
   'L2 capabilities': [{'Pricing Algorithm Management & Modelling': {'level': 2,
      'description': 'Manages and models pricing algorithms for individual insurance policies'}},
    {'Pricing Calculation': {'level': 2,
      'description': 'Calculates the premiums and pricing for individual insurance policies'}},
    {'Pricing Performance': {'level': 2,
      'description': 'Evaluates and monitors the performance of pricing strategies for individual insurance policies'}},
    {'Pricing Data Support': {'level': 2,
      'description': 'Provides data support and analysis for pricing decisions of individual insurance policies'}}]},
  'Personal Underwriting': {'level': 1,
   'description': 'Assesses the risk of insuring individuals',
   'L2 capabilities': [{'Underwriting Rules Management': {'level': 2,
      'description': 'Manages and updates underwriting rules for individual insurance policies'}},
    {'Underwriting Algorithm Management & Modelling': {'level': 2,
      'description': 'Manages and models underwriting algorithms for individual insurance policies'}},
    {'Underwriting Workflow (inc. Workbench)': {'level': 2,
      'description': 'Manages the workflow and processes of underwriting individual insurance policies'}},
    {'Portfolio Management': {'level': 2,
      'description': 'Manages and analyzes the risk portfolio of individual insurance policies'}}]},
  'Commercial Policy': {'level': 1,
   'description': 'Handles insurance policies for businesses',
   'L2 capabilities': [{'Policy Management': {'level': 2,
      'description': 'Manages and administers commercial insurance policies'}},
    {'Insurance Product Management': {'level': 2,
      'description': 'Manages and updates insurance products for businesses'}},
    {'Billing Management': {'level': 2,
      'description': 'Manages billing and premium collection for commercial insurance policies'}},
    {'Reinsurance': {'level': 2,
      'description': 'Manages reinsurance contracts for commercial insurance policies'}}]},
  'Commercial Pricing': {'level': 1,
   'description': 'Determines the price of insurance policies for businesses',
   'L2 capabilities': [{'Pricing Algorithm Management & Modelling': {'level': 2,
      'description': 'Manages and models pricing algorithms for commercial insurance policies'}},
    {'Pricing Calculation': {'level': 2,
      'description': 'Calculates the premiums and pricing for commercial insurance policies'}},
    {'Pricing Performance': {'level': 2,
      'description': 'Evaluates and monitors the performance of pricing strategies for commercial insurance policies'}},
    {'Pricing Data Support': {'level': 2,
      'description': 'Provides data support and analysis for pricing decisions of commercial insurance policies'}}]},
  'Commercial Underwriting': {'level': 1,
   'description': 'Assesses the risk of insuring businesses',
   'L2 capabilities': [{'Underwriting Rules Management': {'level': 2,
      'description': 'Manages and updates underwriting rules for commercial insurance policies'}},
    {'Underwriting Algorithm Management & Modelling': {'level': 2,
      'description': 'Manages and models underwriting algorithms for commercial insurance policies'}},
    {'Underwriting Workflow (Workbench)': {'level': 2,
      'description': 'Manages the workflow and processes of underwriting commercial insurance policies'}},
    {'Portfolio Management': {'level': 2,
      'description': 'Manages and analyzes the risk portfolio of commercial insurance policies'}}]}},
 'Claims, Supply Chain, Comms': {'Claims': {'level': 1,
   'description': 'Manages insurance claims from customers',
   'L2 capabilities': [{'Claims Management': {'level': 2,
      'description': 'Handles the end-to-end management of insurance claims'}},
    {'Fraud Detection': {'level': 2,
      'description': 'Identifies and detects fraudulent insurance claims'}},
    {'Recovery Management': {'level': 2,
      'description': 'Manages the recovery process for insurance claims'}}]},
  'Supply Chain': {'level': 1,
   'description': 'Manages the supply chain of insurance products',
   'L2 capabilities': [{'Supplier Management': {'level': 2,
      'description': 'Manages relationships with suppliers in the insurance supply chain'}},
    {'Parts & Supplier Sourcing': {'level': 2,
      'description': 'Sources and manages parts and suppliers for insurance products'}},
    {'Claims Fulfilment': {'level': 2,
      'description': 'Fulfills insurance claims by coordinating with suppliers'}}]},
  'Communications': {'level': 1,
   'description': 'Handles communications with customers and partners',
   'L2 capabilities': [{'Document Repository and Archival Management': {'level': 2,
      'description': 'Manages the storage and archival of insurance documents'}},
    {'Inbound Document Management': {'level': 2,
      'description': 'Manages incoming documents related to insurance operations'}},
    {'Outbound Document Management': {'level': 2,
      'description': 'Manages outgoing documents related to insurance operations'}}]}},
 'Digital Operations': {'People & Workplace Experience': {'level': 1,
   'description': 'Enhances the digital experience of employees and workplace operations',
   'L2 capabilities': [{'Recruiting': {'level': 2,
      'description': 'Manages the recruitment process for the insurance company'}},
    {'Workforce Management': {'level': 2,
      'description': 'Manages the workforce and schedules for the insurance company'}},
    {'Digital Workplace': {'level': 2,
      'description': 'Facilitates digital collaboration and productivity in the workplace'}},
    {'Learning & Development': {'level': 2,
      'description': 'Manages learning and development programs for employees'}},
    {'Performance & Remuneration': {'level': 2,
      'description': 'Manages employee performance and remuneration'}},
    {'Property': {'level': 2,
      'description': "Manages the insurance company's property assets"}}]},
  'Finance & Actuarial': {'level': 1,
   'description': 'Handles financial and actuarial operations digitally',
   'L2 capabilities': [{'Finance & Actuarial': {'level': 2,
      'description': 'Manages the financial and actuarial processes for the insurance company'}},
    {'Procurement': {'level': 2,
      'description': 'Manages the procurement of goods and services for the insurance company'}},
    {'Capital Asset Management': {'level': 2,
      'description': 'Manages the assets and capital investments of the insurance company'}}]},
  'Risk & Operations': {'level': 1,
   'description': 'Manages business risk and operations of the insurance company',
   'L2 capabilities': [{'Risk & Compliance Management': {'level': 2,
      'description': "Manages the insurance company's risk and compliance processes"}},
    {'Delivery & Change Management': {'level': 2,
      'description': 'Manages the delivery and change processes for insurance operations'}},
    {'Legal': {'level': 2,
      'description': 'Handles legal matters and compliance for the insurance company'}},
    {'Service Management': {'level': 2,
      'description': 'Manages the services provided by the insurance company'}},
    {'Engineering': {'level': 2,
      'description': 'Deliver software engineering services to build and run technology to enable insurance operations'}}]}},
 'Enabling Capabilities': {'Data': {'level': 1,
   'description': 'Manages and analyzes data for insurance operations',
   'L2 capabilities': [{'Data Warehousing & Orchestration': {'level': 2,
      'description': 'Manages the storage and orchestration of data for insurance operations'}},
    {'Analytics & Reporting': {'level': 2,
      'description': 'Performs analytics and generates reports for insurance operations'}},
    {'Archiving': {'level': 2,
      'description': 'Manages the archival of data for insurance operations'}},
    {'Master Data Management': {'level': 2,
      'description': 'Manages the master data for insurance operations'}},
    {'Knowledge Management': {'level': 2,
      'description': 'Manages and shares knowledge within the insurance company'}},
    {'Data Access & Governance': {'level': 2,
      'description': 'Manages access to and governance of data for insurance operations'}}]},
  'Security': {'level': 1,
   'description': 'Ensures the security and protection of insurance data and systems',
   'L2 capabilities': [{'Identity & Access Management': {'level': 2,
      'description': 'Manages the identities and access rights of users in the insurance company'}},
    {'Certificate Management': {'level': 2,
      'description': 'Manages digital certificates used for authentication and encryption'}},
    {'Protective Services': {'level': 2,
      'description': 'Manages security services and measures to protect insurance data and systems'}},
    {'Threat & Vulnerability Management': {'level': 2,
      'description': 'Identifies and manages security threats and vulnerabilities in insurance operations'}}]},
  'Infrastructure': {'level': 1,
   'description': 'Provides the necessary infrastructure to support insurance operations',
   'L2 capabilities': [{'Networking': {'level': 2,
      'description': 'Manages the networking infrastructure for insurance operations'}},
    {'Storage': {'level': 2,
      'description': 'Manages the storage infrastructure for insurance operations'}},
    {'Compute': {'level': 2,
      'description': 'Manages the computing infrastructure for insurance operations'}},
    {'API Management': {'level': 2,
      'description': 'Manages the APIs used for integration in insurance operations'}}]}}}

### trying async calls

In [27]:
import aiohttp
import asyncio
import json
from time import time
# from azure.identity import DefaultAzureCredential

# # Function to initialize GPT models
# def initialize_gpt_models(temperature: float = 0.0, top_p: float = 0.5):
#     config = AzureDeploymentConfig()
#     token_provider = get_bearer_token_provider(
#         DefaultAzureCredential(exclude_interactive_browser_credential=False), config.token_scope
#     )
#     main_model = AzureChatOpenAI(
#         azure_endpoint=str(config.azure_endpoint),
#         deployment_name=config.deployment_name,
#         openai_api_version=config.openai_api_version,
#         azure_ad_token_provider=token_provider,
#         temperature=temperature,
#         top_p=top_p
#     )

#     json_model = AzureChatOpenAI(
#         azure_endpoint=str(config.azure_endpoint),
#         deployment_name=config.deployment_name,
#         openai_api_version=config.openai_api_version,
#         azure_ad_token_provider=token_provider,
#         temperature=temperature,
#         top_p=top_p,
#         model_kwargs={"response_format": {"type": "json_object"}}
#     )
#     return main_model, json_model


# Asynchronous function to fetch GPT model response
async def fetch_gpt_response(prompt, main_model, json_model): # takes in session if pursuing the http route
    raw = await asyncio.to_thread(main_model.invoke, prompt)    
    raw_text = raw.content
    raw_text_validated = validate_json_gpt_model(raw_text, json_model)
    try:
        raw_json = json.loads(raw_text_validated)
        return raw_json
    except Exception as e:
        print("The json_model failed to return valid json for ", raw_text[:100], ". . .")
        return raw_text

         # headers = {
    #     "Content-Type": "application/json",
    #     "Authorization": f"Bearer {await main_model.azure_ad_token_provider.get_token()}"
    # }
    # data = {
    #     "prompt": prompt,
    #     "max_tokens": 100
    # }
    # async with session.post(main_model.azure_endpoint, headers=headers, json=data) as response:
    #     raw_text = await response.text()
    

# async Function to get REALL from input using GPT
async def get_real_from_input_gpt(input_data, pt, main_model, json_model): # was taking in session parameter earlier for fetch gpt

    start = time()
    
    p1_1_r = PromptTemplate.from_template(pt["p1"]["get_roles"]).format(inp_ps = input_data)
    p1_2_e = PromptTemplate.from_template(pt["p1"]["get_events"]).format(inp_ps = input_data)
    
    role_json = await fetch_gpt_response(p1_1_r, main_model, json_model)
    print("role_json generated.")
    
    events_json = await fetch_gpt_response(p1_2_e, main_model, json_model)
    print("event_json generated.")
    
    p1_3_a = PromptTemplate.from_template(pt["p1"]["get_activities"]).format(inp_ps = input_data,
                                                                             events_data = events_json)
    activities_json = await fetch_gpt_response(p1_3_a, main_model, json_model)
    print("activities_json generated.")

    # Prepare prompts and Sequential requests due to dependency
    with open("../st/files/cpm_ins_L1.json", "r") as fp:
        all_l1_capability_model_json = json.load(fp)
    with open("../st/files/cpm_ins_L2.json", "r") as fp:
        all_l2_capability_model_json = json.load(fp)

    p1_4_l1 = PromptTemplate.from_template(pt["p1"]["get_l1_cap"]).format(inp_ps = input_data, 
                                                                        roles_data = role_json,
                                                                        events_data = events_json,
                                                                        activities_data = activities_json,
                                                                        level1_capability_model = all_l1_capability_model_json)
     

    l1_json =  await fetch_gpt_response( p1_4_l1, main_model, json_model)
    print("l1_json generated.")

    if is_json_gpt(json.dumps(l1_json)):
        filtered_l1_capabilities = extract_impacted_capabilities_L1(l1_json)
        relevant_l2_for_l1_json = filter_l2_capabilities_for_l1(filtered_l1_capabilities, all_l2_capability_model_json)

        p1_5_l2 = PromptTemplate.from_template(pt["p1"]["get_l2_cap"]).format(inp_ps = input_data, 
                                                                        roles_data = role_json,
                                                                        events_data = events_json,
                                                                        activities_data = activities_json,
                                                                        sample_l2_cap = pt["p1"]["sample_l2_cap"],
                                                                        filtered_level2_capability_model=relevant_l2_for_l1_json)
        
    else :
        p1_5_l2 = PromptTemplate.from_template(pt["p1"]["get_l2_cap"]).format(inp_ps = input_data, 
                                                                        roles_data = role_json,
                                                                        events_data = events_json,
                                                                        activities_data = activities_json,
                                                                        sample_l2_cap = pt["p1"]["sample_l2_cap"],
                                                                        filtered_level2_capability_model=all_l2_capability_model_json)
        
    
    l2_json = await fetch_gpt_response( p1_5_l2, main_model, json_model)
    print("l2_json created")
    
    end = time()
    print(end-start)

    return role_json, events_json, activities_json, l1_json, l2_json


# Function to save results incrementally
def save_results_incrementally(merged_pcs, page_num, role_json, events_json, activities_json):
    merged_pcs[page_num].update({"role_json": role_json, "events_json": events_json, "activities_json": activities_json})
    with open("merged_pcs.json", "w") as jsn:
        json.dump(merged_pcs, jsn)


# Main function to process pages
async def process_pages(merged_pcs, pt):
    # Initialize GPT models once
    main_model, json_model = initialize_gpt_models()

    # async with aiohttp.ClientSession() as session:
    tasks = [
            get_real_from_input_gpt(value["pcs_content"], pt, main_model, json_model)
            for page_num, value in merged_pcs.items()
        ]

    results = await asyncio.gather(*tasks, return_exceptions=True)

    for i, (page_num, value) in enumerate(merged_pcs.items()):
        result = results[i]
        if isinstance(result, Exception):
            print(f"Error processing page {page_num}: {result}")
        else:
            role_json, events_json, activities_json, l1_json, l2_json = results[i]
            save_results_incrementally(merged_pcs, page_num, role_json, events_json, activities_json)
# =============================================================try 2, errorr : ValueError: <coroutine object as_completed.<locals>._wait_for_one at 0x158431840> is not in list
        # for task in asyncio.as_completed(tasks):
        #     result = await task
        #     page_num = tasks.index(task)
        #     print(f"Result for page {page_num}: {result}")  # Debugging statement
        #     if isinstance(result, Exception):
        #         print(f"Error processing page {page_num}: {result}")
        #     else:
        #         try:
        #             role_json, events_json, activities_json = result
        #             save_results_incrementally(merged_pcs, page_num, role_json, events_json, activities_json)
        #             print(f"Completed processing page {page_num}")
        #         except ValueError as e:
        #             print(f"Error unpacking result for page {page_num}: {e}")
# =============================================================try 3  error KeyError: <coroutine object as_completed.<locals>._wait_for_one at 0x158d76040>
    # tasks = {
    #     asyncio.create_task(get_real_from_input_gpt(value["content"], pt, main_model, json_model)): page_num
    #     for page_num, value in merged_pcs.items()
    # }

    # for task in asyncio.as_completed(tasks):
    #     result = await task
    #     page_num = tasks[task]
    #     print(f"Result for page {page_num}: {result}")  # Debugging statement
    #     if isinstance(result, Exception):
    #         print(f"Error processing page {page_num}: {result}")
    #     else:
    #         try:
    #             role_json, events_json, activities_json, l1, l2 = result
    #             save_results_incrementally(merged_pcs, page_num, role_json, events_json, activities_json)
    #             print(f"Completed processing page {page_num}")
    #         except ValueError as e:
    #             print(f"Error unpacking result for page {page_num}: {e}")

# =============================================================try 4 using tuples of tasks 
    # tasks = [
    #     asyncio.create_task(get_real_from_input_gpt(value["content"], pt, main_model, json_model))
    #     for page_num, value in merged_pcs.items()
    # ]

    # for task in asyncio.as_completed(tasks):
    #     result = await task
    #     print(task)
    #     page_num = tasks.index(task)
    #     print(f"Result for page {page_num}: {result}")  # Debugging statement
    #     if isinstance(result, Exception):
    #         print(f"Error processing page {page_num}: {result}")
    #     else:
    #         try:
    #             role_json, events_json, activities_json , l1, l2= result
    #             save_results_incrementally(merged_pcs, page_num, role_json, events_json, activities_json)
    #             print(f"Completed processing page {page_num}")
    #         except ValueError as e:
    #             print(f"Error unpacking result for page {page_num}: {e}")




# Run the main function
# if __name__ == "__main__":
#     merged_pcs = {}  # Your merged_pcs dictionary
#     pt = {}  # Your pt dictionary
#     asyncio.run(process_pages(merged_pcs, pt))

In [42]:
import json 
with open("../st/files/merged_pcs.json", "r") as ad:
    merged_pcs = json.load(ad)
    # Your merged_pcs dictionary


pt = pt = {   "inp_ps" : """
        Background
        An underwriting restriction may be implemented in response to a major event or the risk of a major event occurring  such as;  Earthquake, Tsunami, Volcano, Wildfire, Ex-tropical cyclone.
        An underwriting restriction is a restriction on the sale or increases in sum insured of risks within specific lines of business based on a geographical location. 
        Problem
        Due to the nature of events that trigger underwriting restrictions,  these need to be implemented as soon as possible after a decision has been made.  These events can happen outside of standard business hours.  
        The IAG technical landscape is varied, complex and constantly changing and it is not clear how to get restrictions implemented or updated across brands, lines of business and geographical locations.   Anecdotally outside of  Personal lines State/Huon, State/AMI digital and AON CPF,  Portfolio have very little visibility on how to implement systems restrictions. 

         In the past getting system restrictions in place has been adhoc, using back channels rather than the Tech Front Door, with Portfolio team members reliant upon who they know rather than following  a prescribed Tech & Ops process. If the “go-to person” is not around then Portfolio may not know who to contact.
        """,
    "p1":{
        "get_roles":"""
                    Using formal software architecture methodology, you will analyse the following problem statement and context information regarding a possible new opportunity for architecture development:

                      {inp_ps}

                      As a first step, extract all user or system roles from the project brief. Use only the information from the above project brief.

                      Return the response in the following JSON format. Return "Empty" if no information could be extracted from the project brief. Do not return any explanation. Your response must be a valid JSON document only.:

                      {{
                      "user_roles" : [],
                      "system_roles" : []
                      }}
                      
                      Pass your final output again through the model to verify if its a valid json and return the final output json.
                """,
        "get_events": """
                      Using formal software architecture methodology, you will analyse the following following problem statement and context information regarding a possible new opportunity for architecture development:

                      {inp_ps}

                      As a first step, extract all manual or automated events from the project brief. Use only the information from the above project brief. Events are triggers that a system or user role can initiate when the solution is deployed into the insurance firm.

                      Return the response in the following JSON format. Return "Empty" if no information could be extracted from the project brief. Do not return any explanation. Your response must be a valid JSON document only.:

                      {{
                      "manual_events" : {{"event name": "event description"}},
                      "automated_events" :  {{"event name": "event description"}}
                      }}  
                      
                      Pass your final output again through the model to verify if its a valid json and return the final output json.
                      """,
        "get_activities" : """
                    Using formal software architecture methodology, you will analyse the following following problem statement and context information regarding a possible new opportunity for architecture development:

                          {inp_ps}

                          As a first step, extract all activities from the project brief. Use only the information from the above project brief. An activity will have a clear objective and will result in changing a Data object. The following JSON list are the triggers related to the project brief above. Each of these triggers will create activities.

                          {events_data}

                          Return the response in the following JSON format. Return "Empty" if no information could be extracted from the project brief. Do not return any explanation. Your response must be a valid JSON document only.:

                          {{
                          "activities" : {{"activity name": "activity objective description"}},
                          "data" : {{"activity name": "activity data transformations"}}
                          }}  
                      
                      Pass your final output again through the model to verify if its a valid json and return the final output json.
                      
                """, 
        "get_l1_cap" : """
                    Using formal software architecture methodology, you will analyse the following following problem statement and context information regarding a possible new opportunity for architecture development:

                  {inp_ps}

                  You have pre-analysed the roles, events in the new system and the expected behaviours from the brief. This is available below in JSON form.

                  Pre-analysed tentative roles(can be more):
                  {roles_data}

                  Pre-analysed events:
                  {events_data}

                  Pre-analysed system behaviours:
                  {activities_data}


                  Your next step is to identify the impacts against the capability model below. Describe the identified impact in a child object under each capability. Use only the information from the above project brief and the pre-analysed data along. Return "Empty" if the capability is not directly impacted based on the project brief or pre-analysed data.

                  An example description of impact for the Web capability is shown below
                  "Web": {{
                          "level": 1,
                          "description": "Allows customers to access insurance services through the web",
                          "impact": "API documentation in an API portal. Technical and non-technical guides for partners to integrate insurance products into their business. Partner self-service functionality, such an onboarding, feedback and support forums, security and access control, downloadable libraries, SDKs and code samples.",
                        }}

                  Return the response in the following JSON format. Do not return any explanation. Your response must be a valid JSON document only to be used for further data pipeline:

                  Capability Model
                  {level1_capability_model}  
                      
                      Pass your final output again through the model to verify if its a valid json and return the final output json.
                      

                  """,
        "sample_l2_cap" : """
                    {"Web": {\
                          "level": 1,
                          "description": "Allows customers to access insurance services through the web",
                          "impact": "API documentation in an API portal. Technical and non-technical guides for partners to integrate insurance products into their business. Partner self-service functionality, such an onboarding, feedback and support forums, security and access control, downloadable libraries, SDKs and code samples.",
                          "L2 capabilities": [{"Web Sales (Quote and Buy)": 
                                                      {"level": 2, "description": "Enables customers to obtain quotes and purchase insurance policies online", "impact":"Empty"}
                                                      }, \
                                              {"Web Self Service": 
                                                      {"level": 2, "description": "Provides self-service options for customers to manage their insurance policies online", "impact": "New API Portal for partners and embedded insurance APIs"}
                                                      }, 
                                              {"Web Claims": 
                                                  {"level": 2, "description": "Allows customers to submit and track insurance claims through the web", "impact":"Empty"}
                                                  }, \
                                              {"Web Content Management": 
                                                  {"level": 2, "description": "Manages and updates the content displayed on the web portal", "impact": "Technical documentation and content, workflows to publish, lifecycle and service information related to APIs" }
                                                  }, 
                                              {"Web Behavioural Analytics": 
                                                  {"level": 2, "description": "Analyzes customer behavior on the web portal to improve marketing strategies", "impact":"Analytics related to partner staff such as developers and product managers utilisation of the API portal. Feedback forms on how APIs could be improved."}\
                                                      }]\
                          }}\
                      """,
        "get_l2_cap" :"""
                    Using formal software architecture methodology, you will analyse the following following problem statement and context information regarding a possible new opportunity for architecture development:

                  {inp_ps}\

                  You have pre-analysed the roles, events in the new system and the expected behaviours from the brief. This is available below in JSON form.

                  Pre-analysed roles:
                  {roles_data}\

                  Pre-analysed events:
                  {events_data}\

                  Pre-analysed system behaviours:
                  {activities_data}\

                  Your next step is to identify the impacts against the capability model below. Describe the identified impact in a child object under each capability. Use only the information from the above project brief and the pre-analysed data along with Pre-analysed system impacts. Return "Empty" if the capability is not directly impacted based on the project brief or pre-analysed data.

                  An example description of sample impact for the Web capability is shown below
                  {sample_l2_cap}\

                  Return the response in the following JSON format. Do not return any explanation. Your response must be a valid JSON document only. Not a formatting with triple quotes, just a valid json string that starts and ends with curly brackets.

                  Capability Model
                  {filtered_level2_capability_model}\  
                      
                      Pass your final output again through the model to verify if its a valid json and return the final output json.
                      
"""
      },
    "p2":{
        "get" : ""
    },
    "p3":{
        "sample_final_json_output_old" : """{ 
                      "Reuse" : { "AD number" : { "L1" : {"Customer" : {"Policy & Pricing": {"Personal Pricing" : {"descrpition": "Determines the price of insurance policies for individuals", "impact" : "Implementation of an interim pricing solution for CGU Direct Home, Motor & Niche, due to the unavailability of the PRICE application for production"}}}}},
                                                "L2" : { "L1" : {"Customer" : {"Policy & Pricing": {"Personal Pricing" : {"descrpition": "Determines the price of insurance policies for individuals", "L2 capabilites" : [{"Pricing Calculation" : "Interim solution for peril pricing calculation for CGU Direct Home, Motor & Niche"}, {"other L2 cap" : "its impact"}]}}}}},
                                { "AD number" : { "L1" : {capabilities fulfilled},
                                                     "L2" : {capabilities fulfilled}}}
                                                     },
                      "Enhance" : { "AD number" : { "L1" : {partial capabilities fulfilled},
                                                        "L2" : {partial capabilities fulfilled}}},
                      "New" :   { "suggested new title of AD" : { "L1" : {capabilities that it should fulfill},
                                                              "L2" : {capabilities that it should fulfill}}}
                    }""", 
        "sample_final_json_output" : """{ 
                      "Reuse" : { "AD number" : { "L0" : 
                                                      {"L1" : 
                                                              {"L2": {"description" : "Determines the price of insurance policies for individuals", 
                                                                          "impact" : "Implementation of an interim pricing solution for CGU Direct Home, Motor & Niche, due to the unavailability of the PRICE application for production"}}}},
                                  "other ADs to be reused" : {}, 
                                  ... },
                      "Enhance" : { "AD number" : { "L0" : 
                                                      {"L1" : 
                                                              {"L2": {"description" : "Determines the price of insurance policies for individuals", 
                                                                          "impact" : "Implementation of an interim pricing solution for CGU Direct Home, Motor & Niche, due to the unavailability of the PRICE application for production"}}}},
                                  "other ADs to be enhanced" : {}, 
                                  ... },
                        "New" :   { "suggested new title of AD" : { "L0" : 
                                                      {"L1" : 
                                                              {"L2": {"description" : "Determines the price of insurance policies for individuals", 
                                                                          "impact" : "Implementation of an interim pricing solution for CGU Direct Home, Motor & Niche, due to the unavailability of the PRICE application for production"}}}},
                                  "other new ADs" : {} ...}
                    }""",                                 
        "get_final_out" : """
                   Using formal software architecture methodology, you will analyse the following following problem statement and context information regarding a possible new opportunity for architecture development:
                   {inp_ps}
                   You have pre-analysed the roles, events and activities earlier based on which you have come up with the following Level-1 and Level-2 capability statements for this opportunity.
                   L1 capability statements : 
                   {inp_l1}
                   L2 capability statements : 
                   {inp_l2}
                   
                   The input problem statement and context were also vector-matched against all previous Architecture Decisions which led us to getting a few top-matched architecture decisions. 
                   These top-matched Architecture Decisions (ADs) were also passed through similar prompt-chains to get roles, events, activities and finally their respective L1 and L2 capabilities. 
                   Here is a list of those ADs with their problem statements, contexts and L1, L2 capabilities. 
                   {top_matched_ads_with_l1_l2}
                   
                   Your job is to analyse the problem statement, level1 and level2 capabilities of the initial input against the problem statement, context, l1 and l2 capabilities of each of the top-matched ADs mentioned subsequently.
                   Then understand how each of the matched ADs fulfill which of the capabilities required by the input.
                   Then provide a detailed structured json of 
                   - which ADs can be reused as is, with the capabilities that they solve for, 
                   - which ADs require certain enhancements to fulfill more capapbilities and 
                   - which new Architectures Decisions need to be taken for the rest of the novel capbilities that need to be fulfilled in this opportunity.
                   
                   A sample json output would look like this : 
                   {sample_final_json_output}
                                                                
                   
            """
    }
} 
# Your pt dictionary

In [32]:
import nest_asyncio 

nest_asyncio.apply()

In [33]:
# import nest_asyncio 

# nest_asyncio.apply()

asyncio.run(process_pages(merged_pcs, pt))

GPT main_model failed to provide valid json.
role_json generated.
GPT main_model failed to provide valid json.
role_json generated.
GPT main_model failed to provide valid json.
role_json generated.
GPT main_model failed to provide valid json.
role_json generated.
GPT main_model failed to provide valid json.
role_json generated.
GPT main_model failed to provide valid json.
role_json generated.
GPT main_model failed to provide valid json.
role_json generated.
GPT main_model failed to provide valid json.
role_json generated.
GPT main_model failed to provide valid json.
role_json generated.
GPT main_model failed to provide valid json.
role_json generated.
GPT main_model failed to provide valid json.
role_json generated.
GPT main_model failed to provide valid json.
role_json generated.
GPT main_model failed to provide valid json.
role_json generated.
GPT main_model failed to provide valid json.
role_json generated.
GPT main_model failed to provide valid json.
role_json generated.
GPT main_model failed to provide valid json.
role_json generated.
GPT main_model failed to provide valid json.
event_json generated.
GPT main_model failed to provide valid json.
event_json generated.
GPT main_model failed to provide valid json.
event_json generated.
GPT main_model failed to provide valid json.
event_json generated.
GPT main_model failed to provide valid json.
event_json generated.
GPT main_model failed to provide valid json.
event_json generated.
GPT main_model failed to provide valid json.
event_json generated.
GPT main_model failed to provide valid json.
event_json generated.
GPT main_model failed to provide valid json.
event_json generated.
GPT main_model failed to provide valid json.
event_json generated.
GPT main_model failed to provide valid json.
event_json generated.
GPT main_model failed to provide valid json.
event_json generated.
GPT main_model failed to provide valid json.
event_json generated.
GPT main_model failed to provide valid json.
event_json generated.
GPT main_model failed to provide valid json.
event_json generated.
GPT main_model failed to provide valid json.
activities_json generated.
GPT main_model failed to provide valid json.
event_json generated.
GPT main_model failed to provide valid json.
activities_json generated.
GPT main_model failed to provide valid json.
activities_json generated.
GPT main_model failed to provide valid json.
activities_json generated.
GPT main_model failed to provide valid json.
activities_json generated.
GPT main_model failed to provide valid json.
activities_json generated.
GPT main_model failed to provide valid json.
activities_json generated.
GPT main_model failed to provide valid json.
activities_json generated.
GPT main_model failed to provide valid json.
activities_json generated.
GPT main_model failed to provide valid json.
activities_json generated.
GPT main_model failed to provide valid json.
activities_json generated.
GPT main_model failed to provide valid json.
activities_json generated.
GPT main_model failed to provide valid json.
activities_json generated.
GPT main_model failed to provide valid json.
activities_json generated.
GPT main_model failed to provide valid json.
activities_json generated.
GPT main_model failed to provide valid json.
activities_json generated.
GPT main_model failed to provide valid json.
l1_json generated.
GPT main_model failed to provide valid json.
l1_json generated.
GPT main_model failed to provide valid json.
l1_json generated.
GPT main_model failed to provide valid json.
l1_json generated.
GPT main_model failed to provide valid json.
l1_json generated.
GPT main_model failed to provide valid json.
l1_json generated.
GPT main_model failed to provide valid json.
l1_json generated.
GPT main_model failed to provide valid json.
l1_json generated.
GPT main_model failed to provide valid json.
l1_json generated.
GPT main_model failed to provide valid json.
l1_json generated.
GPT main_model failed to provide valid json.
l1_json generated.
GPT main_model failed to provide valid json.
l1_json generated.
GPT main_model failed to provide valid json.
l1_json generated.
GPT main_model failed to provide valid json.
l1_json generated.
GPT main_model failed to provide valid json.
l1_json generated.
GPT main_model failed to provide valid json.
l1_json generated.
l2_json created
1065.2852187156677
GPT main_model failed to provide valid json.
l2_json created
1108.2189540863037
GPT main_model failed to provide valid json.
l2_json created
1147.3249740600586
GPT main_model failed to provide valid json.
The json_model failed to return valid json for  {
  "Customer": {
    "Web": {
      "level": 1,
      "description": "Allows customers to access in . . .
l2_json created
1281.6659450531006
l2_json created
1281.6666810512543
l2_json created
1281.6669421195984
l2_json created
1281.6678938865662
l2_json created
1281.6664090156555
GPT main_model failed to provide valid json.
The json_model failed to return valid json for  ```json
{
  "Customer": {
    "Web": {
      "level": 1,
      "description": "Allows customers to a . . .
l2_json created
1414.4249489307404
GPT main_model failed to provide valid json.
l2_json created
1445.9939291477203
GPT main_model failed to provide valid json.
The json_model failed to return valid json for  {
    "Customer": {
        "Web": {
            "level": 1,
            "description": "Allows cust . . .
l2_json created
1601.452269077301
l2_json created
1601.4521088600159
GPT main_model failed to provide valid json.
The json_model failed to return valid json for  ```json
{
  "Customer": {
    "Web": {
      "level": 1,
      "description": "Allows customers to a . . .
l2_json created
1774.0282440185547
l2_json created
1774.0294089317322
GPT main_model failed to provide valid json.
l2_json created
1812.5603420734406
GPT main_model failed to provide valid json.
The json_model failed to return valid json for  {
    "Customer": {
        "Web": {
            "level": 1,
            "description": "Allows cust . . .
l2_json created
1973.3501455783844

In [ ]:
l2_json created
764.7771492004395
l2_json created
764.778077840805
l2_json created
764.7849771976471
l2_json created
764.785315990448
l2_json created
764.7854850292206

In [47]:
!az login

the following arguments are required: _subcommand

Examples from AI knowledge base:
https://aka.ms/cli_ref
Read more about the command in reference docs

In [19]:
!azd auth login 

# need to run this every few hours or every day ?

Logged in to Azure.ing subscriptions...

In [ ]:
!azd auth token --output json
{
  "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6IktRMnRBY3JFN2xCYVZWR0JtYzVGb2JnZEpvNCIsImtpZCI6IktRMnRBY3JFN2xCYVZWR0JtYzVGb2JnZEpvNCJ9.eyJhdWQiOiJodHRwczovL21hbmFnZW1lbnQuYXp1cmUuY29tLyIsImlzcyI6Imh0dHBzOi8vc3RzLndpbmRvd3MubmV0LzdkODQ3YjAwLTljYjItNGU4Yi05ZjE0LWZiNThkZTRiY2RkZS8iLCJpYXQiOjE3MjM4MjY5NzAsIm5iZiI6MTcyMzgyNjk3MCwiZXhwIjoxNzIzODMxMDk2LCJhY3IiOiIxIiwiYWlvIjoiQVZRQXEvOFhBQUFBVFBhR0dWdW8yY3BBTWRPaEk3OVpXSS9wZXpveExadnVHdThlYmNObFZUYTRyS0Fnd2xOQ0NBanNnRjhiczZvbGVoMjBIQ0drSm9Jd3BWeDZlZjJNMW5pZ09aSUhwY2tWZUN5eVgwb01Tcjg9IiwiYW1yIjpbInB3ZCIsIm1mYSJdLCJhcHBpZCI6IjA0YjA3Nzk1LThkZGItNDYxYS1iYmVlLTAyZjllMWJmN2I0NiIsImFwcGlkYWNyIjoiMCIsImRldmljZWlkIjoiMDU3OTU0MWQtOTU1Ni00NzQ3LTkwZTYtMzczYjdiM2FjMzFkIiwiZmFtaWx5X25hbWUiOiJNb3J5ZSIsImdpdmVuX25hbWUiOiJWaWtlc2giLCJncm91cHMiOlsiNmYxMDA2MDItZjRmYS00ZDJhLWEyOTktOWJlNmIxMTk5NjhmIiwiMmQyOTFlMGYtMjE4NC00MWVkLThjYzEtODQ0MWI5ODkwNGYwIiwiMTczMDkwMTMtNTc2Mi00ZWEzLWE0NTktNDMwMDE1OTgyY2MzIiwiZTUwYzNmMjUtZGQyMS00Y2Q0LTlhNDktZTkzNDA0NDc1MjA1IiwiMmViYmE0MjUtNzhhZS00NDM1LTliM2MtMGUzYjA5NDQ4YTJlIiwiYWJhMzQzMjgtZTU1Ny00NjM1LWEzMDctYTA5YjY4M2FkNjE1IiwiOTBiZDU2MjktMWQxNi00MmVjLWI4MWMtNWJhZTZkZTFjMmVjIiwiNzJjMDMzNDEtNDA0OC00NTkwLTk2MjItMDBkMWZjZmU5MzcxIiwiNGE2Mjk2NGUtNmI3NS00NjRmLTkwNGMtZjgwM2FjYTM2ZjIzIiwiYmMyNWZiNTEtNjExMS00YjVjLTg1MmEtZDY4NDA0YjE3Y2Q2IiwiMjU0MGUyNWMtZTliOC00ZDBhLTk2Y2EtMjg3YjUyNDVkNjY4IiwiN2FjNGM2NjYtYmMwOC00NDg5LWI5YmMtZTdmMWU0M2E1YTU0IiwiZmNhYWFhNzYtMTg0ZS00M2QxLThlZjgtNmRmODYwNmYxMDg4IiwiZDJiYWI3NzgtZDNmMi00Nzg1LThmYzctMzY0MDYzMzkwMmQ0IiwiNjhlOGRlNzgtZmE3Yy00ZWU3LWI5NDMtNTNkMjc3YjIyMmI4IiwiNDBiNmEyODEtOTI1Zi00NzdjLTkzNjgtNGJlYjU2N2YwNGQzIiwiN2UxMWJlODgtMWIzOC00YTFmLWI5MDEtOGExMjFiZjMyODdlIiwiZTRlOTgwOGMtZmNiMy00YTAwLWE4ODYtNTExYTk1YjcyMzNkIiwiNzU1ZjJlOWUtZGE5OC00ZTE0LWFkNTMtNDc3ZWZiNzE2ZGRmIiwiMWExZWQyOWYtZWQ0Zi00ZGZjLTg1YjQtMDE3NjY4MmU0YmU2IiwiNzdmZDhiYTQtMDYyMi00OGRmLWIxOTItNjNkOTI4NGMyYzk4IiwiYzRhMGM1YTQtZDZkOC00MDkwLWIxZWYtZDNjZjFmY2UwNWFlIiwiYTA2MjE4YWQtY2Y4MS00YzE2LTk1OWMtMDE0ODM3NmIyOTJmIiwiMDE3MDEzYjUtOTAwYS00YmRiLTlhMjUtZThkYWQ5MTQwNTIwIiwiNjQ2NGMwYjgtMjk1YS00MWY0LWI0MmQtNGUzNjVlYmEzNDY0IiwiNjM5ODc3YmMtNTZkZS00NWE0LWJkMmItZjlhYWQ2NDY0NDYyIiwiYmY3NTFjYzAtYTliNC00MTExLWJhZTAtNDQ1NmU3MzdlYWM0IiwiY2MyOThhYzYtZjg4Yy00MDA1LWJkZGQtZjI4ZTA2OTRiY2M5IiwiYzg4YjU3YzctODI2Mi00OGY5LThkNmMtY2VhMmVmYzUyOGQxIiwiOTFjZmVjZDUtYTU4Mi00NTE5LWIzMWMtMjE2YjQyMzQwMzY1IiwiYzc3ZTA3ZDktYWZlYy00OTIwLTlkNzYtNGFhYWM0YzY1YzcwIiwiZjk5NGE0ZGMtOGYxMi00YTRhLTlmZmEtMGNlM2FkMmY2YmZhIiwiNzIwYWVkZTUtOTEwYy00OWU0LWEyZGUtZjBmZjExMDc2NGFiIiwiNTViYmY1ZTgtNmUwYi00ZDdlLWI5YmItZGEyZDY4YTBmNmFkIiwiM2Y4YzFhZWEtNDk4Zi00ZmVlLWJjYjgtZWM5MTZjMjc0YWZlIiwiNDVlNmQzZWUtYmRlZi00NmE0LThkZDItMTFlNWQ4ZmNhYWI4IiwiZTQxMzI1ZjEtMDdlMS00M2RjLTgwYzMtMDRiNDA0NWFiMDEwIiwiMzIzZDY5ZjItM2NjZS00OTZhLTk3YzYtMDAwYjZlZjY4YzhlIl0sImlkdHlwIjoidXNlciIsImlwYWRkciI6IjI0LjIzOS4xMzMuNjYiLCJuYW1lIjoiVmlrZXNoIE1vcnllIiwib2lkIjoiODJkMzkxYzMtODA3Mi00MTc1LTg4MmEtODFiZDUxNjU1ZTgwIiwib25wcmVtX3NpZCI6IlMtMS01LTIxLTY4MzI0MDAyMS0yMzQ2MDU3MzcyLTM5ODkyODM2MjAtNDY2NjgyIiwicHVpZCI6IjEwMDMyMDAzN0EzODZBOUEiLCJyaCI6IjAuQVVFQUFIdUVmYktjaTA2ZkZQdFkza3ZOM2taSWYza0F1dGRQdWtQYXdmajJNQk5CQU9rLiIsInNjcCI6InVzZXJfaW1wZXJzb25hdGlvbiIsInN1YiI6ImFqRU0zdnJ1OFVCNDFWOVcxTVA0Uk9FZ3A0bWdXeGpXbE52bjRWb0gxSUkiLCJ0aWQiOiI3ZDg0N2IwMC05Y2IyLTRlOGItOWYxNC1mYjU4ZGU0YmNkZGUiLCJ1bmlxdWVfbmFtZSI6IlZpa2VzaC5Nb3J5ZUBpYWcuY29tLmF1IiwidXBuIjoiVmlrZXNoLk1vcnllQGlhZy5jb20uYXUiLCJ1dGkiOiJBN0JRei1Gd0FrNk9qSmNMSHhaVUFBIiwidmVyIjoiMS4wIiwid2lkcyI6WyJiNzlmYmY0ZC0zZWY5LTQ2ODktODE0My03NmIxOTRlODU1MDkiXSwieG1zX2lkcmVsIjoiMSAyMiIsInhtc190Y2R0IjoxNDAyMDUxMzE2fQ.qYfmwcqCd5JOotpVrzpsIYT9uDeUZlfPgColEOssjdsqrTSi1LAzuItaINLJIwrayhyksVETVFLfJErK5uGrlBJguWn9dhSeAlFQWCMviw30DFO5XywbPH0Zim6ktQ-K89zRpCFskLtjXjjkL1hmsP3Ya4RyEFBomM9U6mxMTESySPjP_fKRZPU3JybWuLWi8V_D0ftno7_u81HnTLExv2JSzLYgE1gli6UkJk27getUyx13cXjamkjHEfsH0qOWObXdtfPgat1y37YFtmHpuc8_y1TKPnWs7dQyAeDunnaP_-zXtM6jWhQYGhQfwA15-0EJZ8QOU22qNgZiA_xhDw",
  "expiresOn": "2024-08-16T17:58:15Z"
}

In [39]:
!export REQUESTS_CA_BUNDLE='/Users/s748779/.ssh/IAG_proxy_chain.pem'

In [ ]:
export AZURE_CLIENT_ID="your-client-id"
export AZURE_TENANT_ID="your-tenant-id"
export AZURE_CLIENT_CERTIFICATE_PATH="/path/to/your/certificate.pem"
export AZURE_CLIENT_CERTIFICATE_PASSWORD="your-certificate-password"  # Optional

In [ ]:
!az account get-access-token 

# {
#   "accessToken": "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6IktRMnRBY3JFN2xCYVZWR0JtYzVGb2JnZEpvNCIsImtpZCI6IktRMnRBY3JFN2xCYVZWR0JtYzVGb2JnZEpvNCJ9.eyJhdWQiOiJodHRwczovL21hbmFnZW1lbnQuY29yZS53aW5kb3dzLm5ldC8iLCJpc3MiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC83ZDg0N2IwMC05Y2IyLTRlOGItOWYxNC1mYjU4ZGU0YmNkZGUvIiwiaWF0IjoxNzIzODI2MTU3LCJuYmYiOjE3MjM4MjYxNTcsImV4cCI6MTcyMzgzMTgzOSwiYWNyIjoiMSIsImFpbyI6IkFWUUFxLzhYQUFBQUlTTXBxbDBvSGRJS3RBd1kzV0c2cDdwdHFFNEpRRFMrSXNlNFNvS29QVno1c3FkQmRCTzc5YXAwZDNhLzNwZ1RsN2kzR3lIM3V2VWw1Y0RoUEFTcnhTdTg3bm9Ydi8vVUhNUHo4TDQ0b0pJPSIsImFtciI6WyJwd2QiLCJtZmEiXSwiYXBwaWQiOiIwNGIwNzc5NS04ZGRiLTQ2MWEtYmJlZS0wMmY5ZTFiZjdiNDYiLCJhcHBpZGFjciI6IjAiLCJjYXBvbGlkc19sYXRlYmluZCI6WyIxMTRkMWU1NC0yMTE1LTRmNDItODVlMy0xMzZjMGFmNjVkY2UiLCIwY2Y0ODUyNS1iMWJhLTQ3M2UtOTAzMy0xYjdlM2NhNDM0NWYiXSwiZGV2aWNlaWQiOiIwNTc5NTQxZC05NTU2LTQ3NDctOTBlNi0zNzNiN2IzYWMzMWQiLCJmYW1pbHlfbmFtZSI6Ik1vcnllIiwiZ2l2ZW5fbmFtZSI6IlZpa2VzaCIsImdyb3VwcyI6WyI2ZjEwMDYwMi1mNGZhLTRkMmEtYTI5OS05YmU2YjExOTk2OGYiLCIyZDI5MWUwZi0yMTg0LTQxZWQtOGNjMS04NDQxYjk4OTA0ZjAiLCIxNzMwOTAxMy01NzYyLTRlYTMtYTQ1OS00MzAwMTU5ODJjYzMiLCJlNTBjM2YyNS1kZDIxLTRjZDQtOWE0OS1lOTM0MDQ0NzUyMDUiLCIyZWJiYTQyNS03OGFlLTQ0MzUtOWIzYy0wZTNiMDk0NDhhMmUiLCJhYmEzNDMyOC1lNTU3LTQ2MzUtYTMwNy1hMDliNjgzYWQ2MTUiLCI5MGJkNTYyOS0xZDE2LTQyZWMtYjgxYy01YmFlNmRlMWMyZWMiLCI3MmMwMzM0MS00MDQ4LTQ1OTAtOTYyMi0wMGQxZmNmZTkzNzEiLCI0YTYyOTY0ZS02Yjc1LTQ2NGYtOTA0Yy1mODAzYWNhMzZmMjMiLCJiYzI1ZmI1MS02MTExLTRiNWMtODUyYS1kNjg0MDRiMTdjZDYiLCIyNTQwZTI1Yy1lOWI4LTRkMGEtOTZjYS0yODdiNTI0NWQ2NjgiLCI3YWM0YzY2Ni1iYzA4LTQ0ODktYjliYy1lN2YxZTQzYTVhNTQiLCJmY2FhYWE3Ni0xODRlLTQzZDEtOGVmOC02ZGY4NjA2ZjEwODgiLCJkMmJhYjc3OC1kM2YyLTQ3ODUtOGZjNy0zNjQwNjMzOTAyZDQiLCI2OGU4ZGU3OC1mYTdjLTRlZTctYjk0My01M2QyNzdiMjIyYjgiLCI0MGI2YTI4MS05MjVmLTQ3N2MtOTM2OC00YmViNTY3ZjA0ZDMiLCI3ZTExYmU4OC0xYjM4LTRhMWYtYjkwMS04YTEyMWJmMzI4N2UiLCJlNGU5ODA4Yy1mY2IzLTRhMDAtYTg4Ni01MTFhOTViNzIzM2QiLCI3NTVmMmU5ZS1kYTk4LTRlMTQtYWQ1My00NzdlZmI3MTZkZGYiLCIxYTFlZDI5Zi1lZDRmLTRkZmMtODViNC0wMTc2NjgyZTRiZTYiLCI3N2ZkOGJhNC0wNjIyLTQ4ZGYtYjE5Mi02M2Q5Mjg0YzJjOTgiLCJjNGEwYzVhNC1kNmQ4LTQwOTAtYjFlZi1kM2NmMWZjZTA1YWUiLCJhMDYyMThhZC1jZjgxLTRjMTYtOTU5Yy0wMTQ4Mzc2YjI5MmYiLCIwMTcwMTNiNS05MDBhLTRiZGItOWEyNS1lOGRhZDkxNDA1MjAiLCI2NDY0YzBiOC0yOTVhLTQxZjQtYjQyZC00ZTM2NWViYTM0NjQiLCI2Mzk4NzdiYy01NmRlLTQ1YTQtYmQyYi1mOWFhZDY0NjQ0NjIiLCJiZjc1MWNjMC1hOWI0LTQxMTEtYmFlMC00NDU2ZTczN2VhYzQiLCJjYzI5OGFjNi1mODhjLTQwMDUtYmRkZC1mMjhlMDY5NGJjYzkiLCJjODhiNTdjNy04MjYyLTQ4ZjktOGQ2Yy1jZWEyZWZjNTI4ZDEiLCI5MWNmZWNkNS1hNTgyLTQ1MTktYjMxYy0yMTZiNDIzNDAzNjUiLCJjNzdlMDdkOS1hZmVjLTQ5MjAtOWQ3Ni00YWFhYzRjNjVjNzAiLCJmOTk0YTRkYy04ZjEyLTRhNGEtOWZmYS0wY2UzYWQyZjZiZmEiLCI3MjBhZWRlNS05MTBjLTQ5ZTQtYTJkZS1mMGZmMTEwNzY0YWIiLCI1NWJiZjVlOC02ZTBiLTRkN2UtYjliYi1kYTJkNjhhMGY2YWQiLCIzZjhjMWFlYS00OThmLTRmZWUtYmNiOC1lYzkxNmMyNzRhZmUiLCI0NWU2ZDNlZS1iZGVmLTQ2YTQtOGRkMi0xMWU1ZDhmY2FhYjgiLCJlNDEzMjVmMS0wN2UxLTQzZGMtODBjMy0wNGI0MDQ1YWIwMTAiLCIzMjNkNjlmMi0zY2NlLTQ5NmEtOTdjNi0wMDBiNmVmNjhjOGUiXSwiaWR0eXAiOiJ1c2VyIiwiaXBhZGRyIjoiMjQuMjM5LjEzMy42NiIsIm5hbWUiOiJWaWtlc2ggTW9yeWUiLCJvaWQiOiI4MmQzOTFjMy04MDcyLTQxNzUtODgyYS04MWJkNTE2NTVlODAiLCJvbnByZW1fc2lkIjoiUy0xLTUtMjEtNjgzMjQwMDIxLTIzNDYwNTczNzItMzk4OTI4MzYyMC00NjY2ODIiLCJwdWlkIjoiMTAwMzIwMDM3QTM4NkE5QSIsInJoIjoiMC5BVUVBQUh1RWZiS2NpMDZmRlB0WTNrdk4za1pJZjNrQXV0ZFB1a1Bhd2ZqMk1CTkJBT2suIiwic2NwIjoidXNlcl9pbXBlcnNvbmF0aW9uIiwic3ViIjoiYWpFTTN2cnU4VUI0MVY5VzFNUDRST0VncDRtZ1d4aldsTnZuNFZvSDFJSSIsInRpZCI6IjdkODQ3YjAwLTljYjItNGU4Yi05ZjE0LWZiNThkZTRiY2RkZSIsInVuaXF1ZV9uYW1lIjoiVmlrZXNoLk1vcnllQGlhZy5jb20uYXUiLCJ1cG4iOiJWaWtlc2guTW9yeWVAaWFnLmNvbS5hdSIsInV0aSI6Ik5LTlphcjVldTBpc2pQQ1ZJSzlrQUEiLCJ2ZXIiOiIxLjAiLCJ3aWRzIjpbImI3OWZiZjRkLTNlZjktNDY4OS04MTQzLTc2YjE5NGU4NTUwOSJdLCJ4bXNfY2FlIjoiMSIsInhtc19jYyI6WyJDUDEiXSwieG1zX2ZpbHRlcl9pbmRleCI6WyI2NSJdLCJ4bXNfaWRyZWwiOiIxIDE0IiwieG1zX3JkIjoiMC40MkxsWUJSaWRBUUEiLCJ4bXNfc3NtIjoiMSIsInhtc190Y2R0IjoxNDAyMDUxMzE2fQ.ZNrdCcLtp2xIpnoGQNsDj4kJdlD2RfN6ghIKG8A4wQDshrTfdZs1pwL3BpElXC8GrWQ6_P2T0dEegzL_wur3FdpU8udoL1YlKJytzFPgMuSf__Sg5zzKJyomiNKDhd-QE4de-WBOJAlvRvImcFNVO9bkKJRC-bEoZsI9QlR2xWTYxENqsu6VMClVVLS3M-R_xi4kJ5ed_kBWWMIezW_dqroO7-P6C8hFCSRFCr3-ZOAfVUngoUOoutNHWXwkPxY65qDGHKqnB4tP2w3Zq2pfQajmxGV1bRLnbCOa48TRk4Xs5hWj8l-PykR6u7EIpe_4JhL6kJKSyHZhR91-cZU2Ag",
#   "expiresOn": "2024-08-17 04:10:37.000000",
#   "expires_on": 1723831837,
#   "subscription": "a7705cbb-6c95-4539-9517-e1af5eb295c2",
#   "tenant": "7d847b00-9cb2-4e8b-9f14-fb58de4bcdde",
#   "tokenType": "Bearer"
# }

In [21]:
import asyncio

async def func():
    print("started.")
    await asyncio.sleep(2)
    print("done.")

await func()

started.
done.

### Other tests

In [12]:
import pandas as pd
n_shots = "/Users/s748779/IAG_test/st/files/train_data_l1l2_aug.csv"
# Load the CSV file into a DataFrame
df = pd.read_csv(n_shots)

In [18]:
for i in df.index:
    print(str(df.loc[i].to_json()), '\n', '\n')

{"opportunity_name":"Vehicle Fulfilment Platform  (Carbar)","problem_statement":"Problem statement*\nWhat is the business\/customer problem we want to solve?\n\nDIA Insurance Supply Chain is considering the transition of Carbar Vehicle Fulfilment Platform (VFP) to help IAG. The tool is a quoting tool that we will use internally to engage with motor dealer networks. \n\nCarbar are wanting to review creating a duplication of the platform for IAG to \u201ctransition\u201d inhouse. \n\nWe require an architectural assessment.","outcome":"Outcomes*\nBased on the business\/ customer problem statement, what are the outcomes we are looking to achieve?\u00a0\n\nTransition the VFP to IAG to so that we can continue to service our customers. The VFP will allow ease of connection when engaging with motor dealerships nationally.","RAID":"Risks \u2013 \nTiming. Pending other activity within the Carbar business, we may time constrained re delivery. \n\nGiven other non-related changes in the CB business, their capacity to support (tech SME) may be constrained. \n\n\nAssumptions \u2013 \nThere isn\u2019t significant system uplift required in order to transition VFP into IAG\u2019s tech stack.\n\nResource and other costs to integrate is not considerable \u2013 cost v benefit will need to be considered.\n\nThere is assess to tech resources available to support the immediate transition (if progressed). ","actual_cost":"M","l1_capabilities":"{'Customer': {'Web': {'level': 1, 'description': 'Allows customers to access insurance services through the web', 'impact': 'Empty'}, 'Mobile': {'level': 1, 'description': 'Allows customers to access insurance services through mobile devices', 'impact': 'Empty'}, 'Assisted': {'level': 1, 'description': 'Provides assistance to customers in accessing insurance services', 'impact': 'Empty'}}, 'Customer Experience & Management': {'Partner Portals & Integration': {'level': 1, 'description': 'Enables integration of partner portals for a seamless customer experience', 'impact': {'description': 'The transition of the VFP to IAG may require updates or integration with existing partner portals to ensure seamless quoting and engagement with motor dealer networks.'}}, 'Broker Portals & Integration': {'level': 1, 'description': 'Enables integration of broker portals for improved customer management', 'impact': 'Empty'}}, 'Policy & Pricing': {'Personal Policy': {'level': 1, 'description': 'Handles insurance policies for individuals', 'impact': 'Empty'}, 'Personal Pricing': {'level': 1, 'description': 'Determines the price of insurance policies for individuals', 'impact': 'Empty'}, 'Personal Underwriting': {'level': 1, 'description': 'Assesses the risk of insuring individuals', 'impact': 'Empty'}, 'Commercial Policy': {'level': 1, 'description': 'Handles insurance policies for businesses', 'impact': 'Empty'}, 'Commercial Pricing': {'level': 1, 'description': 'Determines the price of insurance policies for businesses', 'impact': 'Empty'}, 'Commercial Underwriting': {'level': 1, 'description': 'Assesses the risk of insuring businesses', 'impact': 'Empty'}}, 'Claims, Supply Chain, Comms': {'Claims': {'level': 1, 'description': 'Manages insurance claims from customers', 'impact': 'Empty'}, 'Supply Chain': {'level': 1, 'description': 'Manages the supply chain of insurance products', 'impact': {'description': 'The transition of the VFP to IAG is expected to improve the engagement with motor dealer networks, which is a part of the supply chain for vehicle fulfilment.'}}, 'Communications': {'level': 1, 'description': 'Handles communications with customers and partners', 'impact': 'Empty'}}, 'Digital Operations': {'People & Workplace Experience': {'level': 1, 'description': 'Enhances the digital experience of employees and workplace operations', 'impact': 'Empty'}, 'Finance & Actuarial': {'level': 1, 'description': 'Handles financial and actuarial operations digitally', 'impact': 'Empty'}, 'Risk & Operations': {'level': 1, 'description': 'Manages risk and operations digitally', 'impact': 'Empty'}}, 'Enabling Capabilities': {'Data': {'level': 1, 'description': 'Manages and analyzes data for insurance operations', 'impact': {'description': \"The integration of the VFP into IAG's tech stack will involve data management and analysis, particularly related to the creation and update of quotes and communication logs with motor dealerships.\"}}, 'Security': {'level': 1, 'description': 'Ensures the security and protection of insurance data and systems', 'impact': {'description': 'Transitioning the VFP to IAG will require a security assessment to ensure the protection of data during the integration process and subsequent operations.'}}, 'Infrastructure': {'level': 1, 'description': 'Provides the necessary infrastructure to support insurance operations', 'impact': {'description': \"The architectural assessment will determine the infrastructure requirements for integrating the VFP into IAG's tech stack, including any system uplifts and resource allocations.\"}}}}","l2_capabilities":"{'Claims, Supply Chain, Comms': {'Supply Chain': {'level': 1, 'description': 'Manages the supply chain of insurance products', 'impact': 'The transition of the VFP to IAG will impact the way the supply chain is managed, particularly in how IAG engages with motor dealer networks for quoting purposes.', 'L2 capabilities': [{'Supplier Management': {'level': 2, 'description': 'Manages relationships with suppliers in the insurance supply chain', 'impact': 'The VFP will streamline the engagement process with motor dealer networks, potentially affecting supplier relationship management.'}}, {'Parts & Supplier Sourcing': {'level': 2, 'description': 'Sources and manages parts and suppliers for insurance products', 'impact': 'Empty'}}, {'Claims Fulfilment': {'level': 2, 'description': 'Fulfills insurance claims by coordinating with suppliers', 'impact': 'Empty'}}]}}, 'Enabling Capabilities': {'Data': {'level': 1, 'description': 'Manages and analyzes data for insurance operations', 'impact': 'The integration of VFP will require data warehousing, orchestration, and potentially changes to data governance practices.', 'L2 capabilities': [{'Data Warehousing & Orchestration': {'level': 2, 'description': 'Manages the storage and orchestration of data for insurance operations', 'impact': \"The VFP's data will need to be integrated into IAG's existing data warehousing and orchestration systems.\"}}, {'Analytics & Reporting': {'level': 2, 'description': 'Performs analytics and generates reports for insurance operations', 'impact': 'The VFP may provide new data points for analytics and reporting, enhancing the decision-making process.'}}, {'Archiving': {'level': 2, 'description': 'Manages the archival of data for insurance operations', 'impact': 'Empty'}}, {'Master Data Management': {'level': 2, 'description': 'Manages the master data for insurance operations', 'impact': \"Master data management practices may need to be updated to accommodate the VFP's data structures.\"}}, {'Knowledge Management': {'level': 2, 'description': 'Manages and shares knowledge within the insurance company', 'impact': 'Empty'}}, {'Data Access & Governance': {'level': 2, 'description': 'Manages access to and governance of data for insurance operations', 'impact': \"Data governance policies may need to be reviewed and updated to include the VFP's data and usage.\"}}]}, 'Security': {'level': 1, 'description': 'Ensures the security and protection of insurance data and systems', 'impact': 'The integration of the VFP will necessitate a review of security measures to ensure the protection of data and systems.', 'L2 capabilities': [{'Identity & Access Management': {'level': 2, 'description': 'Manages the identities and access rights of users in the insurance company', 'impact': 'Identity and access management systems may need to be updated to incorporate VFP users and permissions.'}}, {'Certificate Management': {'level': 2, 'description': 'Manages digital certificates used for authentication and encryption', 'impact': 'Empty'}}, {'Protective Services': {'level': 2, 'description': 'Manages security services and measures to protect insurance data and systems', 'impact': \"Protective services will need to ensure that the VFP's integration does not introduce new vulnerabilities.\"}}, {'Threat & Vulnerability Management': {'level': 2, 'description': 'Identifies and manages security threats and vulnerabilities in insurance operations', 'impact': \"Threat and vulnerability management processes may need to be updated to account for the VFP's architecture and potential risks.\"}}]}, 'Infrastructure': {'level': 1, 'description': 'Provides the necessary infrastructure to support insurance operations', 'impact': \"The VFP's transition to IAG will require infrastructure support for hosting, networking, and API management.\", 'L2 capabilities': [{'Networking': {'level': 2, 'description': 'Manages the networking infrastructure for insurance operations', 'impact': 'Empty'}}, {'Storage': {'level': 2, 'description': 'Manages the storage infrastructure for insurance operations', 'impact': \"Additional storage solutions may be required to accommodate the VFP's data.\"}}, {'Compute': {'level': 2, 'description': 'Manages the computing infrastructure for insurance operations', 'impact': \"Compute resources will need to be evaluated and potentially scaled to support the VFP's workload.\"}}, {'API Management': {'level': 2, 'description': 'Manages the APIs used for integration in insurance operations', 'impact': \"API management capabilities will be critical for the integration and ongoing interaction between the VFP and IAG's systems.\"}}]}}}"}


{"opportunity_name":"Add 'Channel' as a mandatory CCM Field","problem_statement":"What is the business\/customer problem we want to solve?\u000b\u000bWhat is happening?\nTo include \u2018Channel\u2019 as a new mandatory field in CCM when capturing or updating a Complaint.\n\nWhy is this happening?\nIAG has a mandatory requirement to capture this information due to the regulatory issues of currently being non-compliant with AFCA.\n\n\nPlease see https:\/\/iag.atlassian.net\/browse\/DDI-1110 for further context & history","outcome":"We are proposing to add Complaints Channel as a field in CCM. IAG has a mandatory requirement to capture this information in the following format:\n1 - Face to face\u000b2 - Phone\u000b3 - E-mail\u000b4 - Web Chat\u000b5 - Online Form\u000b6 - Social Media\u000b7 - Referral from AFCA \u000b8 - Other\u000b9 - Unknown","RAID":"\nFunding pathway needs to be confirmed, will be divisional but need exact costs\n\nMandatory compliance date","actual_cost":"M","l1_capabilities":"{'Customer': {'Web': {'level': 1, 'description': 'Allows customers to access insurance services through the web', 'impact': 'Empty'}, 'Mobile': {'level': 1, 'description': 'Allows customers to access insurance services through mobile devices', 'impact': 'Empty'}, 'Assisted': {'level': 1, 'description': 'Provides assistance to customers in accessing insurance services', 'impact': 'Empty'}}, 'Customer Experience & Management': {'Partner Portals & Integration': {'level': 1, 'description': 'Enables integration of partner portals for a seamless customer experience', 'impact': 'Empty'}, 'Broker Portals & Integration': {'level': 1, 'description': 'Enables integration of broker portals for improved customer management', 'impact': 'Empty'}}, 'Policy & Pricing': {'Personal Policy': {'level': 1, 'description': 'Handles insurance policies for individuals', 'impact': 'Empty'}, 'Personal Pricing': {'level': 1, 'description': 'Determines the price of insurance policies for individuals', 'impact': 'Empty'}, 'Personal Underwriting': {'level': 1, 'description': 'Assesses the risk of insuring individuals', 'impact': 'Empty'}, 'Commercial Policy': {'level': 1, 'description': 'Handles insurance policies for businesses', 'impact': 'Empty'}, 'Commercial Pricing': {'level': 1, 'description': 'Determines the price of insurance policies for businesses', 'impact': 'Empty'}, 'Commercial Underwriting': {'level': 1, 'description': 'Assesses the risk of insuring businesses', 'impact': 'Empty'}}, 'Claims, Supply Chain, Comms': {'Claims': {'level': 1, 'description': 'Manages insurance claims from customers', 'impact': {'description': \"The addition of the 'Channel' field in the CCM will impact the way claims are captured and updated, ensuring that the channel through which the complaint was received is recorded for compliance purposes.\"}}, 'Supply Chain': {'level': 1, 'description': 'Manages the supply chain of insurance products', 'impact': 'Empty'}, 'Communications': {'level': 1, 'description': 'Handles communications with customers and partners', 'impact': 'Empty'}}, 'Digital Operations': {'People & Workplace Experience': {'level': 1, 'description': 'Enhances the digital experience of employees and workplace operations', 'impact': 'Empty'}, 'Finance & Actuarial': {'level': 1, 'description': 'Handles financial and actuarial operations digitally', 'impact': 'Empty'}, 'Risk & Operations': {'level': 1, 'description': 'Manages risk and operations digitally', 'impact': 'Empty'}}, 'Enabling Capabilities': {'Data': {'level': 1, 'description': 'Manages and analyzes data for insurance operations', 'impact': {'description': \"The CCM system will need to be updated to handle the new 'Channel' data field, which will require changes to data capture, storage, and compliance reporting processes.\"}}, 'Security': {'level': 1, 'description': 'Ensures the security and protection of insurance data and systems', 'impact': 'Empty'}, 'Infrastructure': {'level': 1, 'description': 'Provides the necessary infrastructure to support insurance operations', 'impact': 'Empty'}}}","l2_capabilities":"{'Claims, Supply Chain, Comms': {'Claims': {'level': 1, 'description': 'Manages insurance claims from customers', 'L2 capabilities': [{'Claims Management': {'level': 2, 'description': 'Handles the end-to-end management of insurance claims', 'impact': \"The 'Channel' field will need to be added to the claims management system to ensure that complaints are captured with the new mandatory information, affecting data capture and storage.\"}}, {'Fraud Detection': {'level': 2, 'description': 'Identifies and detects fraudulent insurance claims', 'impact': 'Empty'}}, {'Recovery Management': {'level': 2, 'description': 'Manages the recovery process for insurance claims', 'impact': 'Empty'}}]}}, 'Enabling Capabilities': {'Data': {'level': 1, 'description': 'Manages and analyzes data for insurance operations', 'L2 capabilities': [{'Data Warehousing & Orchestration': {'level': 2, 'description': 'Manages the storage and orchestration of data for insurance operations', 'impact': \"The data schema will need to be updated to include the new 'Channel' field, affecting how complaint data is stored and orchestrated.\"}}, {'Analytics & Reporting': {'level': 2, 'description': 'Performs analytics and generates reports for insurance operations', 'impact': \"Reporting tools will need to be updated to account for the new 'Channel' field to ensure compliance reporting includes this new mandatory data.\"}}, {'Archiving': {'level': 2, 'description': 'Manages the archival of data for insurance operations', 'impact': 'Empty'}}, {'Master Data Management': {'level': 2, 'description': 'Manages the master data for insurance operations', 'impact': \"The master data model will need to be updated to include the new 'Channel' field as part of the complaint records.\"}}, {'Knowledge Management': {'level': 2, 'description': 'Manages and shares knowledge within the insurance company', 'impact': 'Empty'}}, {'Data Access & Governance': {'level': 2, 'description': 'Manages access to and governance of data for insurance operations', 'impact': \"Policies and procedures will need to be updated to ensure that the new 'Channel' field is governed appropriately and included in access controls.\"}}]}}}"}



['Problem statement*\nWhat is the business/customer problem we want to solve?\n\nDIA Insurance Supply Chain is considering the transition of Carbar Vehicle Fulfilment Platform (VFP) to help IAG. The tool is a quoting tool that we will use internally to engage with motor dealer networks. \n\nCarbar are wanting to review creating a duplication of the platform for IAG to “transition” inhouse. \n\nWe require an architectural assessment. Outcomes*\nBased on the business/ customer problem statement, what are the outcomes we are looking to achieve?\xa0\n\nTransition the VFP to IAG to so that we can continue to service our customers. The VFP will allow ease of connection when engaging with motor dealerships nationally. Risks – \nTiming. Pending other activity within the Carbar business, we may time constrained re delivery. \n\nGiven other non-related changes in the CB business, their capacity to support (tech SME) may be constrained. \n\n\nAssumptions – \nThere isn’t significant system uplift required in order to transition VFP into IAG’s tech stack.\n\nResource and other costs to integrate is not considerable – cost v benefit will need to be considered.\n\nThere is assess to tech resources available to support the immediate transition (if progressed). ', 'What is the business/customer problem we want to solve?\x0b\x0bWhat is happening?\nTo include ‘Channel’ as a new mandatory field in CCM when capturing or updating a Complaint.\n\nWhy is this happening?\nIAG has a mandatory requirement to capture this information due to the regulatory issues of currently being non-compliant with AFCA.\n\n\nPlease see https://iag.atlassian.net/browse/DDI-1110 for further context & history We are proposing to add Complaints Channel as a field in CCM. IAG has a mandatory requirement to capture this information in the following format:\n1 - Face to face\x0b2 - Phone\x0b3 - E-mail\x0b4 - Web Chat\x0b5 - Online Form\x0b6 - Social Media\x0b7 - Referral from AFCA \x0b8 - Other\x0b9 - Unknown \nFunding pathway needs to be confirmed, will be divisional but need exact costs\n\nMandatory compliance date', 'Currently, our colleagues face the frustration of having to navigate and utilise multiple systems to service their customers. To capture a lead or referral for a customer, they need to use either SCV (old application to be decommissioned as part of our Technology strategy) or the Xcelr8 eForm (depending on the product), to pass this information to the right area of the business to contact the customer.  This initiative will simplify the process for our colleagues by allowing them to remain within one application, Orbit Desktop, to identify and capture such leads or referrals as opposed to having to jump through multiple applications. In February, as part of the SME Micro Program, Leads Management functionality for Business Insurance was brought into Orbit (Phase 1), so where possible we’ll be leveraging and extending this out for CD Leads. This will also be a step to enabling the decommission of SCV/Workbench, as well as the Xcelr8 eForm referral system. Delivery of the leads capability across Motor, Home , and lifestyle products across the NRMA and SGI brands for the assisted channel only. RISKS: \nTechnical resourcing availability to work on the project deliverables concurrently. If resources are not available this will result to further costs/effort as the project timeline will increase due to stop/start activities.\nEDH resourcing have not been involved in the estimates due to other project constraints.\nNon-functional requirements are yet to be defined. Assumption: Phase 1 (SME Leads) non-functional requirements will be similar if not the same for CD leads.\nCONSTRAINTS:\nThere are no testing environments for end to end testing (full journey) – which will need to be factored into the costs and effort.\nDEPENDENCIES:\nCross-functional platforms are to work together to deliver on all agreed business/non-functional requirements.', "Problem statement*\nWhat is the business/customer problem we want to solve?\n\nWithin the context of our strategic goal to enhance customer experience and realize operational efficiencies, we're facing a critical challenge in customer engagement with our digital platforms—Heritage SSC and EP Online Account. \n\nDespite the platforms' capabilities to simplify and speed up various customer interactions, only a mere 3% of customers register for an online account following a policy purchase in Heritage digital. This low adoption rate doesn't just limit our ability to provide a superior and more cost-effective customer experience; it also hampers our competitiveness. \n\nWe understand that customers are seeking convenient, quick, and efficient ways to manage their policies. However, our current onboarding mechanisms are failing to capture customers at pivotal lifecycle events—such as renewals, payments, and claims—resulting in missed opportunities for engagement and value delivery. \n\nThis lack of adoption also forfeits the strategic advantage we could otherwise gain over both direct and adjacent competitors, many of whom are actively investing in simplifying digital self-service adoption. Based on the business/ customer problem statement, what are the outcomes we are looking to achieve?\xa0\n\nIncrease Customer Lifetime Value:\xa0Higher retention and more value per\xa0customer through seamless digital experiences.\xa0More opportunities for upselling and cross-selling\xa0due to higher digital engagement.\xa0\n\nTCE:\xa0Lower operational costs through reduced contacts,\xa0and more optimal customer setup/target profile with e-docs,\xa0marketing consent etc...\xa0\n\nIncreased Digital Adoption: Get more customers to adopt our digital platforms. Higher engagement levels as more\xa0customers use digital platforms, making future digital initiatives easier\xa0to roll out.\n\nCustomer Re-Onboarding: Provides an avenue to reactivate and re-engage the\xa0existing customer base, driving further digital adoption and improving\xa0the customer lifecycle and overall digital experience. List any key risks or dependencies that may prevent outcomes being achieved, constraints that must be met, or assumptions that have been made.\n\nRisks\n\nTechnical & Security Hurdles: The risk that unforeseen technical or security challenges could delay implementation or compromise the system's integrity.\n\nMispositioning of Onboarding: The risk that poor framing of the onboarding and setup process as an additional or separate step could hinder customer adoption and engagement.\n\nIssues\n\nResource Constraints: The challenge of insufficient CLP (Customer Lifecycle Platform) resources impacting timely and quality delivery.\n\nAssumptions\n\nDIA Funding: The assumption that DIA funding will be successful in resolving the CLP resource issue.\n\nMarket Conformity: The assumption that seamless onboarding is a common market practice, thus aligning with customer expectations.\n\nDependencies\n\nCLP Resources: This project is dependent on adequate CLP resources, which is currently being addressed through DIA funding.", 'Problem statement*\nWhat is the business/customer problem we want to solve?\n\nDistribution of policy documents is a mandatory legal activity which is currently delivered through post and email. In FY23, DIA spent over $15M on print and postage. It is an area of opportunity for the following reasons;\x0b\uf0d8 Cost to distribute printed policy documents is\x0bapproximately 40 times more expensive than email\x0b\uf0d8 IAG’s carbon footprint impact\x0b\uf0d8 Cost to implement industry-wide regulatory reforms\x0band remediation (UCT, GICOP, IP, etc) is also an\x0bexpensive affair\x0b\nIf we increase our eDocs consent rate there will be a\x0bdirect savings to DIA’s TCE. It will also enable us to\x0bcreate enhanced digital customer interactions and\x0bunlock value adds.\n\nCurrently both Yes and No options for eDocs consent are blank in Policy Centre. Outcomes*\nBased on the business/ customer problem statement, what are the outcomes we are looking to achieve?\xa0\n\nDuring Policy centre quote flows, when a consultant reaches the eDocs consent question, it will pre-fill the yes box \nNew scripting will prompt the consultant to add value through eDocs (approved scripting to follow) Risks / constraints / dependencies / assumptions / challenges\xa0\nList any key risks or dependencies that may prevent outcomes being achieved, constraints that must be met, or assumptions that have been made.\n\n\uf0d8 Prioritisation against other sectors/portfolios\x0b\uf0d8 Commitment from required\xa0tech and business\x0bteams\n', 'The NRMA would like to change name and price of the current roadside assistance offering in the Motor funnel, as well as add a third product for IAG to sell as part of the Sell RSA offering in the Motor funnel (see additional email attached for details). Provides a convenient experience for customers to be able to easily buy Motor and RSA nan', 'Problem statement*\n\nTraditionally, excess is used as a customer contribution to claims as they occur; it also helps to reduce small claims and provide savings on administration costs. Both Home and Motor excess levels have not been reviewed for several years, which means higher than anticipated volume of low value claims being processed and paid, resulting in claims cost challenges\n\nCurrently, some states have lower default excess compared to major competitors in the market. This impacts our competitive position with lower conversion rate.\xa0\n\nOpportunity to realise benefit margin for East Heritage customers prior to EP migration Outcomes*\nBased on the business/ customer problem statement, what are the outcomes we are looking to achieve?\xa0\n\nLooking to achieve budgeted saving of $30m over 12 months\n\nUplift excess levels for both new business and renewal to make excess more in line with average claim size and keep up with inflation Risks / constraints / dependencies / assumptions / challenges\xa0\nList any key risks or dependencies that may prevent outcomes being achieved, constraints that must be met, or assumptions that have been made.\n\nPotential retention impacts in EP, where West customers see a second excess increase in EP native renewals\n\nEP DIA/IIA/NZ impacts of additional $4000 excess level for home product\n\n‘Lights on’ HUON maintenance, resulting in vulnerabilities in delivering change\n\nOutbound / Customer Comms capacity constraints\xa0\n\nDeployment of change between IAG and RACV comes with inherent tech risks.\xa0\n\nPDS update required for heritage home products, which may not have the capacity.', 'IAG is missing out on sales opportunities to reach SME customers by not being in all the places that they are. All sales for SME direct products are via IAG channels, there is no way for partners to sell insurance on our behalf by utilising aspects of our own technology. \n\nWe want to be able to offer SME insurance to a wide range of SME customers in the way and situation that suits them and their business.  Creating the links and information required to enable, external parties to connect with API’s allowing them to quote and sell (and eventually service), SME insurance products. \n\nBe able to offer API connections to compatible businesses, who share the IAG values and customer outlook.  Ensuring that work doesn’t have to be done multiple times as Commercial Enterprise Platform comes closer.\n\nConfirming that necessary documentation is created and shared appropriately. This needs to be kept up to date so as to allow for additional links to be established (subject to confirmation of bandwidth etc.).\n\nDetails about data gathering / sharing / storing will need to be covered. Including details of who owns the customer details and journey (how much is controlled by IAG). \nIncludes details of Cloud Adoption Framework (CAF) and security architecture.\n', '1. We are limited in our ability to track and understand customer behaviour in the Digital flows because\nWe are unable see what customers do and what errors they receive due to their behaviour in digital\nWe cannot see where customers focus on a page due to a lack of heat-mapping\n\n2. We have to manually audit our websites to understand whether our items such tags and cookies are working correctly. This means we miss items which can negatively impact customers and also our ability to track customer behaviour. 1. Refresh the discovery work done 1 year ago and decide on appropriate to tools / vendors so:\nWe can view recordings of individual sessions so we can track root cause of issues\nWe can understand the hotspots on pages where customers are hovering\nWe can automatically monitor analytics implementation in our website and identify issues\n\n2. Decide on funding pathway for tools. Implementation needs to be prior to NRMA NSW EP migration to allow time to baseline data and for analysis and fixing of issues\nPrivacy / security issues with session recording\nHighly likely we’ll need to onboard new third-party cloud-based vendors', "For Consumers:\nThere is a lack of quality publicly available natural peril data for homebuyers, making it difficult for them to make informed decisions about the properties they're considering purchasing. This lack of information can lead to costly surprises for homebuyers, who may not be aware of the potential risks associated with a particular property until it is too late, including home insurance premiums.\n\nFor Partners:\nOur strategic banking partners lack quality natural peril risk data that will help them to make improved lending decisions & help their customers to factor in property location risk & home insurance affordability.\n\nBanks' increasing exposure to climate risks raises the need for accurate risk analysis.\nLenders have low visibility of a home’s risk during the loan application process.\nLenders have an increasing need to identify and manage risk in their home loan portfolios. For a consumer audience considering a new home, the Home Risk Index will provide quality and easy to understand natural peril risk insights for a given location. Embedding this data earlier into the homebuying journey will raise our brand awareness and make insurance affordability more of a consideration than our research suggests it is today.\n\nFor our banking partners, providing peril data to assist with their lending decisioning & mortgage portfolio analysis will strengthen our strategic relationships and provide a value-add for new partnerships.  Peril Data Licensing:\nThe AAL/100k modelling that the Home Risk Index derives its data from is sourced from many 3rd party data sources – a mix of professional peril data companies, local councils, industry data pools. We are currently working through a risk assessment of licensing conditions to use said data sources for Home Risk Index.\n\nEmbedded Experience Layer:\nTo productionise the Home Risk Index API for intended use cases – exposing data externally – it is dependent on the Experience Layer to provide requisite security, contracts & integration."]

/var/folders/kn/1r34002j2x594690tjs2ly000000gp/T/ipykernel_17878/4099726848.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2.rename(columns = {"Tshrt_size" : "actual_cost",
/var/folders/kn/1r34002j2x594690tjs2ly000000gp/T/ipykernel_17878/4099726848.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2["l1_capabilities"] = None

,opportunity_name,problem_statement,outcome,RAID,actual_cost,combined,l1_capabilities,l2_capabilities
0,Vehicle Fulfilment Platform (Carbar),Problem statement*\nWhat is the business/custo...,Outcomes*\nBased on the business/ customer pro...,Risks – \nTiming. Pending other activity withi...,M,Problem statement*\nWhat is the business/custo...,None,None
1,Add 'Channel' as a mandatory CCM Field,What is the business/customer problem we want ...,We are proposing to add Complaints Channel as ...,"\nFunding pathway needs to be confirmed, will ...",M,What is the business/customer problem we want ...,None,None
2,Consumer Leads in Orbit (Phase 2 + Lifestyle),"Currently, our colleagues face the frustration...","Delivery of the leads capability across Motor,...",RISKS: \nTechnical resourcing availability to ...,M,"Currently, our colleagues face the frustration...",None,None
3,Digital out of the box,Problem statement*\nWhat is the business/custo...,Based on the business/ customer problem statem...,List any key risks or dependencies that may pr...,M,Problem statement*\nWhat is the business/custo...,None,None
4,eDocs Uplift: EP PC Preselected Yes to eDocs i...,Problem statement*\nWhat is the business/custo...,Outcomes*\nBased on the business/ customer pro...,Risks / constraints / dependencies / assumptio...,XS,Problem statement*\nWhat is the business/custo...,None,None

In [62]:
len(combined_list)

10

In [ ]:
pt = pt.pt
for i, row in df2.iterrows():
    inp_l1, inp_l2 = ut.get_reall_from_input_gpt(row["combined"], pt)
    row["l1_capabilities"] = inp_l1
    row["l2_capabilities"] = inp_l2

df2.to_csv("train_data_l1l2_aug.csv", index=False)

### Working utils code functions

In [1]:
from time import time
from langchain.prompts import PromptTemplate
import json
import os

from typing import Dict

from azure.identity import DefaultAzureCredential, get_bearer_token_provider
from azure.identity import AzureDeveloperCliCredential
from azure.core.exceptions import ClientAuthenticationError
from azure.core.credentials import AccessToken

from langchain_community.callbacks import get_openai_callback
from langchain_openai import AzureChatOpenAI
from pydantic import HttpUrl
from pydantic_settings import BaseSettings, SettingsConfigDict

# ============= models ========================

class AzureDeploymentConfig(BaseSettings):
    model_config = SettingsConfigDict(env_prefix='vk_') #SettingsConfigDict(env_prefix='ka_')  # such that you can overwrite these values with environment                                                         
    azure_endpoint: HttpUrl = "https://payg-kar-d-r1-oai.openai.azure.com"
    deployment_name: str = "default-gpt4-turbo"
    openai_api_version: str = "2024-02-01"
    token_scope: str = "https://cognitiveservices.azure.com/.default"


# =============== model initialisation with azure dev backend refresh token ===========

def get_token():
    config = AzureDeploymentConfig()
    credential = DefaultAzureCredential(exclude_interactive_browser_credential=False)
    token = credential.get_token(config.token_scope)
    return token
    
# Function to refresh the token if needed
def refresh_token_if_needed(token: AccessToken):
    if token.expires_on - time() < 300:  # Refresh if less than 5 minutes left
        token = get_token()
    return token.token


def initialize_gpt_models(temperature: float = 0.0, top_p: float = 0.5):
    config = AzureDeploymentConfig()
    token = get_token()
    # token_provider = get_bearer_token_provider(
    #     DefaultAzureCredential(exclude_interactive_browser_credential=False),config.token_scope
    # )
    main_model = AzureChatOpenAI(
        azure_endpoint=str(config.azure_endpoint),
        deployment_name=config.deployment_name,
        openai_api_version=config.openai_api_version,
        # azure_ad_token_provider=token_provider,
        azure_ad_token_provider=lambda: refresh_token_if_needed(token),
        temperature=temperature,
        top_p=top_p
    )

    json_model = AzureChatOpenAI(
        azure_endpoint=str(config.azure_endpoint),
        deployment_name=config.deployment_name,
        openai_api_version=config.openai_api_version,
        # azure_ad_token_provider=token_provider,
        azure_ad_token_provider=lambda: refresh_token_if_needed(token),
        temperature=temperature,
        top_p=top_p,
        model_kwargs={"response_format": {"type": "json_object"}}
    )
    return main_model, json_model

# =========================================================


# modify validate_json_model 
def validate_json_gpt_model(prompt, json_model):
    if not is_json_gpt(prompt):
        response = json_model.invoke([ ("system",
                                        "Validate the given json string and correct it wherever required to convert it into a valid JSON structure."),
                                        ("human", prompt),
                                     ])
        resp = response.content
        # validated_json_dict = json.loads(resp)
        return resp

    return prompt
    
def is_json_gpt(response_output):
    try:
        json.loads(response_output)
        return True
    except json.JSONDecodeError:
        print("GPT main_model failed to provide valid json.")
        return False

# ============ model outputs ===================

# modify get_gemini_response
def get_gpt_model_response(prompt, main_model, json_model):
    raw = main_model.invoke(prompt)
    raw_text = raw.content
    raw_text_validated = validate_json_gpt_model(raw_text, json_model)
    try:
        raw_json = json.loads(raw_text_validated)
        return raw_json
    except Exception as e:
        print("The json_model failed to return valid json for ", raw_text[:100], ". . .")
        return raw_text

/Users/s748779/IAG_test/test1/lib/python3.9/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(

In [2]:
m , j = initialize_gpt_models()

In [3]:
m

AzureChatOpenAI(client=<openai.resources.chat.completions.Completions object at 0x139b9b7f0>, async_client=<openai.resources.chat.completions.AsyncCompletions object at 0x139bac1c0>, temperature=0.0, openai_proxy='', top_p=0.5, azure_endpoint='https://payg-kar-d-r1-oai.openai.azure.com/', deployment_name='default-gpt4-turbo', openai_api_version='2024-02-01', azure_ad_token_provider=<function initialize_gpt_models.<locals>.<lambda> at 0x139b6a310>, openai_api_type='azure')

In [4]:
j

AzureChatOpenAI(client=<openai.resources.chat.completions.Completions object at 0x139bb5bb0>, async_client=<openai.resources.chat.completions.AsyncCompletions object at 0x139bc0580>, temperature=0.0, model_kwargs={'response_format': {'type': 'json_object'}}, openai_proxy='', top_p=0.5, azure_endpoint='https://payg-kar-d-r1-oai.openai.azure.com/', deployment_name='default-gpt4-turbo', openai_api_version='2024-02-01', azure_ad_token_provider=<function initialize_gpt_models.<locals>.<lambda> at 0x139b6a550>, openai_api_type='azure')

### assistant

In [2]:

!pip install azure-identity

Collecting azure-identity
  Downloading azure_identity-1.17.1-py3-none-any.whl (173 kB)
     |████████████████████████████████| 173 kB 71 kB/s eta 0:00:01
Collecting azure-core>=1.23.0
  Downloading azure_core-1.30.2-py3-none-any.whl (194 kB)
     |████████████████████████████████| 194 kB 51 kB/s eta 0:00:01
Requirement already satisfied: typing-extensions>=4.0.0 in ./local_oai/lib/python3.9/site-packages (from azure-identity) (4.12.2)
Collecting msal>=1.24.0
  Downloading msal-1.29.0-py3-none-any.whl (110 kB)
     |████████████████████████████████| 110 kB 74 kB/s eta 0:00:01
Collecting cryptography>=2.5
  Downloading cryptography-42.0.8-cp39-abi3-macosx_10_12_universal2.whl (5.9 MB)
     |████████████████████████████████| 5.9 MB 50 kB/s eta 0:00:012
Collecting msal-extensions>=0.3.0
  Downloading msal_extensions-1.2.0-py3-none-any.whl (19 kB)
Requirement already satisfied: six>=1.11.0 in ./local_oai/lib/python3.9/site-packages (from azure-core>=1.23.0->azure-identity) (1.16.0)
Requirement already satisfied: requests>=2.21.0 in ./local_oai/lib/python3.9/site-packages (from azure-core>=1.23.0->azure-identity) (2.32.3)
Requirement already satisfied: cffi>=1.12 in ./local_oai/lib/python3.9/site-packages (from cryptography>=2.5->azure-identity) (1.16.0)
Requirement already satisfied: pycparser in ./local_oai/lib/python3.9/site-packages (from cffi>=1.12->cryptography>=2.5->azure-identity) (2.22)
Collecting PyJWT[crypto]<3,>=1.0.0
  Downloading PyJWT-2.8.0-py3-none-any.whl (22 kB)
Collecting portalocker<3,>=1.4
  Downloading portalocker-2.10.0-py3-none-any.whl (18 kB)
Requirement already satisfied: idna<4,>=2.5 in ./local_oai/lib/python3.9/site-packages (from requests>=2.21.0->azure-core>=1.23.0->azure-identity) (3.7)
Requirement already satisfied: charset-normalizer<4,>=2 in ./local_oai/lib/python3.9/site-packages (from requests>=2.21.0->azure-core>=1.23.0->azure-identity) (3.3.2)
Requirement already satisfied: urllib3<3,>=1.21.1 in ./local_oai/lib/python3.9/site-packages (from requests>=2.21.0->azure-core>=1.23.0->azure-identity) (2.2.2)
Requirement already satisfied: certifi>=2017.4.17 in ./local_oai/lib/python3.9/site-packages (from requests>=2.21.0->azure-core>=1.23.0->azure-identity) (2024.7.4)
Installing collected packages: PyJWT, cryptography, portalocker, msal, msal-extensions, azure-core, azure-identity
Successfully installed PyJWT-2.8.0 azure-core-1.30.2 azure-identity-1.17.1 cryptography-42.0.8 msal-1.29.0 msal-extensions-1.2.0 portalocker-2.10.0
WARNING: You are using pip version 21.2.4; however, version 24.1.1 is available.
You should consider upgrading via the '/Users/s748779/IAG_test/openai_local/local_oai/bin/python3 -m pip install --upgrade pip' command.

In [3]:

!pip install pydantic pydantic-settings

Collecting pydantic
  Downloading pydantic-2.8.2-py3-none-any.whl (423 kB)
     |████████████████████████████████| 423 kB 102 kB/s eta 0:00:01
Collecting pydantic-settings
  Downloading pydantic_settings-2.3.4-py3-none-any.whl (22 kB)
Collecting annotated-types>=0.4.0
  Using cached annotated_types-0.7.0-py3-none-any.whl (13 kB)
Requirement already satisfied: typing-extensions>=4.6.1 in ./local_oai/lib/python3.9/site-packages (from pydantic) (4.12.2)
Collecting pydantic-core==2.20.1
  Downloading pydantic_core-2.20.1-cp39-cp39-macosx_11_0_arm64.whl (1.7 MB)
     |████████████████████████████████| 1.7 MB 26 kB/s eta 0:00:013
Collecting python-dotenv>=0.21.0
  Using cached python_dotenv-1.0.1-py3-none-any.whl (19 kB)
Installing collected packages: pydantic-core, annotated-types, python-dotenv, pydantic, pydantic-settings
Successfully installed annotated-types-0.7.0 pydantic-2.8.2 pydantic-core-2.20.1 pydantic-settings-2.3.4 python-dotenv-1.0.1
WARNING: You are using pip version 21.2.4; however, version 24.1.1 is available.
You should consider upgrading via the '/Users/s748779/IAG_test/openai_local/local_oai/bin/python3 -m pip install --upgrade pip' command.

In [4]:
!pip install langchain langchain-community

Collecting langchain
  Downloading langchain-0.2.6-py3-none-any.whl (975 kB)
     |████████████████████████████████| 975 kB 40 kB/s eta 0:00:013
Collecting langchain-community
  Downloading langchain_community-0.2.6-py3-none-any.whl (2.2 MB)
     |████████████████████████████████| 2.2 MB 65 kB/s eta 0:00:011
Collecting langchain-core<0.3.0,>=0.2.10
  Downloading langchain_core-0.2.11-py3-none-any.whl (337 kB)
     |████████████████████████████████| 337 kB 79 kB/s eta 0:00:01
Requirement already satisfied: PyYAML>=5.3 in ./local_oai/lib/python3.9/site-packages (from langchain) (6.0.1)
Collecting langchain-text-splitters<0.3.0,>=0.2.0
  Downloading langchain_text_splitters-0.2.2-py3-none-any.whl (25 kB)
Requirement already satisfied: pydantic<3,>=1 in ./local_oai/lib/python3.9/site-packages (from langchain) (2.8.2)
Collecting async-timeout<5.0.0,>=4.0.0
  Using cached async_timeout-4.0.3-py3-none-any.whl (5.7 kB)
Collecting tenacity!=8.4.0,<9.0.0,>=8.1.0
  Downloading tenacity-8.5.0-py3-none-any.whl (28 kB)
Collecting SQLAlchemy<3,>=1.4
  Downloading SQLAlchemy-2.0.31-cp39-cp39-macosx_11_0_arm64.whl (2.1 MB)
     |████████████████████████████████| 2.1 MB 206 kB/s eta 0:00:01
Collecting langsmith<0.2.0,>=0.1.17
  Downloading langsmith-0.1.83-py3-none-any.whl (127 kB)
     |████████████████████████████████| 127 kB 44 kB/s eta 0:00:01
Collecting numpy<2,>=1
  Using cached numpy-1.26.4-cp39-cp39-macosx_11_0_arm64.whl (14.0 MB)
Collecting aiohttp<4.0.0,>=3.8.3
  Using cached aiohttp-3.9.5-cp39-cp39-macosx_11_0_arm64.whl (390 kB)
Requirement already satisfied: requests<3,>=2 in ./local_oai/lib/python3.9/site-packages (from langchain) (2.32.3)
Collecting dataclasses-json<0.7,>=0.5.7
  Downloading dataclasses_json-0.6.7-py3-none-any.whl (28 kB)
Requirement already satisfied: attrs>=17.3.0 in ./local_oai/lib/python3.9/site-packages (from aiohttp<4.0.0,>=3.8.3->langchain) (23.2.0)
Collecting multidict<7.0,>=4.5
  Using cached multidict-6.0.5-cp39-cp39-macosx_11_0_arm64.whl (30 kB)
Collecting yarl<2.0,>=1.0
  Using cached yarl-1.9.4-cp39-cp39-macosx_11_0_arm64.whl (81 kB)
Collecting frozenlist>=1.1.1
  Using cached frozenlist-1.4.1-cp39-cp39-macosx_11_0_arm64.whl (53 kB)
Collecting aiosignal>=1.1.2
  Using cached aiosignal-1.3.1-py3-none-any.whl (7.6 kB)
Collecting marshmallow<4.0.0,>=3.18.0
  Downloading marshmallow-3.21.3-py3-none-any.whl (49 kB)
     |████████████████████████████████| 49 kB 112 kB/s ta 0:00:01
Collecting typing-inspect<1,>=0.4.0
  Using cached typing_inspect-0.9.0-py3-none-any.whl (8.8 kB)
Collecting jsonpatch<2.0,>=1.33
  Using cached jsonpatch-1.33-py2.py3-none-any.whl (12 kB)
Requirement already satisfied: packaging<25,>=23.2 in ./local_oai/lib/python3.9/site-packages (from langchain-core<0.3.0,>=0.2.10->langchain) (24.1)
Requirement already satisfied: jsonpointer>=1.9 in ./local_oai/lib/python3.9/site-packages (from jsonpatch<2.0,>=1.33->langchain-core<0.3.0,>=0.2.10->langchain) (3.0.0)
Collecting orjson<4.0.0,>=3.9.14
  Downloading orjson-3.10.6-cp39-cp39-macosx_10_15_x86_64.macosx_11_0_arm64.macosx_10_15_universal2.whl (250 kB)
     |████████████████████████████████| 250 kB 99 kB/s eta 0:00:011
Requirement already satisfied: pydantic-core==2.20.1 in ./local_oai/lib/python3.9/site-packages (from pydantic<3,>=1->langchain) (2.20.1)
Requirement already satisfied: annotated-types>=0.4.0 in ./local_oai/lib/python3.9/site-packages (from pydantic<3,>=1->langchain) (0.7.0)
Requirement already satisfied: typing-extensions>=4.6.1 in ./local_oai/lib/python3.9/site-packages (from pydantic<3,>=1->langchain) (4.12.2)
Requirement already satisfied: charset-normalizer<4,>=2 in ./local_oai/lib/python3.9/site-packages (from requests<3,>=2->langchain) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in ./local_oai/lib/python3.9/site-packages (from requests<3,>=2->langchain) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in ./local_oai/lib/python3.9/site-packages (from requests<3,>=2->langchain) (2.2.2)
Requirement already satisfied: certifi>=2017.4.17 in ./local_oai/lib/python3.9/site-packages (from requests<3,>=2->langchain) (2024.7.4)
Collecting mypy-extensions>=0.3.0
  Using cached mypy_extensions-1.0.0-py3-none-any.whl (4.7 kB)
Installing collected packages: orjson, tenacity, multidict, langsmith, jsonpatch, frozenlist, yarl, mypy-extensions, langchain-core, async-timeout, aiosignal, typing-inspect, SQLAlchemy, numpy, marshmallow, langchain-text-splitters, aiohttp, langchain, dataclasses-json, langchain-community
Successfully installed SQLAlchemy-2.0.31 aiohttp-3.9.5 aiosignal-1.3.1 async-timeout-4.0.3 dataclasses-json-0.6.7 frozenlist-1.4.1 jsonpatch-1.33 langchain-0.2.6 langchain-community-0.2.6 langchain-core-0.2.11 langchain-text-splitters-0.2.2 langsmith-0.1.83 marshmallow-3.21.3 multidict-6.0.5 mypy-extensions-1.0.0 numpy-1.26.4 orjson-3.10.6 tenacity-8.5.0 typing-inspect-0.9.0 yarl-1.9.4
WARNING: You are using pip version 21.2.4; however, version 24.1.1 is available.
You should consider upgrading via the '/Users/s748779/IAG_test/openai_local/local_oai/bin/python3 -m pip install --upgrade pip' command.

In [8]:

!pip install langchain-openai

Collecting langchain-openai
  Downloading langchain_openai-0.1.14-py3-none-any.whl (45 kB)
     |████████████████████████████████| 45 kB 1.8 MB/s eta 0:00:01
Collecting openai<2.0.0,>=1.32.0
  Downloading openai-1.35.10-py3-none-any.whl (328 kB)
     |████████████████████████████████| 328 kB 2.0 MB/s eta 0:00:01
Requirement already satisfied: langchain-core<0.3,>=0.2.2 in ./local_oai/lib/python3.9/site-packages (from langchain-openai) (0.2.11)
Collecting tiktoken<1,>=0.7
  Using cached tiktoken-0.7.0-cp39-cp39-macosx_11_0_arm64.whl (907 kB)
Requirement already satisfied: tenacity!=8.4.0,<9.0.0,>=8.1.0 in ./local_oai/lib/python3.9/site-packages (from langchain-core<0.3,>=0.2.2->langchain-openai) (8.5.0)
Requirement already satisfied: jsonpatch<2.0,>=1.33 in ./local_oai/lib/python3.9/site-packages (from langchain-core<0.3,>=0.2.2->langchain-openai) (1.33)
Requirement already satisfied: langsmith<0.2.0,>=0.1.75 in ./local_oai/lib/python3.9/site-packages (from langchain-core<0.3,>=0.2.2->langchain-openai) (0.1.83)
Requirement already satisfied: packaging<25,>=23.2 in ./local_oai/lib/python3.9/site-packages (from langchain-core<0.3,>=0.2.2->langchain-openai) (24.1)
Requirement already satisfied: PyYAML>=5.3 in ./local_oai/lib/python3.9/site-packages (from langchain-core<0.3,>=0.2.2->langchain-openai) (6.0.1)
Requirement already satisfied: pydantic<3,>=1 in ./local_oai/lib/python3.9/site-packages (from langchain-core<0.3,>=0.2.2->langchain-openai) (2.8.2)
Requirement already satisfied: jsonpointer>=1.9 in ./local_oai/lib/python3.9/site-packages (from jsonpatch<2.0,>=1.33->langchain-core<0.3,>=0.2.2->langchain-openai) (3.0.0)
Requirement already satisfied: orjson<4.0.0,>=3.9.14 in ./local_oai/lib/python3.9/site-packages (from langsmith<0.2.0,>=0.1.75->langchain-core<0.3,>=0.2.2->langchain-openai) (3.10.6)
Requirement already satisfied: requests<3,>=2 in ./local_oai/lib/python3.9/site-packages (from langsmith<0.2.0,>=0.1.75->langchain-core<0.3,>=0.2.2->langchain-openai) (2.32.3)
Requirement already satisfied: typing-extensions<5,>=4.7 in ./local_oai/lib/python3.9/site-packages (from openai<2.0.0,>=1.32.0->langchain-openai) (4.12.2)
Requirement already satisfied: sniffio in ./local_oai/lib/python3.9/site-packages (from openai<2.0.0,>=1.32.0->langchain-openai) (1.3.1)
Requirement already satisfied: httpx<1,>=0.23.0 in ./local_oai/lib/python3.9/site-packages (from openai<2.0.0,>=1.32.0->langchain-openai) (0.27.0)
Collecting distro<2,>=1.7.0
  Using cached distro-1.9.0-py3-none-any.whl (20 kB)
Collecting tqdm>4
  Using cached tqdm-4.66.4-py3-none-any.whl (78 kB)
Requirement already satisfied: anyio<5,>=3.5.0 in ./local_oai/lib/python3.9/site-packages (from openai<2.0.0,>=1.32.0->langchain-openai) (4.4.0)
Requirement already satisfied: exceptiongroup>=1.0.2 in ./local_oai/lib/python3.9/site-packages (from anyio<5,>=3.5.0->openai<2.0.0,>=1.32.0->langchain-openai) (1.2.1)
Requirement already satisfied: idna>=2.8 in ./local_oai/lib/python3.9/site-packages (from anyio<5,>=3.5.0->openai<2.0.0,>=1.32.0->langchain-openai) (3.7)
Requirement already satisfied: certifi in ./local_oai/lib/python3.9/site-packages (from httpx<1,>=0.23.0->openai<2.0.0,>=1.32.0->langchain-openai) (2024.7.4)
Requirement already satisfied: httpcore==1.* in ./local_oai/lib/python3.9/site-packages (from httpx<1,>=0.23.0->openai<2.0.0,>=1.32.0->langchain-openai) (1.0.5)
Requirement already satisfied: h11<0.15,>=0.13 in ./local_oai/lib/python3.9/site-packages (from httpcore==1.*->httpx<1,>=0.23.0->openai<2.0.0,>=1.32.0->langchain-openai) (0.14.0)
Requirement already satisfied: annotated-types>=0.4.0 in ./local_oai/lib/python3.9/site-packages (from pydantic<3,>=1->langchain-core<0.3,>=0.2.2->langchain-openai) (0.7.0)
Requirement already satisfied: pydantic-core==2.20.1 in ./local_oai/lib/python3.9/site-packages (from pydantic<3,>=1->langchain-core<0.3,>=0.2.2->langchain-openai) (2.20.1)
Requirement already satisfied: urllib3<3,>=1.21.1 in ./local_oai/lib/python3.9/site-packages (from requests<3,>=2->langsmith<0.2.0,>=0.1.75->langchain-core<0.3,>=0.2.2->langchain-openai) (2.2.2)
Requirement already satisfied: charset-normalizer<4,>=2 in ./local_oai/lib/python3.9/site-packages (from requests<3,>=2->langsmith<0.2.0,>=0.1.75->langchain-core<0.3,>=0.2.2->langchain-openai) (3.3.2)
Collecting regex>=2022.1.18
  Using cached regex-2024.5.15-cp39-cp39-macosx_11_0_arm64.whl (278 kB)
Installing collected packages: tqdm, regex, distro, tiktoken, openai, langchain-openai
Successfully installed distro-1.9.0 langchain-openai-0.1.14 openai-1.35.10 regex-2024.5.15 tiktoken-0.7.0 tqdm-4.66.4
WARNING: You are using pip version 21.2.4; however, version 24.1.1 is available.
You should consider upgrading via the '/Users/s748779/IAG_test/openai_local/local_oai/bin/python3 -m pip install --upgrade pip' command.

In [18]:
p1 = """
Convert the following code into a perfect OOPs code, following separation of concerns, the right classes, methods, attributes and approach.
Suggest if required to add custom exception classes, data models and any other parts that need to be added to this code to make it OOPs oriented. 

here's the code : 

from typing import Dict
from azure.identity import DefaultAzureCredential, get_bearer_token_provider
from langchain_community.callbacks import get_openai_callback
from langchain_openai import AzureChatOpenAI
from pydantic import HttpUrl
from pydantic_settings import BaseSettings, SettingsConfigDict


class AzureDeploymentConfig(BaseSettings):
    model_config = SettingsConfigDict(env_prefix='vk_') #SettingsConfigDict(env_prefix='ka_')  # such that you can overwrite these values with environment 
                                                         # variables. E.g.: KA_AZURE_ENDPOINT=http://some.where will
                                                         # overwrite the azure_endpoint value below.
    azure_endpoint: HttpUrl = "https://payg-kar-d-r1-oai.openai.azure.com"
    deployment_name: str = "default-gpt4-turbo"
    openai_api_version: str = "2024-02-01"
    token_scope: str = "https://cognitiveservices.azure.com/.default"



def get_azure_openai(temperature: float = 0.0, top_p: float = 0.5):
    config = AzureDeploymentConfig()
    token_provider = get_bearer_token_provider(
        DefaultAzureCredential(exclude_interactive_browser_credential=False),config.token_scope
    )
    model = AzureChatOpenAI(
        azure_endpoint=str(config.azure_endpoint),
        deployment_name=config.deployment_name,
        openai_api_version=config.openai_api_version,
        azure_ad_token_provider=token_provider,
        temperature=temperature,
        model_kwargs={"top_p": top_p}
    )
    return model

"""

In [19]:
model = get_azure_openai(temperature=1.0)
with get_openai_callback() as cb:
    print(model.invoke(p1).content)
    print(f"Total Tokens: {cb.total_tokens}")

To convert the provided code into a more object-oriented design, we'll need to create a few classes that encapsulate different concerns. Here's a refactored version of the code with added classes and methods that adhere to OOP principles:

```python
from typing import Dict
from azure.identity import DefaultAzureCredential
from langchain_community.callbacks import get_openai_callback
from langchain_openai import AzureChatOpenAI
from pydantic import HttpUrl, BaseModel
from pydantic.env_settings import BaseSettings

# Custom exception classes
class AzureDeploymentError(Exception):
    pass

# Data models
class AzureDeploymentConfig(BaseSettings):
    azure_endpoint: HttpUrl = "https://payg-kar-d-r1-oai.openai.azure.com"
    deployment_name: str = "default-gpt4-turbo"
    openai_api_version: str = "2024-02-01"
    token_scope: str = "https://cognitiveservices.azure.com/.default"

    class Config:
        env_prefix = 'vk_'

# Azure OpenAI Service class
class AzureOpenAIService:
    def __init__(self, config: AzureDeploymentConfig):
        self.config = config
        self.model = None

    def get_token_provider(self):
        try:
            return DefaultAzureCredential(exclude_interactive_browser_credential=False)
        except Exception as e:
            raise AzureDeploymentError(f"Error obtaining token provider: {e}")

    def initialize_model(self, temperature: float, top_p: float):
        token_provider = self.get_token_provider()
        self.model = AzureChatOpenAI(
            azure_endpoint=str(self.config.azure_endpoint),
            deployment_name=self.config.deployment_name,
            openai_api_version=self.config.openai_api_version,
            azure_ad_token_provider=token_provider,
            temperature=temperature,
            model_kwargs={"top_p": top_p}
        )

    def get_model(self, temperature: float = 0.0, top_p: float = 0.5):
        if self.model is None:
            self.initialize_model(temperature, top_p)
        return self.model

# Usage
def main():
    config = AzureDeploymentConfig()
    azure_service = AzureOpenAIService(config)
    model = azure_service.get_model(temperature=0.0, top_p=0.5)
    # Use the model for whatever purpose needed

if __name__ == "__main__":
    main()
```

Explanation of changes:

1. `AzureDeploymentConfig` is now a subclass of `BaseSettings` from `pydantic`, which allows for easy environment variable overrides with the `env_prefix` attribute set in the nested `Config` class.

2. `AzureDeploymentError` is a custom exception class for handling errors related to Azure deployment.

3. `AzureOpenAIService` is a new class that encapsulates the logic for obtaining a token provider and initializing the Azure Chat OpenAI model. It separates the concerns of configuration and service initialization.

4. The `get_token_provider` method handles the creation of the token provider and raises a custom exception if something goes wrong.

5. The `initialize_model` method initializes the Azure Chat OpenAI model with the given parameters.

6. The `get_model` method returns the initialized model or calls `initialize_model` if the model has not been initialized yet.

7. The `main` function demonstrates how to use the `AzureOpenAIService` class to obtain a model.

This refactoring follows the principles of object-oriented programming by encapsulating related properties and behaviors within classes and separating concerns into different classes and methods. It also adds custom exception handling for better error management.
Total Tokens: 1153

In [1]:
from typing import Dict
from azure.identity import DefaultAzureCredential
from langchain_community.callbacks import get_openai_callback
from langchain_openai import AzureChatOpenAI
from pydantic import HttpUrl, BaseModel
from pydantic.env_settings import BaseSettings

# Custom exception classes
class AzureDeploymentError(Exception):
    pass

# Data models
class AzureDeploymentConfig(BaseSettings):
    azure_endpoint: HttpUrl = "https://payg-kar-d-r1-oai.openai.azure.com"
    deployment_name: str = "default-gpt4-turbo"
    openai_api_version: str = "2024-02-01"
    token_scope: str = "https://cognitiveservices.azure.com/.default"

    class Config:
        env_prefix = 'vk_'

# Azure OpenAI Service class
class AzureOpenAIService:
    def __init__(self, config: AzureDeploymentConfig):
        self.config = config
        self.model = None

    def get_token_provider(self):
        try:
            return DefaultAzureCredential(exclude_interactive_browser_credential=False)
        except Exception as e:
            raise AzureDeploymentError(f"Error obtaining token provider: {e}")

    def initialize_model(self, temperature: float, top_p: float):
        token_provider = self.get_token_provider()
        self.model = AzureChatOpenAI(
            azure_endpoint=str(self.config.azure_endpoint),
            deployment_name=self.config.deployment_name,
            openai_api_version=self.config.openai_api_version,
            azure_ad_token_provider=token_provider,
            temperature=temperature,
            model_kwargs={"top_p": top_p}
        )

    def get_model(self, temperature: float = 0.0, top_p: float = 0.5):
        if self.model is None:
            self.initialize_model(temperature, top_p)
        return self.model

# Usage
def main():
    config = AzureDeploymentConfig()
    azure_service = AzureOpenAIService(config)
    model = azure_service.get_model(temperature=0.0, top_p=0.5)
    # Use the model for whatever purpose needed

if __name__ == "__main__":
    main()

/Users/s748779/IAG_test/test1/lib/python3.9/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(

ImportError: cannot import name 'BaseSettings' from 'pydantic.env_settings' (/Users/s748779/IAG_test/test1/lib/python3.9/site-packages/pydantic/env_settings.py)

In [10]:

model = get_azure_openai(temperature=1.0)
with get_openai_callback() as cb:
    print(model.invoke("Tell me a joke about an insurance company."))
    print(f"Total Tokens: {cb.total_tokens}")

content="Why did the insurance company recruit a band of musicians?\n\nBecause they had a lot of coverage and were great at risk assessment—they knew how to play it by ear and always stayed in tune with their clients' needs!" response_metadata={'token_usage': {'completion_tokens': 43, 'prompt_tokens': 16, 'total_tokens': 59}, 'model_name': 'gpt-4', 'system_fingerprint': 'fp_811936bd4f', 'prompt_filter_results': [{'prompt_index': 0, 'content_filter_results': {'hate': {'filtered': False, 'severity': 'safe'}, 'self_harm': {'filtered': False, 'severity': 'safe'}, 'sexual': {'filtered': False, 'severity': 'safe'}, 'violence': {'filtered': False, 'severity': 'safe'}}}], 'finish_reason': 'stop', 'logprobs': None, 'content_filter_results': {'hate': {'filtered': False, 'severity': 'safe'}, 'self_harm': {'filtered': False, 'severity': 'safe'}, 'sexual': {'filtered': False, 'severity': 'safe'}, 'violence': {'filtered': False, 'severity': 'safe'}}} id='run-03f8ab3d-924c-4245-8238-fff15d4141de-0' usage_metadata={'input_tokens': 16, 'output_tokens': 43, 'total_tokens': 59}
Total Tokens: 59

In [13]:
p1 = """
Consider the following problem statement and context provided by the solutions architect ,  and the top 5 Architecture Decisions that matched with the problem statement and explain how the ADs are solving the issues mentioned in the problem statement. 
Also mentions if there are some capabilites that need new Architecture Decisions and cannot be fulfilled by the matched ADs.

problem statement : 
Background
An underwriting restriction may be implemented in response to a major event or the risk of a major event occurring  such as;  Earthquake, Tsunami, Volcano, Wildfire, Ex-tropical cyclone.
An underwriting restriction is a restriction on the sale or increases in sum insured of risks within specific lines of business based on a geographical location. 
Problem
Due to the nature of events that trigger underwriting restrictions,  these need to be implemented as soon as possible after a decision has been made.  These events can happen outside of standard business hours.  
The IAG technical landscape is varied, complex and constantly changing and it is not clear how to get restrictions implemented or updated across brands, lines of business and geographical locations.   Anecdotally outside of  Personal lines State/Huon, State/AMI digital and AON CPF,  Portfolio have very little visibility on how to implement systems restrictions. 

 In the past getting system restrictions in place has been adhoc, using back channels rather than the Tech Front Door, with Portfolio team members reliant upon who they know rather than following  a prescribed Tech & Ops process. If the “go-to person” is not around then Portfolio may not know who to contact. 




Matched ADs : 
 AD 136 - Which system/s will provide operational peril risk for pricing for CGU Direct Home, Motor & Niche? 
Problem : AD 125 - Which system/s will provide operational peril risk for pricing and underwriting? determined that the strategic solution for peril pricing and underwriting was to use the PRICE application. However this system is not ready for production yet. The peril underwriting can be delayed indefinitely, but it is necessary to have peril pricing from the first release. So what should the interim solution be for CGU Direct Home, Motor & Niche?	
 AD 108 - Where should correspondence insert/onsert management be done? 
Problem : When outbound correspondence for policy outbound is generated, a set of static documents is included.  This includes specified policy transaction inclusions such as PDS, SPDS, and KFS.  It may optionally include marketing inserts. The set of static documents can be derived from information passed into the document composition API (eg LoB, Brand, Transaction type).  The set of inclusions will periodically change via a business process, for example when a new PDS is issued, or a new marketing campaign occurs Currently within the HUON eco-system this is managed within custom mainframe code. 

"""

In [2]:
with get_openai_callback() as cb:
    print(model.invoke(p1).content)
    print(f"Total Tokens: {cb.total_tokens}")

NameError: name 'model' is not defined

In [15]:
p2 = """
Consider the following problem statement and context provided by the solutions architect ,  and the top 5 Architecture Decisions that matched with the problem statement and explain how the ADs are solving the issues mentioned in the problem statement. 
Also mentions if there are some capabilites that need new Architecture Decisions and cannot be fulfilled by the matched ADs.

problem statement : 
Background
An underwriting restriction may be implemented in response to a major event or the risk of a major event occurring  such as;  Earthquake, Tsunami, Volcano, Wildfire, Ex-tropical cyclone.
An underwriting restriction is a restriction on the sale or increases in sum insured of risks within specific lines of business based on a geographical location. 
Problem
Due to the nature of events that trigger underwriting restrictions,  these need to be implemented as soon as possible after a decision has been made.  These events can happen outside of standard business hours.  
The IAG technical landscape is varied, complex and constantly changing and it is not clear how to get restrictions implemented or updated across brands, lines of business and geographical locations.   Anecdotally outside of  Personal lines State/Huon, State/AMI digital and AON CPF,  Portfolio have very little visibility on how to implement systems restrictions. 

 In the past getting system restrictions in place has been adhoc, using back channels rather than the Tech Front Door, with Portfolio team members reliant upon who they know rather than following  a prescribed Tech & Ops process. If the “go-to person” is not around then Portfolio may not know who to contact. 




Matched ADs : 
 AD 136 - Which system/s will provide operational peril risk for pricing for CGU Direct Home, Motor & Niche? 
Problem : AD 125 - Which system/s will provide operational peril risk for pricing and underwriting? determined that the strategic solution for peril pricing and underwriting was to use the PRICE application. However this system is not ready for production yet. The peril underwriting can be delayed indefinitely, but it is necessary to have peril pricing from the first release. So what should the interim solution be for CGU Direct Home, Motor & Niche?	
 AD 108 - Where should correspondence insert/onsert management be done? 
Problem : When outbound correspondence for policy outbound is generated, a set of static documents is included.  This includes specified policy transaction inclusions such as PDS, SPDS, and KFS.  It may optionally include marketing inserts. The set of static documents can be derived from information passed into the document composition API (eg LoB, Brand, Transaction type).  The set of inclusions will periodically change via a business process, for example when a new PDS is issued, or a new marketing campaign occurs Currently within the HUON eco-system this is managed within custom mainframe code. 
 AD 005 - What cloud pattern & technology will be used for PC/BC? 		 
 Problem : Guidewire Policy Center will be the core Policy system used across Australia and New Zealand.  To this date, IAG has only hosted core systems (indeed any System of Record) in internal data centers.  This has long been regarded as the optimum solution for meeting IAG's privacy and regulatory requirements, influenced by advice put forward by APRA. With the increasing use of Public Cloud within the Australian Financial Services industry, the regulatory and privacy view put forward by APRA has changed.  Public Cloud deployments now regarded as viable as long as the appropriate measures can be met and demonstrated. We need to determine the appropriate hosting location based on organisational strategic intent and risk appetite. 
 AD 044 - What high level party model will be used across the operational ecosystem? 		 
 Problem : There are a number of different ways of representing Customers and other parties within our current insurance brands at IAG; we will refer to this as the Party Model. The party models have many common features, such as supporting both Individuals (with name & DOB) and Organisations (with name & business number) as legal entities, but have two high level, and material, differences that affect customer experience and business process. These are: 
 AD 056 - What system/s will store inbound and outbound documents for CGU Direct Home and Motor? 	
 Problem : Inbound and outbound policy documents must be: 

You are freeto modify the prompt to fulfill the specific needs of this task. 
"""

In [16]:
with get_openai_callback() as cb:
    print(model.invoke(p2).content)
    print(f"Total Tokens: {cb.total_tokens}")

The problem statement indicates that there is a need for a rapid and consistent implementation of underwriting restrictions across various brands, lines of business, and geographical locations in response to major events. The current process is ad hoc and lacks a clear and standardized approach, leading to inefficiencies and potential delays.

Let's analyze how the matched Architecture Decisions (ADs) address the issues mentioned in the problem statement:

1. AD 136 - Interim solution for peril pricing and underwriting:
   This AD acknowledges the need for a system to manage peril risk for pricing, which is crucial for implementing underwriting restrictions. By identifying an interim solution, it ensures that there is no delay in peril pricing during the transition to the PRICE application. This helps in rapid response to events but does not directly address the implementation of underwriting restrictions across the board.

2. AD 108 - Correspondence insert/onsert management:
   This AD deals with the management of outbound correspondence and the inclusion of static documents. While it improves the process of document management, it does not directly solve the problem of implementing underwriting restrictions. However, a robust document management system could potentially be leveraged to disseminate information about new restrictions quickly.

3. AD 005 - Cloud pattern & technology for PC/BC:
   Moving to the cloud can offer greater flexibility and scalability, which is beneficial when rapid changes are needed, such as implementing underwriting restrictions. This AD could indirectly support the problem by providing a more agile infrastructure that can be updated quickly in response to major events.

4. AD 044 - High level party model across the operational ecosystem:
   A unified party model can enhance the understanding of customer data across different brands and lines of business. While this AD does not directly address the implementation of underwriting restrictions, it can facilitate better decision-making by providing a clear view of the affected parties.

5. AD 056 - Document storage for CGU Direct Home and Motor:
   This AD ensures that all inbound and outbound policy documents are stored and managed effectively. Similar to AD 108, while it does not directly solve the problem, a well-organized document storage system could be essential for tracking and communicating underwriting restrictions.

Capabilities that may need new Architecture Decisions:
- A centralized decision-making and implementation system for underwriting restrictions that can be accessed and activated outside of standard business hours.
- A standardized process for rapid deployment of underwriting restrictions across all brands and lines of business, with clear roles and responsibilities.
- A communication protocol that ensures all relevant parties are informed about the new restrictions in a timely manner, regardless of the time of day.
- Integration of geographical information systems (GIS) to accurately define and communicate the areas affected by the underwriting restrictions.
- Real-time monitoring and alerting systems that can trigger the underwriting restriction process automatically based on predefined criteria related to major events.

In summary, while the matched ADs provide a foundation for addressing parts of the problem, new ADs are likely needed to create a comprehensive solution that ensures the rapid and consistent implementation of underwriting restrictions in response to major events.
Total Tokens: 1533

In [21]:
pe = """
how does the url have to look in the config.ini file to avoid the following error ?

ValidationError: 1 validation error for AzureDeploymentConfig
azure_endpoint
  Input should be a valid URL, relative URL without a base [type=url_parsing, input_value='"https://payg-kar-d-r1-oai.openai.azure.com"', input_type=str]
"""

In [22]:
with get_openai_callback() as cb:
    print(model.invoke(pe).content)
    print(f"Total Tokens: {cb.total_tokens}")

The error message you're seeing indicates that the `azure_endpoint` value in your `config.ini` file is not being parsed as a valid URL. This can sometimes happen if there are extra characters (like quotes) around the URL that shouldn't be there.

To avoid this error, ensure that the URL in the `config.ini` file is properly formatted without any extra quotes or whitespace. Here's an example of how it should look:

```ini
[azure]
azure_endpoint=https://payg-kar-d-r1-oai.openai.azure.com
```

Make sure that there are no extra characters around the URL. In the error message you provided, it looks like there are double quotes (`"`) around the URL, which should not be there. Remove those quotes and any other extraneous characters, and the URL should be parsed correctly.

If you are still encountering issues, ensure that the rest of the `config.ini` file is correctly formatted and that there are no syntax errors. The file should follow the standard INI file structure with sections (enclosed in square brackets `[ ]`) and key-value pairs.
Total Tokens: 308

In [ ]:
input_dict = {  "590260523": { "content": "AD 136 - Which system/s will provide operational peril risk for pricing for CGU Direct Home, Motor & Niche? ...",
                                "page_link": "https://iag.atlassian.net/wiki/spaces/SEP/pages/590260523",
                                "l1_capability": { "Customer": 
                                                  {"Web": {"level": 1,
                                                            "description": "Allows customers to access insurance services through the web",
                                                            "impact": "Empty"}, # ... other L1 keys with "Empty" or non-"Empty" impact values ...
                                                   },           # ... other L0 keys ...
                                                  }
                              }   # ... other L0 keys ...
             }# Filter the dictionary\n

filtered_dict = {l0_key: {"content": l0_value["content"],
                          "page_link": l0_value["page_link"],
                          "l1_capability": {
                              l1_key: {
                                  l2_key: l2_value for l2_key, l2_value in l1_value.items() if l2_value.get("impact") != "Empty"} for l1_key, l1_value in l0_value["l1_capability"].items() if any(l2_value.get("impact") != "Empty" for l2_value in l1_value.values()) } } for l0_key, l0_value in input_dict.items() if any(any(l2_value.get("impact") != "Empty" for l2_value in l1_value.values()) for l1_value in l0_value["l1_capability"].values() )}
# Remove L0 keys with empty L1 capabilities\n
filtered_dict = {l0_key: l0_value for l0_key, l0_value in filtered_dict.items()\n    if l0_value["l1_capability"]}

print(filtered_dict)

```\n\nThis code does the following:\n\n
1. Iterates through each L0 key in the input dictionary.\n
2. For each L0 key, it checks the L1 capabilities to see if they have any impact other than "Empty".\
3. It then filters out the L1 keys that have an impact value of "Empty".\
4. Finally, it removes any L0 keys that have all L1 impacts as "Empty"

In [10]:
with get_openai_callback() as cb:
    model = get_azure_openai(temperature=1.0)
    print(model.invoke(p1).content)
    print(f"Total Tokens : {cb.total_tokens}")

To filter the dictionary based on the criteria you've provided, you can use the following Python code:

```python
input_dict = {
    "590260523": {
        # ... (rest of the dictionary as provided in the question)
    }
}

def filter_impact(input_dict):
    # Dictionary to store the filtered results
    filtered_dict = {}

    # Iterate over the top-level keys (L0)
    for l0_key, l0_value in input_dict.items():
        # Dictionary to store the sub-keys (L1) that have non-empty impact
        l1_with_impact = {}

        # Check if 'l1_capability' exists in the dictionary
        if 'l1_capability' in l0_value:
            # Iterate over the second-level keys (L1)
            for l1_key, l1_value in l0_value['l1_capability'].items():
                # Filter out the keys with 'impact' value 'Empty'
                l1_with_impact[l1_key] = {k: v for k, v in l1_value.items() if not (isinstance(v.get('impact'), str) and v.get('impact') == 'Empty')}

            # Remove L1 keys if they are empty after filtering
            l1_with_impact = {k: v for k, v in l1_with_impact.items() if v}

        # If after filtering, there are L1 keys with impact, add them to the filtered dictionary
        if l1_with_impact:
            # Copy the original L0 values
            filtered_l0_value = l0_value.copy()
            # Update the 'l1_capability' with the filtered L1 keys
            filtered_l0_value['l1_capability'] = l1_with_impact
            # Add the filtered L0 key to the filtered dictionary
            filtered_dict[l0_key] = filtered_l0_value

    return filtered_dict

# Apply the filter function to the input dictionary
filtered_dict = filter_impact(input_dict)

# Print or use the filtered dictionary as needed
print(filtered_dict)
```

This code defines a function `filter_impact` that processes the input dictionary. It iterates over the L0 keys and then the L1 keys within the 'l1_capability' dictionary. It filters out any L1 keys that have an 'impact' value of 'Empty' and removes any L0 keys that end up with all L1 impacts as 'Empty'. The resulting dictionary is then returned and can be printed or used as needed.
Total Tokens : 1399

In [14]:
p1 = """
Refactor the following code for the streamlit page, such that, it not only shows the top 5 and next 5 results, but also shows the weblink and content stored for each of them to the right side. 
so when the results are displayed on the streamlit page, we have the top 5 and next 5 results on the left and their corresponding page_link and subheading_content on the right. 
The content part can be inside an expander and link should be visible alongside the result.
the load_vector_db_results returns a dict like 
{id_1: { "ad_ref" : "AD 005 - What cloud pattern & technology will be used for PC/BC?",
        "author" : "Tom Gionfriddo (Deactivated)",
        "page_link" : https://tlassian.net/wiki/spaces/SEP/pages/577713",
        "page_ref" : "590077713",
        "subheading_content" : ""Problem : Guidewire Policy Center will be the core Policy system used across Australia and New Zealand.  To this date, IAG has only hosted core systems (indeed any System of Record) in internal data centers.""
        },
 id_2: ... }

    with open("st/input.json","r") as input_json:
        in_dict = json.load(input_json)
    
    results = load_vector_db_results(in_dict, embedding_model, client, collection_name )
    
    st.subheader("Top 5 Matches")
    for i, result in enumerate(results['top_5']):
        st.write(f"{i+1}. {result}")
    
    with st.expander("Show more results"):
        for i, result in enumerate(results['next_5']):
            st.write(f"{i+6}. {result}")


"""

In [15]:
model = get_azure_openai(temperature=1.0)
print(model.invoke(p1).content)

To refactor the code as requested, we need to make a few changes. We'll use Streamlit's columns to display the results on the left and their corresponding page links and subheading content on the right. Here's the updated code:

```python
import streamlit as st
import json
from your_module import load_vector_db_results  # Assuming load_vector_db_results is imported from your_module

# Load the input data
with open("st/input.json", "r") as input_json:
    in_dict = json.load(input_json)

# Get the results from the vector database
results = load_vector_db_results(in_dict, embedding_model, client, collection_name)

# Display the top 5 matches with their corresponding links and content
st.subheader("Top 5 Matches")
for i, (result_id, result_data) in enumerate(results['top_5'].items()):
    col1, col2 = st.columns([1, 3])  # Adjust the ratio as needed
    with col1:
        st.write(f"{i+1}. {result_data['ad_ref']}")
    with col2:
        st.markdown(f"[Link]({result_data['page_link']})")
        with st.expander("Content"):
            st.write(result_data['subheading_content'])

# Display the next 5 matches with their corresponding links and content
with st.expander("Show more results"):
    for i, (result_id, result_data) in enumerate(results['next_5'].items()):
        col1, col2 = st.columns([1, 3])  # Adjust the ratio as needed
        with col1:
            st.write(f"{i+6}. {result_data['ad_ref']}")
        with col2:
            st.markdown(f"[Link]({result_data['page_link']})")
            with st.expander("Content"):
                st.write(result_data['subheading_content'])
```

Please note that I've made the following assumptions:

1. The `load_vector_db_results` function returns a dictionary where the keys are `top_5` and `next_5`, and the values are dictionaries with the result ID as the key and the result data as the value.
2. The `result_data` dictionary contains keys `ad_ref`, `page_link`, and `subheading_content` that correspond to the result's reference, web link, and content, respectively.
3. The `your_module` is a placeholder for the actual module name where the `load_vector_db_results` function is defined.

Make sure to replace `your_module` with the actual module name and adjust the column ratios as needed for your Streamlit layout.

In [74]:
df2.iloc[:, :5]

,opportunity_name,problem_statement,outcome,RAID,actual_cost
0,Vehicle Fulfilment Platform (Carbar),Problem statement*\nWhat is the business/custo...,Outcomes*\nBased on the business/ customer pro...,Risks – \nTiming. Pending other activity withi...,M
1,Add 'Channel' as a mandatory CCM Field,What is the business/customer problem we want ...,We are proposing to add Complaints Channel as ...,"\nFunding pathway needs to be confirmed, will ...",M
2,Consumer Leads in Orbit (Phase 2 + Lifestyle),"Currently, our colleagues face the frustration...","Delivery of the leads capability across Motor,...",RISKS: \nTechnical resourcing availability to ...,M
3,Digital out of the box,Problem statement*\nWhat is the business/custo...,Based on the business/ customer problem statem...,List any key risks or dependencies that may pr...,M
4,eDocs Uplift: EP PC Preselected Yes to eDocs i...,Problem statement*\nWhat is the business/custo...,Outcomes*\nBased on the business/ customer pro...,Risks / constraints / dependencies / assumptio...,XS
5,MVB redesign (Initiative from the NRMA),The NRMA would like to change name and price o...,Provides a convenient experience for customers...,NaN,S
6,NPCID-2023635,"Problem statement*\n\nTraditionally, excess is...",Outcomes*\nBased on the business/ customer pro...,Risks / constraints / dependencies / assumptio...,S
7,SME API Exposure to partners,IAG is missing out on sales opportunities to r...,Creating the links and information required to...,Ensuring that work doesn’t have to be done mul...,S
8,Extend Digital Analytics Capability,1. We are limited in our ability to track and ...,1. Refresh the discovery work done 1 year ago ...,Implementation needs to be prior to NRMA NSW E...,S
9,Home Risk Index,For Consumers:\nThere is a lack of quality pub...,For a consumer audience considering a new home...,Peril Data Licensing:\nThe AAL/100k modelling ...,M

In [78]:


# df2.iloc[:, :5].to_json()

{'opportunity_name': {'0': 'Vehicle Fulfilment Platform  (Carbar)',
  '1': "Add 'Channel' as a mandatory CCM Field",
  '2': 'Consumer Leads in Orbit (Phase 2 + Lifestyle)',
  '3': 'Digital out of the box',
  '4': 'eDocs Uplift: EP PC Preselected Yes to eDocs in New Business Flow and update eDocs scripting',
  '5': 'MVB redesign (Initiative from the NRMA)',
  '6': 'NPCID-2023635',
  '7': 'SME API Exposure to partners',
  '8': 'Extend Digital Analytics Capability',
  '9': 'Home Risk Index'},
 'problem_statement': {'0': 'Problem statement*\nWhat is the business/customer problem we want to solve?\n\nDIA Insurance Supply Chain is considering the transition of Carbar Vehicle Fulfilment Platform (VFP) to help IAG. The tool is a quoting tool that we will use internally to engage with motor dealer networks. \n\nCarbar are wanting to review creating a duplication of the platform for IAG to “transition” inhouse. \n\nWe require an architectural assessment.',
  '1': 'What is the business/customer problem we want to solve?\x0b\x0bWhat is happening?\nTo include ‘Channel’ as a new mandatory field in CCM when capturing or updating a Complaint.\n\nWhy is this happening?\nIAG has a mandatory requirement to capture this information due to the regulatory issues of currently being non-compliant with AFCA.\n\n\nPlease see https://iag.atlassian.net/browse/DDI-1110 for further context & history',
  '2': 'Currently, our colleagues face the frustration of having to navigate and utilise multiple systems to service their customers. To capture a lead or referral for a customer, they need to use either SCV (old application to be decommissioned as part of our Technology strategy) or the Xcelr8 eForm (depending on the product), to pass this information to the right area of the business to contact the customer.  This initiative will simplify the process for our colleagues by allowing them to remain within one application, Orbit Desktop, to identify and capture such leads or referrals as opposed to having to jump through multiple applications. In February, as part of the SME Micro Program, Leads Management functionality for Business Insurance was brought into Orbit (Phase 1), so where possible we’ll be leveraging and extending this out for CD Leads. This will also be a step to enabling the decommission of SCV/Workbench, as well as the Xcelr8 eForm referral system.',
  '3': "Problem statement*\nWhat is the business/customer problem we want to solve?\n\nWithin the context of our strategic goal to enhance customer experience and realize operational efficiencies, we're facing a critical challenge in customer engagement with our digital platforms—Heritage SSC and EP Online Account. \n\nDespite the platforms' capabilities to simplify and speed up various customer interactions, only a mere 3% of customers register for an online account following a policy purchase in Heritage digital. This low adoption rate doesn't just limit our ability to provide a superior and more cost-effective customer experience; it also hampers our competitiveness. \n\nWe understand that customers are seeking convenient, quick, and efficient ways to manage their policies. However, our current onboarding mechanisms are failing to capture customers at pivotal lifecycle events—such as renewals, payments, and claims—resulting in missed opportunities for engagement and value delivery. \n\nThis lack of adoption also forfeits the strategic advantage we could otherwise gain over both direct and adjacent competitors, many of whom are actively investing in simplifying digital self-service adoption.",
  '4': 'Problem statement*\nWhat is the business/customer problem we want to solve?\n\nDistribution of policy documents is a mandatory legal activity which is currently delivered through post and email. In FY23, DIA spent over $15M on print and postage. It is an area of opportunity for the following reasons;\x0b\uf0d8 Cost to distribute printed policy documents is\x0bapproximately 40 times more expensive than email\x0b\uf0d8 IAG’s carbon footprint impact\x0b\uf0d8 Cost to implement industry-wide regulatory reforms\x0band remediation (UCT, GICOP, IP, etc) is also an\x0bexpensive affair\x0b\nIf we increase our eDocs consent rate there will be a\x0bdirect savings to DIA’s TCE. It will also enable us to\x0bcreate enhanced digital customer interactions and\x0bunlock value adds.\n\nCurrently both Yes and No options for eDocs consent are blank in Policy Centre.',
  '5': 'The NRMA would like to change name and price of the current roadside assistance offering in the Motor funnel, as well as add a third product for IAG to sell as part of the Sell RSA offering in the Motor funnel (see additional email attached for details).',
  '6': 'Problem statement*\n\nTraditionally, excess is used as a customer contribution to claims as they occur; it also helps to reduce small claims and provide savings on administration costs. Both Home and Motor excess levels have not been reviewed for several years, which means higher than anticipated volume of low value claims being processed and paid, resulting in claims cost challenges\n\nCurrently, some states have lower default excess compared to major competitors in the market. This impacts our competitive position with lower conversion rate.\xa0\n\nOpportunity to realise benefit margin for East Heritage customers prior to EP migration',
  '7': 'IAG is missing out on sales opportunities to reach SME customers by not being in all the places that they are. All sales for SME direct products are via IAG channels, there is no way for partners to sell insurance on our behalf by utilising aspects of our own technology. \n\nWe want to be able to offer SME insurance to a wide range of SME customers in the way and situation that suits them and their business. ',
  '8': '1. We are limited in our ability to track and understand customer behaviour in the Digital flows because\nWe are unable see what customers do and what errors they receive due to their behaviour in digital\nWe cannot see where customers focus on a page due to a lack of heat-mapping\n\n2. We have to manually audit our websites to understand whether our items such tags and cookies are working correctly. This means we miss items which can negatively impact customers and also our ability to track customer behaviour.',
  '9': "For Consumers:\nThere is a lack of quality publicly available natural peril data for homebuyers, making it difficult for them to make informed decisions about the properties they're considering purchasing. This lack of information can lead to costly surprises for homebuyers, who may not be aware of the potential risks associated with a particular property until it is too late, including home insurance premiums.\n\nFor Partners:\nOur strategic banking partners lack quality natural peril risk data that will help them to make improved lending decisions & help their customers to factor in property location risk & home insurance affordability.\n\nBanks' increasing exposure to climate risks raises the need for accurate risk analysis.\nLenders have low visibility of a home’s risk during the loan application process.\nLenders have an increasing need to identify and manage risk in their home loan portfolios."},
 'outcome': {'0': 'Outcomes*\nBased on the business/ customer problem statement, what are the outcomes we are looking to achieve?\xa0\n\nTransition the VFP to IAG to so that we can continue to service our customers. The VFP will allow ease of connection when engaging with motor dealerships nationally.',
  '1': 'We are proposing to add Complaints Channel as a field in CCM. IAG has a mandatory requirement to capture this information in the following format:\n1 - Face to face\x0b2 - Phone\x0b3 - E-mail\x0b4 - Web Chat\x0b5 - Online Form\x0b6 - Social Media\x0b7 - Referral from AFCA \x0b8 - Other\x0b9 - Unknown',
  '2': 'Delivery of the leads capability across Motor, Home , and lifestyle products across the NRMA and SGI brands for the assisted channel only.',
  '3': 'Based on the business/ customer problem statement, what are the outcomes we are looking to achieve?\xa0\n\nIncrease Customer Lifetime Value:\xa0Higher retention and more value per\xa0customer through seamless digital experiences.\xa0More opportunities for upselling and cross-selling\xa0due to higher digital engagement.\xa0\n\nTCE:\xa0Lower operational costs through reduced contacts,\xa0and more optimal customer setup/target profile with e-docs,\xa0marketing consent etc...\xa0\n\nIncreased Digital Adoption: Get more customers to adopt our digital platforms. Higher engagement levels as more\xa0customers use digital platforms, making future digital initiatives easier\xa0to roll out.\n\nCustomer Re-Onboarding: Provides an avenue to reactivate and re-engage the\xa0existing customer base, driving further digital adoption and improving\xa0the customer lifecycle and overall digital experience.',
  '4': 'Outcomes*\nBased on the business/ customer problem statement, what are the outcomes we are looking to achieve?\xa0\n\nDuring Policy centre quote flows, when a consultant reaches the eDocs consent question, it will pre-fill the yes box \nNew scripting will prompt the consultant to add value through eDocs (approved scripting to follow)',
  '5': 'Provides a convenient experience for customers to be able to easily buy Motor and RSA',
  '6': 'Outcomes*\nBased on the business/ customer problem statement, what are the outcomes we are looking to achieve?\xa0\n\nLooking to achieve budgeted saving of $30m over 12 months\n\nUplift excess levels for both new business and renewal to make excess more in line with average claim size and keep up with inflation',
  '7': 'Creating the links and information required to enable, external parties to connect with API’s allowing them to quote and sell (and eventually service), SME insurance products. \n\nBe able to offer API connections to compatible businesses, who share the IAG values and customer outlook. ',
  '8': '1. Refresh the discovery work done 1 year ago and decide on appropriate to tools / vendors so:\nWe can view recordings of individual sessions so we can track root cause of issues\nWe can understand the hotspots on pages where customers are hovering\nWe can automatically monitor analytics implementation in our website and identify issues\n\n2. Decide on funding pathway for tools.',
  '9': 'For a consumer audience considering a new home, the Home Risk Index will provide quality and easy to understand natural peril risk insights for a given location. Embedding this data earlier into the homebuying journey will raise our brand awareness and make insurance affordability more of a consideration than our research suggests it is today.\n\nFor our banking partners, providing peril data to assist with their lending decisioning & mortgage portfolio analysis will strengthen our strategic relationships and provide a value-add for new partnerships. '},
 'RAID': {'0': 'Risks – \nTiming. Pending other activity within the Carbar business, we may time constrained re delivery. \n\nGiven other non-related changes in the CB business, their capacity to support (tech SME) may be constrained. \n\n\nAssumptions – \nThere isn’t significant system uplift required in order to transition VFP into IAG’s tech stack.\n\nResource and other costs to integrate is not considerable – cost v benefit will need to be considered.\n\nThere is assess to tech resources available to support the immediate transition (if progressed). ',
  '1': '\nFunding pathway needs to be confirmed, will be divisional but need exact costs\n\nMandatory compliance date',
  '2': 'RISKS: \nTechnical resourcing availability to work on the project deliverables concurrently. If resources are not available this will result to further costs/effort as the project timeline will increase due to stop/start activities.\nEDH resourcing have not been involved in the estimates due to other project constraints.\nNon-functional requirements are yet to be defined. Assumption: Phase 1 (SME Leads) non-functional requirements will be similar if not the same for CD leads.\nCONSTRAINTS:\nThere are no testing environments for end to end testing (full journey) – which will need to be factored into the costs and effort.\nDEPENDENCIES:\nCross-functional platforms are to work together to deliver on all agreed business/non-functional requirements.',
  '3': "List any key risks or dependencies that may prevent outcomes being achieved, constraints that must be met, or assumptions that have been made.\n\nRisks\n\nTechnical & Security Hurdles: The risk that unforeseen technical or security challenges could delay implementation or compromise the system's integrity.\n\nMispositioning of Onboarding: The risk that poor framing of the onboarding and setup process as an additional or separate step could hinder customer adoption and engagement.\n\nIssues\n\nResource Constraints: The challenge of insufficient CLP (Customer Lifecycle Platform) resources impacting timely and quality delivery.\n\nAssumptions\n\nDIA Funding: The assumption that DIA funding will be successful in resolving the CLP resource issue.\n\nMarket Conformity: The assumption that seamless onboarding is a common market practice, thus aligning with customer expectations.\n\nDependencies\n\nCLP Resources: This project is dependent on adequate CLP resources, which is currently being addressed through DIA funding.",
  '4': 'Risks / constraints / dependencies / assumptions / challenges\xa0\nList any key risks or dependencies that may prevent outcomes being achieved, constraints that must be met, or assumptions that have been made.\n\n\uf0d8 Prioritisation against other sectors/portfolios\x0b\uf0d8 Commitment from required\xa0tech and business\x0bteams\n',
  '5': None,
  '6': 'Risks / constraints / dependencies / assumptions / challenges\xa0\nList any key risks or dependencies that may prevent outcomes being achieved, constraints that must be met, or assumptions that have been made.\n\nPotential retention impacts in EP, where West customers see a second excess increase in EP native renewals\n\nEP DIA/IIA/NZ impacts of additional $4000 excess level for home product\n\n‘Lights on’ HUON maintenance, resulting in vulnerabilities in delivering change\n\nOutbound / Customer Comms capacity constraints\xa0\n\nDeployment of change between IAG and RACV comes with inherent tech risks.\xa0\n\nPDS update required for heritage home products, which may not have the capacity.',
  '7': 'Ensuring that work doesn’t have to be done multiple times as Commercial Enterprise Platform comes closer.\n\nConfirming that necessary documentation is created and shared appropriately. This needs to be kept up to date so as to allow for additional links to be established (subject to confirmation of bandwidth etc.).\n\nDetails about data gathering / sharing / storing will need to be covered. Including details of who owns the customer details and journey (how much is controlled by IAG). \nIncludes details of Cloud Adoption Framework (CAF) and security architecture.\n',
  '8': 'Implementation needs to be prior to NRMA NSW EP migration to allow time to baseline data and for analysis and fixing of issues\nPrivacy / security issues with session recording\nHighly likely we’ll need to onboard new third-party cloud-based vendors',
  '9': 'Peril Data Licensing:\nThe AAL/100k modelling that the Home Risk Index derives its data from is sourced from many 3rd party data sources – a mix of professional peril data companies, local councils, industry data pools. We are currently working through a risk assessment of licensing conditions to use said data sources for Home Risk Index.\n\nEmbedded Experience Layer:\nTo productionise the Home Risk Index API for intended use cases – exposing data externally – it is dependent on the Experience Layer to provide requisite security, contracts & integration.'},
 'actual_cost': {'0': 'M',
  '1': 'M',
  '2': 'M ',
  '3': 'M',
  '4': 'XS',
  '5': 'S',
  '6': 'S',
  '7': 'S',
  '8': 'S',
  '9': 'M'}}

In [13]:
with open('Safe to experiment.html', 'r') as f:
    html_file = f.read()

p1 = f"""
can you convert the content ont this webpage into a neat dictionary that focuses on the 3 major sections talked about on this page 
https://iagau.sharepoint.com/sites/GenAIatIAG/SitePages/Safe-to-experiment.aspx#gai-stories .
Here's a copy pasted version of the content: 

=================== Live Uses ===================
Microsoft Copilot for web
Microsoft Copilot for web is your IAG approved, AI chat solution (think ChatGPT) available now as part of your IAG Microsoft 365 license
 
Find out how others are using Copilot for Web here: Copilot for web - Prompt ideas (sharepoint.com)
 

What's GitHub Copilot and How Devs can ...
GitHub Copilot
Developer Assistant to write code and solve issues, faster
 
 
Suggests individual lines and whole functions instantly​
Powered by a generative AI model developed by GitHub, OpenAI, and Microsoft
GitHub - Copilot

Artika Narayan
Executive Manager, Enterprise Environments and Release Engineeri

Glen Kennedy
Manager, Delivery Engineering
 


             
 GenAI Claims      assistant
 
 
 
Improved employee and customer experience in claims handling
Claims Agent asks questions and CASI provides answers from relevant Product Disclosure Statements and policy documents
Now extended to Property and Motor Claims 

Anna Coticchio
Manager, Automation (Digital) & Continuous Improvement

MICHAEL LO1
Principal, Analytics Product Owner
New Relic AI  
Observability Assistant
New Relic AI (NRAI) is designed to help every member of your team improve observability, not just engineers. We combined OpenAI's large language models (LLMs) with our unified telemetry data platform

Lee McRae
Manager, Observability and AI Operations

Shefali Varma
Team Lead (Enterprise Analytics and Event Monitoring)

Anuj Kumar
Product Manager, ServiceNow Pl

=================== Other Pilots ===================
Copilot for M365
Gen AI within the Microsoft apps
 
 
 
Gen AI embedded in Microsoft 365 apps such as Teams, Outlook, Word & PowerPoint, connected to your Microsoft data (Chats, emails, meetings, files).
IAG is part of the Early Adopter Program, with 300 Early Adopters currently using the tool

Daniel Egan
Senior Change Manager

Duane Herring
EM, Digital Workplace & Contact Centre
 



Generative AI Agent Builder
 
 
 
Build safe, reuseable GAI agents, anchored in our data to automate tasks 
Multiple applications, including content centre script creation, marketing content creation, customer response editing
Check out or add your use case here - LUMI Use Cases - Strategy & Innovation - Analytics - Confluence (atlassian.net)

Ehsan Mazloumi
Manager, AI Products

Omid Karr
Executive Manager, Ambiata Advanced Analytics

Gemini
Generative AI Assistant across Google Cloud Platform
 
 
 
Used to increase productivity and efficiency in data engineering, data analysis and platform security and operations workflows
Powered by generative AI models from Google.

Burak Hoban
Executive Manager, Data Platforms

Omid Karr
Executive Manager, Ambiata Advanced Analytics
Knowledge Assist
   Improve the quality and search & retrieval      of knowledge articles 
Used to increase productivity and efficiency in service and claims knowledge by quickly accessing and improving the quality of knowledge articles

Omid Karr
Executive Manager, Ambiata Advanced Analytics

Ehsan Mazloumi
Manager, AI Products
ARKI ArchAssist
Improve the quality and efficiency of developing IT artefacts and assessments
Used to create draft artefacts for IT Assessments and understanding

Kirit Kundu
Executive Manager, Enterprise Architecture & Governance

=================== More PoCs being added ===================

1) Fraud GenAI (by CASI squad) - POC in IIA
2) Knowledge GenAI (by CASI squad) - POC in IIA
3) Data-mapping for long-term archiving of legacy systems (under project Kondo) - POC in T&O
4) Image recognition for Fraud - POC in RIA
5) CTP GenAI - at discovery stage - RIA and T&O
6) CASI for NZ Claims - in discovery stage
7) GenAI for NZ Homehub - POC completed
8) Fraud GenAI monitoring and alerts
9) SVx GenAI bot POC - enable querying SVx data using natural language
 

"""

In [14]:
with get_openai_callback() as cb:
    model = get_azure_openai(temperature=1.0)
    print(model.invoke(p1).content)
    print(f"Total Tokens : {cb.total_tokens}")

Based on the provided content, here is a neat dictionary focusing on the three major sections discussed on the page:

```python
safe_to_experiment = {
    "Live Uses": {
        "Microsoft Copilot for web": {
            "Description": "AI chat solution (think ChatGPT) available as part of IAG Microsoft 365 license",
            "Usage": "Find out how others are using Copilot for Web here: Copilot for web - Prompt ideas (sharepoint.com)"
        },
        "GitHub Copilot": {
            "Description": "Developer Assistant to write code and solve issues, faster",
            "Features": [
                "Suggests individual lines and whole functions instantly",
                "Powered by a generative AI model developed by GitHub, OpenAI, and Microsoft"
            ],
            "Representatives": ["Artika Narayan", "Glen Kennedy"]
        },
        "GenAI Claims assistant": {
            "Description": "Improved employee and customer experience in claims handling",
            "Functionality": "Claims Agent asks questions and CASI provides answers from relevant Product Disclosure Statements and policy documents",
            "Scope": "Now extended to Property and Motor Claims",
            "Representatives": ["Anna Coticchio", "MICHAEL LO1"]
        },
        "New Relic AI": {
            "Description": "Observability Assistant",
            "Purpose": "Designed to help every team member improve observability, not just engineers",
            "Integration": "Combines OpenAI's large language models (LLMs) with unified telemetry data platform",
            "Representatives": ["Lee McRae", "Shefali Varma", "Anuj Kumar"]
        }
    },
    "Other Pilots": {
        "Copilot for M365": {
            "Description": "Gen AI within the Microsoft apps",
            "Details": "Embedded in Microsoft 365 apps such as Teams, Outlook, Word & PowerPoint, connected to Microsoft data",
            "Status": "Early Adopter Program with 300 Early Adopters currently using the tool",
            "Representatives": ["Daniel Egan", "Duane Herring"]
        },
        "Generative AI Agent Builder": {
            "Description": "Build safe, reusable GAI agents, anchored in our data to automate tasks",
            "Applications": [
                "Content centre script creation",
                "Marketing content creation",
                "Customer response editing"
            ],
            "Resources": "Check out or add your use case here - LUMI Use Cases - Strategy & Innovation - Analytics - Confluence (atlassian.net)",
            "Representatives": ["Ehsan Mazloumi", "Omid Karr"]
        },
        "Gemini": {
            "Description": "Generative AI Assistant across Google Cloud Platform",
            "Purpose": "Increase productivity and efficiency in data engineering, data analysis, and platform security and operations workflows",
            "Technology": "Powered by generative AI models from Google",
            "Representatives": ["Burak Hoban", "Omid Karr"]
        },
        "Knowledge Assist": {
            "Description": "Improve the quality and search & retrieval of knowledge articles",
            "Purpose": "Increase productivity and efficiency in service and claims knowledge by quickly accessing and improving the quality of knowledge articles",
            "Representatives": ["Omid Karr", "Ehsan Mazloumi"]
        },
        "ARKI ArchAssist": {
            "Description": "Improve the quality and efficiency of developing IT artefacts and assessments",
            "Usage": "Used to create draft artefacts for IT Assessments and understanding",
            "Representative": "Kirit Kundu"
        }
    },
    "More PoCs being added": [
        {"Fraud GenAI": "POC in IIA"},
        {"Knowledge GenAI": "POC in IIA"},
        {"Data-mapping for long-term archiving of legacy systems": "POC in T&O"},
        {"Image recognition for Fraud": "POC in RIA"},
        {"CTP GenAI": "At discovery stage - RIA and T&O"},
        {"CASI for NZ Claims": "In discovery stage"},
        {"GenAI for NZ Homehub": "POC completed"},
        {"Fraud GenAI monitoring and alerts": None},
        {"SVx GenAI bot POC": "Enable querying SVx data using natural language"}
    ]
}
```

This dictionary organizes the content into three main sections: "Live Uses," "Other Pilots," and "More PoCs being added." Each section contains structured information about the various AI initiatives, including descriptions, purposes, features, status, and representatives when provided.
Total Tokens : 1886

In [17]:
p2 = """
Convert following text into a usable xml file format. 

# Operational efficiency​
    # performing current workflows with less cost, more accuracy​
    # e.g. claim processing, supplier onboarding​
# Customer value​
    # improving customer experience, customer service, and increasing personalisation​
    # e.g. personalised chat bots and communication mails.​
# Competitive advantage​
    # new products and services that differentiate from competitors​
    # e.g. customised advice in an app.​
# Decision intelligence and reporting​
    # support strategic choices with data-driven insights and creation of reporting​
    # e.g. creation of executive summaries.​
# Tech Development & Operations​
    # accelerating the creation and maintenance of software and IT infrastructure by developing code, test scripts, insights​
    # e.g. creating prototype code or assisting in troubleshooting bugs.​
# Creative Design ​
    # supporting the creation and consistency of visual and creative elements​
    # e.g. producing content for websites, suggesting complementary images​
# Strategic planning and risk management​
    # enhancing the ability to anticipate and prepare for scenarios and potential risks​
    # e.g. scenario planning for disasters or significant events.​
# Team success and effectiveness​
    # team communications, knowledge management, onboarding, training team​
    # e.g. creating customised onboarding packs based on current policy documents​
"""

with get_openai_callback() as cb:
    model = get_azure_openai(temperature=1.0)
    print(model.invoke(p2).content)
    print(f"Total Tokens : {cb.total_tokens}")

Below is the text converted into an XML file format. XML is a markup language that defines a set of rules for encoding documents in a format that is both human-readable and machine-readable. The structure of an XML document should reflect the hierarchical nature of the data it contains.

```xml
<?xml version="1.0" encoding="UTF-8"?>
<BusinessFocusAreas>
    <OperationalEfficiency>
        <Description>performing current workflows with less cost, more accuracy</Description>
        <Examples>
            <Example>claim processing</Example>
            <Example>supplier onboarding</Example>
        </Examples>
    </OperationalEfficiency>
    <CustomerValue>
        <Description>improving customer experience, customer service, and increasing personalisation</Description>
        <Examples>
            <Example>personalised chat bots</Example>
            <Example>communication mails</Example>
        </Examples>
    </CustomerValue>
    <CompetitiveAdvantage>
        <Description>new products and services that differentiate from competitors</Description>
        <Examples>
            <Example>customised advice in an app</Example>
        </Examples>
    </CompetitiveAdvantage>
    <DecisionIntelligenceAndReporting>
        <Description>support strategic choices with data-driven insights and creation of reporting</Description>
        <Examples>
            <Example>creation of executive summaries</Example>
        </Examples>
    </DecisionIntelligenceAndReporting>
    <TechDevelopmentAndOperations>
        <Description>accelerating the creation and maintenance of software and IT infrastructure by developing code, test scripts, insights</Description>
        <Examples>
            <Example>creating prototype code</Example>
            <Example>assisting in troubleshooting bugs</Example>
        </Examples>
    </TechDevelopmentAndOperations>
    <CreativeDesign>
        <Description>supporting the creation and consistency of visual and creative elements</Description>
        <Examples>
            <Example>producing content for websites</Example>
            <Example>suggesting complementary images</Example>
        </Examples>
    </CreativeDesign>
    <StrategicPlanningAndRiskManagement>
        <Description>enhancing the ability to anticipate and prepare for scenarios and potential risks</Description>
        <Examples>
            <Example>scenario planning for disasters or significant events</Example>
        </Examples>
    </StrategicPlanningAndRiskManagement>
    <TeamSuccessAndEffectiveness>
        <Description>team communications, knowledge management, onboarding, training team</Description>
        <Examples>
            <Example>creating customised onboarding packs based on current policy documents</Example>
        </Examples>
    </TeamSuccessAndEffectiveness>
</BusinessFocusAreas>
```

This XML document contains a root element `<BusinessFocusAreas>` which encapsulates different business focus areas as child elements. Each focus area contains a `<Description>` and a set of `<Examples>` with individual `<Example>` elements. This structure allows for easy parsing and extraction of information for each business focus area.
Total Tokens : 920

In [4]:

p3 = """
provide a project plan for 1.5 months for the following GenAI project.
Project details are as follows : 
1) project involves building a GenAI assistant, for Executive managers, to help them make annual strategic plans.
2) the AI tool will have tentatively 4 major segments (input plan, discover value areas, recommend responsible use guidelines, suggest AI tech enablement plan)
3) stakeholders include 2 client leaders : cto, program lead, and 2 working resources : sr. data scientist, sr. front end dveloper
4) there is supposed to be weekly meeting with the 2 client leaders for feedback and iterations
5) majority of the flow is undecided and experimental. what starts with a single prompt for each segment might convert into a multi-step prompting for every segment.

Use best project management guidelines and theory to create a suitable formal project plan for this project.
"""
with get_openai_callback() as cb:
    model = get_azure_openai(temperature=1.0)
    print(model.invoke(p3).content)
    print(f"Total Tokens : {cb.total_tokens}")

Creating a project plan for the GenAI assistant involves defining the scope, objectives, deliverables, milestones, and tasks. Given the experimental nature of the project, the plan should be flexible and iterative, incorporating Agile methodologies. Here's a high-level project plan for the 1.5-month timeline:

**Week 1: Project Initiation and Planning**

- **Day 1-2: Kick-off Meeting**
  - Gather all stakeholders for an initial meeting.
  - Define project vision, objectives, and scope.
  - Discuss the roles and responsibilities of each team member.

- **Day 3-5: Project Planning**
  - Develop a project charter and detailed project plan.
  - Establish communication protocols for weekly meetings and updates.
  - Create a risk management plan.
  - Set up project management tools (e.g., JIRA, Trello).

**Week 2-3: Requirements Gathering and Design**

- **Week 2: Requirements Workshops**
  - Conduct workshops with client leaders to understand their needs.
  - Define the requirements for each of the four segments of the GenAI assistant.
  - Start developing user stories and use cases.

- **Week 3: High-Level Design**
  - Create high-level design documents for the AI assistant.
  - Define the technology stack and architecture.
  - Develop a prototype for the input plan segment.

**Week 4-5: Development Sprints**

- **Week 4: Sprint 1**
  - Develop the 'input plan' and 'discover value areas' segments.
  - Begin weekly meetings with client leaders for feedback.
  - Implement feedback loops and iterative development.

- **Week 5: Sprint 2**
  - Refine the first two segments based on feedback.
  - Start development on the 'recommend responsible use guidelines' segment.
  - Continue weekly feedback sessions.

**Week 6: Development and Testing**

- **Week 6: Sprint 3**
  - Develop the 'suggest AI tech enablement plan' segment.
  - Conduct integration testing for all segments.
  - Prepare for user acceptance testing (UAT).

**Week 7: UAT and Iterations**

- **Week 7: User Acceptance Testing**
  - Conduct UAT with client leaders and gather feedback.
  - Make necessary adjustments based on UAT results.
  - Begin preparing for deployment.

**Week 8: Deployment and Project Closure**

- **Week 8: Deployment**
  - Deploy the GenAI assistant in the client's environment.
  - Conduct training sessions for executive managers.
  - Monitor the system and provide support.

- **Project Closure**
  - Document lessons learned and best practices.
  - Conduct a project retrospective with the team.
  - Finalize all project documentation.
  - Officially close the project and release resources.

**Deliverables:**

- Project Charter
- Detailed Project Plan
- Risk Management Plan
- High-Level Design Documents
- Developed AI Assistant Segments
- Integration Testing Report
- UAT Report
- Deployment Guide
- Training Materials
- Project Closure Report

**Milestones:**

- End of Week 1: Project Charter and Plan Finalized
- End of Week 3: High-Level Design Completed
- End of Week 5: First Two Segments Developed and Tested
- End of Week 6: All Segments Developed and Integrated
- End of Week 7: UAT Completed and Adjustments Made
- End of Week 8: Deployment and Project Closure

**Communication Plan:**

- Weekly meetings with client leaders for project updates and feedback.
- Daily stand-ups with the development team to discuss progress and impediments.
- Use of a project management tool for tracking tasks and progress.
- Email updates after each significant milestone.

**Risk Management:**

- Regularly review and update the risk management plan.
- Proactively identify potential risks and develop mitigation strategies.
- Maintain open communication channels for reporting and addressing issues promptly.

Given the experimental nature of the project, the plan should remain flexible, with room for adjustments based on stakeholder feedback and project discoveries. Agile methodologies will be crucial to accommodate the evolving requirements and iterative development process.
Total Tokens : 1041

In [6]:
p4 = """
**Week 1: Project Initiation and Planning**

- **Day 1-2: Kick-off Meeting**
  - Gather all stakeholders for an initial meeting.
  - Define project vision, objectives, and scope.
  - Discuss the roles and responsibilities of each team member.

- **Day 3-5: Project Planning**
  - Develop a project charter and detailed project plan.
  - Establish communication protocols for weekly meetings and updates.
  - Create a risk management plan.
  - Set up project management tools (e.g., JIRA, Trello).

**Week 2-3: Requirements Gathering and Design**

- **Week 2: Requirements Workshops**
  - Conduct workshops with client leaders to understand their needs.
  - Define the requirements for each of the four segments of the GenAI assistant.
  - Start developing user stories and use cases.

- **Week 3: High-Level Design**
  - Create high-level design documents for the AI assistant.
  - Define the technology stack and architecture.
  - Develop a prototype for the input plan segment.

**Week 4-5: Development Sprints**

- **Week 4: Sprint 1**
  - Develop the 'input plan' and 'discover value areas' segments.
  - Begin weekly meetings with client leaders for feedback.
  - Implement feedback loops and iterative development.

- **Week 5: Sprint 2**
  - Refine the first two segments based on feedback.
  - Start development on the 'recommend responsible use guidelines' segment.
  - Continue weekly feedback sessions.

**Week 6: Development and Testing**

- **Week 6: Sprint 3**
  - Develop the 'suggest AI tech enablement plan' segment.
  - Conduct integration testing for all segments.
  - Prepare for user acceptance testing (UAT).

**Week 7: UAT and Iterations**

- **Week 7: User Acceptance Testing**
  - Conduct UAT with client leaders and gather feedback.
  - Make necessary adjustments based on UAT results.
  - Begin preparing for deployment.

**Week 8: Deployment and Project Closure**

- **Week 8: Deployment**
  - Deploy the GenAI assistant in the client's environment.
  - Conduct training sessions for executive managers.
  - Monitor the system and provide support.

- **Project Closure**
  - Document lessons learned and best practices.
  - Conduct a project retrospective with the team.
  - Finalize all project documentation.
  - Officially close the project and release resources.

**Deliverables:**

- Project Charter
- Detailed Project Plan
- Risk Management Plan
- High-Level Design Documents
- Developed AI Assistant Segments
- Integration Testing Report
- UAT Report
- Deployment Guide
- Training Materials
- Project Closure Report

**Milestones:**

- End of Week 1: Project Charter and Plan Finalized
- End of Week 3: High-Level Design Completed
- End of Week 5: First Two Segments Developed and Tested
- End of Week 6: All Segments Developed and Integrated
- End of Week 7: UAT Completed and Adjustments Made
- End of Week 8: Deployment and Project Closure

**Communication Plan:**

- Weekly meetings with client leaders for project updates and feedback.
- Daily stand-ups with the development team to discuss progress and impediments.
- Use of a project management tool for tracking tasks and progress.
- Email updates after each significant milestone.

**Risk Management:**

- Regularly review and update the risk management plan.
- Proactively identify potential risks and develop mitigation strategies.
- Maintain open communication channels for reporting and addressing issues promptly.

Given the experimental nature of the project, the plan should remain flexible, with room for adjustments based on stakeholder feedback and project discoveries. Agile methodologies will be crucial to accommodate the evolving requirements and iterative development process.
"""

In [8]:
p5 = f""" \nhuman : {p3} \n\n :: Assistant : {p4} :: \n\n human : Can you give an example of charter & plans """

In [10]:
with get_openai_callback() as cb:
    model = get_azure_openai(temperature=1.0)
    print(model.invoke(p5).content)
    print(f"Total Tokens : {cb.total_tokens}")

Certainly! Below are examples of a project charter and a high-level project plan for the GenAI project. These are simplified and would need to be expanded upon with more specific details relevant to the actual project environment.

**Project Charter Example for GenAI Project**

**Project Title:** GenAI Assistant Development for Executive Managers

**Project Start Date:** April 1, 2023

**Project End Date:** May 15, 2023

**Project Manager:** [Project Manager's Name]

**Project Objectives:**
- To develop a GenAI assistant that aids executive managers in making annual strategic plans.
- To create an AI tool with four major segments: input plan, discover value areas, recommend responsible use guidelines, and suggest AI tech enablement plan.

**Scope:**
- The project will encompass the design, development, testing, and deployment of the GenAI assistant.
- The project will not include ongoing maintenance post-deployment within the scope of this project phase.

**Stakeholders:**
- CTO (Client Leader)
- Program Lead (Client Leader)
- Senior Data Scientist (Working Resource)
- Senior Front End Developer (Working Resource)

**Deliverables:**
- Project Plan
- Risk Management Plan
- High-Level Design Documents
- Developed AI Assistant Segments
- Testing and UAT Reports
- Deployment Guide and Training Materials
- Project Closure Report

**High-Level Milestones:**
- Project Planning Completion: April 7, 2023
- High-Level Design Completion: April 21, 2023
- Development Completion: May 5, 2023
- UAT and Final Adjustments: May 12, 2023
- Deployment and Project Closure: May 15, 2023

**Budget:**
- [Include a high-level budget, breaking down costs associated with resources, tools, and any other expenses.]

**Assumptions and Risks:**
- Assumption: Stakeholders will be available for weekly meetings.
- Risk: Changes in project scope could lead to delays.

**Approval Signatures:**
- [Project Manager's Name & Signature]
- [CTO's Name & Signature]
- [Program Lead's Name & Signature]

**Project Plan Example for GenAI Project**

**1. Project Initiation:**
- Define project objectives, scope, and deliverables.
- Identify project team and assign roles and responsibilities.
- Develop project charter and secure approvals.

**2. Project Planning:**
- Create a detailed project plan, including timelines for each phase.
- Establish a communication plan for stakeholder engagement.
- Develop a risk management plan with mitigation strategies.

**3. Requirements Gathering:**
- Conduct workshops with stakeholders to gather detailed requirements.
- Document and prioritize requirements.
- Develop user stories and use cases for each segment of the AI assistant.

**4. Design and Prototyping:**
- Create high-level design documents outlining the system architecture.
- Develop a prototype for initial segment(s) to validate concepts.

**5. Development Sprints:**
- Organize work into sprints, focusing on one segment at a time.
- Conduct regular sprint reviews with stakeholders for feedback.
- Implement changes based on feedback.

**6. Testing and UAT:**
- Perform integration testing to ensure all segments work together seamlessly.
- Conduct User Acceptance Testing with stakeholders.
- Document feedback and make necessary adjustments.

**7. Deployment:**
- Finalize deployment plans and train end-users.
- Deploy the GenAI assistant in the production environment.
- Monitor deployment and address any immediate issues.

**8. Project Closure:**
- Document lessons learned and gather final project metrics.
- Prepare and distribute the project closure report.
- Officially close the project and release resources.

Each of these documents would be further detailed and tailored to the specific needs and context of the project, including more granular tasks, dependencies, resource allocations, and timelines.
Total Tokens : 1794

In [12]:
p6 = """
Go through the code in this public githubrepo , https://github.com/abdulValeed1/AI-AGI ,
Identify the block of code that renders the first page of "Fill Details" and asks for "Priority Outcome, Measurable Target and Risks & Dependencies" in the form, under a subheading "Add Focus Area".
Show me the current block of code that does this and then provide an alternate code block , with comments, that now takes in 4 fields instead of earlier 3, the 4th field being "Focus_area_name" 
"""

In [13]:
with get_openai_callback() as cb:
    model = get_azure_openai(temperature=1.0)
    print(model.invoke(p6).content)
    print(f"Total Tokens : {cb.total_tokens}")

As an AI developed by OpenAI, I don't have the capability to directly browse the internet or access external content such as GitHub repositories. However, I can guide you on how to find the code block you're looking for and provide you with an example of how you might modify it to include an additional field.

To find the code block that renders the first page of "Fill Details" with the fields "Priority Outcome, Measurable Target, and Risks & Dependencies," you would typically look for a file that handles form rendering. This could be a HTML file, a template file (like a `.ejs`, `.pug`, or `.hbs` file if it's a Node.js project), or a component file (like a `.jsx` or `.tsx` file if it's a React project).

Once you've found the form in the code, it might look something like this (in a hypothetical React component):

```jsx
import React from 'react';

class FocusAreaForm extends React.Component {
  // ... other component logic

  render() {
    return (
      <div>
        <h2>Add Focus Area</h2>
        <form>
          <label>
            Priority Outcome:
            <input type="text" name="priorityOutcome" />
          </label>
          <label>
            Measurable Target:
            <input type="text" name="measurableTarget" />
          </label>
          <label>
            Risks & Dependencies:
            <input type="text" name="risksDependencies" />
          </label>
          <button type="submit">Submit</button>
        </form>
      </div>
    );
  }
}

export default FocusAreaForm;
```

To add a fourth field called "Focus_area_name," you would modify the form to include the new field like so:

```jsx
import React from 'react';

class FocusAreaForm extends React.Component {
  // ... other component logic

  render() {
    return (
      <div>
        <h2>Add Focus Area</h2>
        <form>
          <label>
            Focus Area Name: {/* New field for Focus Area Name */}
            <input type="text" name="focusAreaName" />
          </label>
          <label>
            Priority Outcome:
            <input type="text" name="priorityOutcome" />
          </label>
          <label>
            Measurable Target:
            <input type="text" name="measurableTarget" />
          </label>
          <label>
            Risks & Dependencies:
            <input type="text" name="risksDependencies" />
          </label>
          <button type="submit">Submit</button>
        </form>
      </div>
    );
  }
}

export default FocusAreaForm;
```

In the above code, I've added a new `label` and `input` element for the "Focus Area Name." This assumes that the backend or the state management is also updated to handle the new field.

Remember, the actual code you need to modify will depend on the specific technologies and architecture used in the repository you're working with. You'll need to adjust the example I provided to fit the actual codebase.
Total Tokens : 780

#### in line Chat

In [19]:
!pip install ipywidgets

Collecting ipywidgets
  Downloading ipywidgets-8.1.5-py3-none-any.whl.metadata (2.3 kB)
Requirement already satisfied: comm>=0.1.3 in /Users/s748779/IAG_test/test1/lib/python3.9/site-packages (from ipywidgets) (0.2.2)
Requirement already satisfied: ipython>=6.1.0 in /Users/s748779/IAG_test/test1/lib/python3.9/site-packages (from ipywidgets) (8.18.1)
Requirement already satisfied: traitlets>=4.3.1 in /Users/s748779/IAG_test/test1/lib/python3.9/site-packages (from ipywidgets) (5.14.3)
Collecting widgetsnbextension~=4.0.12 (from ipywidgets)
  Downloading widgetsnbextension-4.0.13-py3-none-any.whl.metadata (1.6 kB)
Collecting jupyterlab-widgets~=3.0.12 (from ipywidgets)
  Downloading jupyterlab_widgets-3.0.13-py3-none-any.whl.metadata (4.1 kB)
Requirement already satisfied: decorator in /Users/s748779/IAG_test/test1/lib/python3.9/site-packages (from ipython>=6.1.0->ipywidgets) (5.1.1)
Requirement already satisfied: jedi>=0.16 in /Users/s748779/IAG_test/test1/lib/python3.9/site-packages (from ipython>=6.1.0->ipywidgets) (0.19.1)
Requirement already satisfied: matplotlib-inline in /Users/s748779/IAG_test/test1/lib/python3.9/site-packages (from ipython>=6.1.0->ipywidgets) (0.1.7)
Requirement already satisfied: prompt-toolkit<3.1.0,>=3.0.41 in /Users/s748779/IAG_test/test1/lib/python3.9/site-packages (from ipython>=6.1.0->ipywidgets) (3.0.45)
Requirement already satisfied: pygments>=2.4.0 in /Users/s748779/IAG_test/test1/lib/python3.9/site-packages (from ipython>=6.1.0->ipywidgets) (2.18.0)
Requirement already satisfied: stack-data in /Users/s748779/IAG_test/test1/lib/python3.9/site-packages (from ipython>=6.1.0->ipywidgets) (0.6.3)
Requirement already satisfied: typing-extensions in /Users/s748779/IAG_test/test1/lib/python3.9/site-packages (from ipython>=6.1.0->ipywidgets) (4.12.0)
Requirement already satisfied: exceptiongroup in /Users/s748779/IAG_test/test1/lib/python3.9/site-packages (from ipython>=6.1.0->ipywidgets) (1.2.1)
Requirement already satisfied: pexpect>4.3 in /Users/s748779/IAG_test/test1/lib/python3.9/site-packages (from ipython>=6.1.0->ipywidgets) (4.9.0)
Requirement already satisfied: parso<0.9.0,>=0.8.3 in /Users/s748779/IAG_test/test1/lib/python3.9/site-packages (from jedi>=0.16->ipython>=6.1.0->ipywidgets) (0.8.4)
Requirement already satisfied: ptyprocess>=0.5 in /Users/s748779/IAG_test/test1/lib/python3.9/site-packages (from pexpect>4.3->ipython>=6.1.0->ipywidgets) (0.7.0)
Requirement already satisfied: wcwidth in /Users/s748779/IAG_test/test1/lib/python3.9/site-packages (from prompt-toolkit<3.1.0,>=3.0.41->ipython>=6.1.0->ipywidgets) (0.2.13)
Requirement already satisfied: executing>=1.2.0 in /Users/s748779/IAG_test/test1/lib/python3.9/site-packages (from stack-data->ipython>=6.1.0->ipywidgets) (2.0.1)
Requirement already satisfied: asttokens>=2.1.0 in /Users/s748779/IAG_test/test1/lib/python3.9/site-packages (from stack-data->ipython>=6.1.0->ipywidgets) (2.4.1)
Requirement already satisfied: pure-eval in /Users/s748779/IAG_test/test1/lib/python3.9/site-packages (from stack-data->ipython>=6.1.0->ipywidgets) (0.2.2)
Requirement already satisfied: six>=1.12.0 in /Users/s748779/IAG_test/test1/lib/python3.9/site-packages (from asttokens>=2.1.0->stack-data->ipython>=6.1.0->ipywidgets) (1.16.0)
Downloading ipywidgets-8.1.5-py3-none-any.whl (139 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 139.8/139.8 kB 2.8 MB/s eta 0:00:00 MB/s eta 0:00:01
Downloading jupyterlab_widgets-3.0.13-py3-none-any.whl (214 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 214.4/214.4 kB 3.0 MB/s eta 0:00:00[31m3.4 MB/s eta 0:00:01
Downloading widgetsnbextension-4.0.13-py3-none-any.whl (2.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.3/2.3 MB 4.3 MB/s eta 0:00:00 MB/s eta 0:00:01:01
Installing collected packages: widgetsnbextension, jupyterlab-widgets, ipywidgets
Successfully installed ipywidgets-8.1.5 jupyterlab-widgets-3.0.13 widgetsnbextension-4.0.13

[notice] A new release of pip is available: 24.0 -> 24.2
[notice] To update, run: pip install --upgrade pip

Text(value='', placeholder='Enter your query...')

Button(description='Send', style=ButtonStyle())

In [ ]:
while True:
    get_prompt = input("Give the input prompt here: ")
    with get_openai_callback() as cb:
        model = get_azure_openai(temperature=1.0)
        response = model.invoke(get_prompt).content
        print(response)
        print(f"Total Tokens : {cb.total_tokens}")

    exit_q = input("Want to Exit? y / n : ")
    if exit_q == 'y' or exit_q == 'Y':
        print("Thanks for spending time with me")
        break

Give the input prompt here:  I have the following XML file:  <?xml version="1.0" encoding="UTF-8"?> <BusinessFocusAreas>     <OperationalEfficiency>         <Description>performing current workflows with less cost, more accuracy</Description>         <Examples>             <Example>claim processing</Example>             <Example>supplier onboarding</Example>         </Examples>     </OperationalEfficiency>     <CustomerValue>         <Description>improving customer experience, customer service, and increasing personalisation</Description>         <Examples>             <Example>personalised chat bots</Example>             <Example>communication mails</Example>         </Examples>     </CustomerValue>     <CompetitiveAdvantage>         <Description>new products and services that differentiate from competitors</Description>         <Examples>             <Example>customised advice in an app</Example>         </Examples>     </CompetitiveAdvantage>     <DecisionIntelligenceAndReporting>         <Description>support strategic choices with data-driven insights and creation of reporting</Description>         <Examples>             <Example>creation of executive summaries</Example>         </Examples>     </DecisionIntelligenceAndReporting>     <TechDevelopmentAndOperations>         <Description>accelerating the creation and maintenance of software and IT infrastructure by developing code, test scripts, insights</Description>         <Examples>             <Example>creating prototype code</Example>             <Example>assisting in troubleshooting bugs</Example>         </Examples>     </TechDevelopmentAndOperations>     <CreativeDesign>         <Description>supporting the creation and consistency of visual and creative elements</Description>         <Examples>             <Example>producing content for websites</Example>             <Example>suggesting complementary images</Example>         </Examples>     </CreativeDesign>     <StrategicPlanningAndRiskManagement>         <Description>enhancing the ability to anticipate and prepare for scenarios and potential risks</Description>         <Examples>             <Example>scenario planning for disasters or significant events</Example>         </Examples>     </StrategicPlanningAndRiskManagement>     <TeamSuccessAndEffectiveness>         <Description>team communications, knowledge management, onboarding, training team</Description>         <Examples>             <Example>creating customised onboarding packs based on current policy documents</Example>         </Examples>     </TeamSuccessAndEffectiveness> </BusinessFocusAreas> can you write the code to neatly read this xml and use it in the form of python dict or suitable datatype?

Certainly! To read the XML file and convert it into a Python dictionary, you can use the `xml.etree.ElementTree` module which is a part of the standard library in Python. Below is a sample code that does this:

```python
import xml.etree.ElementTree as ET

# Function to parse XML into a dictionary
def xml_to_dict(element):
    # Base case: if the element has no subelements, return its text
    if not list(element):
        return element.text.strip() if element.text else None

    # Recursive case: build a dictionary from subelements
    return {subelement.tag: xml_to_dict(subelement) for subelement in element}

# Read the XML file
xml_data = '''<?xml version="1.0" encoding="UTF-8"?>
<BusinessFocusAreas>
    <!-- Your XML content here -->
</BusinessFocusAreas>'''

# Parse the XML data
root = ET.fromstring(xml_data)

# Convert the XML tree into a dictionary
business_focus_areas_dict = xml_to_dict(root)

# Print the resulting dictionary
print(business_focus_areas_dict)
```

Make sure to replace the `<!-- Your XML content here -->` comment with your actual XML content. This script will parse the XML content and convert it into a nested dictionary structure, where each XML tag becomes a key in the dictionary.

Please note that this script assumes that the XML structure is such that each child element has a unique tag name within its parent. If there are multiple child elements with the same tag name (like multiple `<Example>` tags), you may need to modify the function to handle lists appropriately.

Here's how you might modify the `xml_to_dict` function to handle multiple elements with the same tag name:

```python
def xml_to_dict(element):
    # Base case: if the element has no subelements, return its text
    if not list(element):
        return element.text.strip() if element.text else None

    # Recursive case: build a dictionary or list from subelements
    result = {}
    for subelement in element:
        sub_dict = xml_to_dict(subelement)
        if subelement.tag in result:
            # If the tag is already in the dictionary, append to the list
            if not isinstance(result[subelement.tag], list):
                # Convert to list if it's the first duplicate
                result[subelement.tag] = [result[subelement.tag]]
            result[subelement.tag].append(sub_dict)
        else:
            # Otherwise, just add the sub_dict to the result
            result[subelement.tag] = sub_dict
    return result
```

This modified function will create a list for any tag that appears multiple times within the same parent element. This is necessary for tags like `<Example>` which can occur multiple times within `<Examples>`.
Total Tokens : 1110

Want to Exit? y / n :  n

### Direct connection to Sharepoint

In [10]:
!pip install sharepy==2.0.0b1.post2

Collecting sharepy==2.0.0b1.post2
  Downloading sharepy-2.0.0b1.post2.tar.gz (11 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: requests<3,>=2 in /Users/s748779/IAG_test/test1/lib/python3.9/site-packages (from sharepy==2.0.0b1.post2) (2.32.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /Users/s748779/IAG_test/test1/lib/python3.9/site-packages (from requests<3,>=2->sharepy==2.0.0b1.post2) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /Users/s748779/IAG_test/test1/lib/python3.9/site-packages (from requests<3,>=2->sharepy==2.0.0b1.post2) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Users/s748779/IAG_test/test1/lib/python3.9/site-packages (from requests<3,>=2->sharepy==2.0.0b1.post2) (2.2.1)
Requirement already satisfied: certifi>=2017.4.17 in /Users/s748779/IAG_test/test1/lib/python3.9/site-packages (from requests<3,>=2->sharepy==2.0.0b1.post2) (2024.2.2)
Building wheels for collected packages: sharepy
  Building wheel for sharepy (pyproject.toml) ... done
  Created wheel for sharepy: filename=sharepy-2.0.0b1.post2-py3-none-any.whl size=13736 sha256=37a3c2dc8601005fc4c9b25857d16aff8a6dddbdf815c546e12552d41cc25350
  Stored in directory: /Users/s748779/Library/Caches/pip/wheels/5e/2b/c4/d4ff2b5c210000e554c4ad2da890d502d219c08d1eaa36052a
Successfully built sharepy
Installing collected packages: sharepy
Successfully installed sharepy-2.0.0b1.post2

[notice] A new release of pip is available: 24.0 -> 24.2
[notice] To update, run: pip install --upgrade pip

In [11]:
import sharepy
s = sharepy.connect("iagau.sharepoint.com")

Enter your username:  vikesh.morye@iag.com.au
Enter your password:  ········

AuthError: Authentication Failure: AADSTS53003: Access has been blocked by Conditional Access policies. The access policy does not allow token issuance

In [ ]:
# Access blocked

# Public GPT key

In [15]:
from openai import OpenAI
import os

OPENAI_API_KEY="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" 
os.environ['OPENAI_API_KEY'] = OPENAI_API_KEY


# Initialize OpenAI client
client = OpenAI(api_key=os.getenv('OPENAI_API_KEY'))


def get_response_from_llm(prompt, model="gpt-4o", max_tokens=1000, temperature=0):
    response = client.chat.completions.create(
        model=model,
        messages=[
            {"role": "system", "content": "You are an assistant."},
            {"role": "user", "content": prompt}
        ],
        max_tokens=max_tokens,
        temperature=temperature
    )

    # To access the completion text:
    return response, response.choices[0].message.content.strip()

In [16]:
r, c = get_response_from_llm("IS THIS WORKING?")
print(r, c)

PermissionDeniedError: <head>
    <meta name="referrer" content="no-referrer">
</head>
<script>
window.onload = function() {
    // modal style
var css = '\
  .ns-template-wrap { \
     z-index: 2; \
     font-size: 12px; \
     background: #ffffff; \
     line-height: 16px; \
     color: #646464; \
     border-top: 8px solid transparent; \
     padding: 24px 32px 32px; \
     font-family: Lato, sans-serif; \
  } \
  .ns-template-inner-wrap { \
     width: 600px; \
     margin: 0 auto; \
  } \
  .ns-template-wrap * { \
     box-sizing: border-box; \
  } \
  .ns-template-wrap h1 { \
     margin-top: 0; \
     color: #000000; \
     font-size: 20px; \
     line-height: 24px; \
     font-weight: normal; \
     margin-bottom: 16px; \
  } \
  .ns-template-wrap h2 { \
     margin-top: 0; \
     color: #000000; \
     font-size: 14px; \
     line-height: 20px; \
     font-weight: normal; \
     margin-bottom: 16px; \
  } \
  .ns-template-wrap p { \
     color: #646464; \
     font-size: 12px; \
     line-height: 16px; \
     margin-bottom: 24px; \
  } \
  .ns-template-wrap p.message-max-height { \
     max-height: 40vh; \
     overflow: auto; \
     word-wrap: break-word; \
     margin-bottom: 20px; \
  } \
  .ns-template-wrap fieldset { \
     margin: 0 0 12px 0; \
     padding: 0; \
     border: 0; \
  } \
  .ns-template-wrap fieldset label{ \
     margin: 0 0 8px 0; \
     padding: 0; \
     border: 0; \
     font-size: 14px; \
     line-height: 20px; \
     color: #000000; \
  } \
  .ns-template-wrap fieldset label::after{ \
     content: ""; \
     display: table; \
     width: 100%; \
     clear: both; \
  } \
  .ns-template-wrap fieldset label:last-of-type{ \
     margin-bottom: 0; \
  } \
  .ns-template-wrap .custom-logo { \
     margin-bottom: 24px; \
  } \
  .ns-template-wrap .custom-logo.small { \
     max-height: 48px; \
  } \
  .ns-template-wrap .custom-logo.medium { \
     max-height: 64px; \
  } \
  .ns-template-wrap .custom-logo.large { \
     max-height: 128px; \
  } \
  .ns-template-wrap textarea { \
     font-family: inherit; \
     padding: 8px 12px; \
     height: 80px; \
     width: 100% !important; \
     resize: none; \
     border: 1px solid #E1E1E1; \
     border-radius: 4px; \
     background-color: #FFFFFF; \
     color: #434343; \
     font-size: 13px; \
     line-height: 16px; \
  } \
  .ns-template-wrap button[disabled] { \
     background: #EEEEEE; \
     border-color: #E3E3E3; \
     color: #ccc; \
  } \
  .ns-template-wrap button { \
     height: auto; \
     min-width: 88px; \
     max-width: 160px; \
     overflow: hidden; \
     text-overflow: ellipsis; \
     padding: 8px 16px; \
     font-size: 12px; \
     font-weight: bold; \
     line-height: 16px; \
     text-align: center; \
     text-transform: uppercase; \
  } \
  .ns-template-wrap button.ns-btn-primary { \
     border: 1px solid #1BB7DF; \
     color: #FFFFFF; \
     border-radius: 4px; \
     background-color: #1BB7DF; \
  } \
  .ns-template-wrap button.ns-btn-cancel { \
     border: 1px solid #1BB7DF; \
     border-radius: 4px; \
     background-color: #FFFFFF; \
     color: #12A3D4; \
     margin-right: 8px; \
  }\
  .ns-user-justify-modal-wrap { \
      font-size: 14px; \
      color: #333333; \
      text-align: center; \
  } \
  .ns-user-justify-modal-backdrop { \
      position: fixed; \
      z-index: 1; \
      top: 0; \
      left: 0; \
      height: 100%; \
      width: 100%; \
      opacity: .6; \
      background: #000000; \
  } \
  .ns-user-justify-modal-wrap .modal-header { \
      min-height: 40px; \
      height: auto; \
      padding: 0; \
      background: #FFFFFF; \
      border-bottom: 0; \
  } \
  .ns-user-justify-modal-wrap .modal-header .modal-header { \
      padding: 0 0 24px 0; \
  } \
  .ns-user-justify-modal-wrap textarea { \
      font-size: inherit; \
      font-family: inherit; \
  } \
  .ns-user-justify-modal-wrap * { \
      box-sizing: border-box; \
  } \
  .ns-user-justify-modal { \
      position: relative; \
      display: inline-block; \
      z-index: 2; \
      padding: 72px 32px 0; \
      width: 100%; \
      max-width: 480px; \
      text-align: left; \
      border-radius: 2px; \
      background-color: #FFFFFF; \
      color: #242424; \
      font-family:Lato, Arial, sans-serif; \
      font-size: 14px; \
      line-height: 20px; \
  } \
  .ns-user-justify-modal h1 { \
      margin-top: 0; \
      color: #000100; \
      font-size: 20px; \
      line-height: 24px; \
      font-family:Lato, Arial, sans-serif; \
  } \
  .ns-user-justify-modal h2 { \
      margin-top: 0; \
      color: #000100; \
      font-size: 18px; \
      line-height: 24px; \
      font-family:Lato, Arial, sans-serif; \
  } \
  .ns-user-justify-modal h3 { \
      margin-top: 0; \
      color: #000100; \
      font-size: 16px; \
      line-height: 24px; \
      font-family:Lato, Arial, sans-serif; \
  } \
  .ns-user-justify-modal p { \
      margin: 24px 0; \
      color: #434343; \
      font-size: 12px; \
      line-height: 15px; \
      max-height: 150px; \
      overflow-y: auto; \
  } \
  .ns-user-justify-modal label { \
      display: block; \
      margin-right: .5em; \
  } \
  .ns-user-justify-modal fieldset { \
      margin: 1em 0 0; \
      padding: 0; \
      border: 0; \
  } \
  .ns-user-justify-modal .custom-logo { \
      position: absolute; \
      top: 24px; \
      left: 32px; \
      max-height: 60px; \
      max-width: 128px; \
  } \
  #ns-justify-description-box { \
      padding: .5em; \
      height: 7.5em; \
      width: 100% !important; \
      resize: none; \
      margin-bottom: 0; \
      border: 1px solid #E1E1E1; \
      border-radius: 4px; \
      background-color: #FFFFFF; \
      color: #9B9B9B; \
      font-size: 13px; \
      line-height: 16px; \
  } \
  .ns-user-justify-modal-wrap button[disabled] { \
      background: #EEEEEE; \
      border-color: #E3E3E3; \
      color: #ccc; \
  } \
  .ns-btn-group { \
      margin-top: 40px; \
      padding: 16px 0; \
      text-align: right; \
      position: relative; \
  } \
  .ns-btn-group:after { \
      content: ""; \
      background: #EEEEEE; \
      height: 1px; \
      width: calc(100% + 64px); \
      position: absolute; \
      top: 0; \
      left: -32px; \
  } \
  .ns-btn-group button { \
      height: auto; \
      min-width: 88px; \
      max-width: 160px; \
      overflow: hidden; \
      text-overflow: ellipsis; \
      padding: 8px 16px; \
      font-size: 12px; \
      font-weight: bold; \
      line-height: 16px; \
      text-align: center; \
      text-transform: uppercase; \
  } \
  .ns-btn-cancel { \
      border: 1px solid #1BB7DF; \
      border-radius: 4px; \
      background-color: #FFFFFF; \
      color: #1BB7DF; \
      float: left; \
  } \
  .ns-btn-primary { \
      color: #FFFFFF; \
      border-radius: 4px; \
      background-color: #1BB7DF; \
      border: 1px solid #1BB7DF; \
  } \
  .ns-btn-group.ns-no-border { \
      text-align: left; \
      padding: 0; \
      margin-top: 32px; \
  } \
  .ns-btn-group.ns-no-border:after { \
      background: transparent; \
  } \
  .ns-btn-group.ns-no-border .ns-btn-cancel { \
      margin-right: 8px; \
  } \
  .ns-user-justify-modal h4 { \
      margin-top:0; \
      margin-bottom:0; \
      color: #000100; \
      font-size: 20px; \
      line-height: 24px; \
      font-family:Lato, Arial, sans-serif; \
      font-weight:normal; \
  } \
  .ns-user-justify-modal h5 { \
      margin-top: 0; \
      margin-bottom: 0; \
      color: #434343; \
      font-size: 12px; \
      line-height: 16px; \
      font-family:Lato, Arial, sans-serif; \
      font-weight: normal; \
  } \
  .ns-form-input { \
      width: 280px; \
      border: 1px solid #E1E1E1; \
      border-radius: 4px; \
      background-color: #FFFFFF; \
      color: #9B9B9B; \
      font-family:Lato, Arial, sans-serif; \
      font-size: 13px; \
      line-height: 16px; \
      padding:8px 12px; \
      margin-top: 16px; \
      margin-bottom:0; \
  } \
  .ns-padding-none { \
      padding: 0 !important; \
  } \
  .ns-margin-none { \
      margin: 0 !important; \
  }';

var notify_css = document.createElement('style');
notify_css.innerHTML = css;
document.getElementsByTagName("head")[0].appendChild(notify_css);

function renderMessage(params) {
    /*
    // params comes from server
    // The top format is for rendering the justification html
    // and the bottom format is for rendering the block html.
    @params = {
    msg: (string),
    justify: (htmlString)
    } or
    @params = {
    rawmsg: (htmlString)
    }
     */
    var notify_modal_container = document.createElement('div');
    if (document.body) {
        document.body.appendChild(notify_modal_container);
    }
    // Display justification pages
    doc = window.document;

    notify_css = doc.createElement('style');
    notify_css.innerHTML = css;
    doc.getElementsByTagName("head")[0].appendChild(notify_css);

    doc.body.innerHTML = params.justify;
    doc.querySelector('.msg').innerHTML = params.msg;

    formData = {};
    var justifyForm = doc.querySelector('.ns-template-inner-wrap form');
    var descriptionField = doc.querySelector('#ns-justify-description');
    var descriptionFieldBox = doc.querySelector('#ns-justify-description-box');
    var justifySubmitBtns = justifyForm.querySelectorAll('.ns-submit');
    var justifyRadio = justifyForm.querySelector('#justify-usage-radio');
    var falsePositiveRadio = justifyForm.querySelector('#false-positive-radio');

    var justification_req = 1;
    _ns_justify_message_ = 1;
    _ns_url_ = justifyForm.getAttribute('action');

    var justifyFields = justifyForm.querySelectorAll('[name]');
    for (var i=0; i<justifyFields.length; i++) {
        var field = justifyFields[i];
        var key = field.getAttribute('name');
        if(key == 'msuid') {
            _ns_msuid_ = field.value;
            break;
        }
    }

    function disableSubmitBtns() {
        if (justifySubmitBtns.length == 2) {
            justifySubmitBtns[1].setAttribute('disabled', 'disabled');
        } else if (justifySubmitBtns.length == 1) {
            justifySubmitBtns[0].setAttribute('disabled', 'disabled');
        }
    }

    function enableSubmitBtns() {
        if (justifySubmitBtns.length == 2) {
            justifySubmitBtns[1].removeAttribute('disabled');
        } else if (justifySubmitBtns.length == 1) {
            justifySubmitBtns[0].removeAttribute('disabled');
        }
    }

    function validateForm() {
        if(params.force_justify == "false")
            return;

        if (!descriptionFieldBox || !justifySubmitBtns) {
            return;
        }
        if (justification_req == 1 && !descriptionFieldBox.value.length) {
            disableSubmitBtns();
        } else {
            if (justification_req == 1 &&
                descriptionFieldBox.value.length &&
                !descriptionFieldBox.value.match(/([^\u0000-\u007F]|\w)+/)) {
                disableSubmitBtns();
            } else {
                enableSubmitBtns();
            }
        }
    }

    function submitModal() {
        var justifyFields = justifyForm.querySelectorAll('[name]');
        var url = justifyForm.getAttribute('action');

        var cancel_button = 0;
        if(this.value == 'cancel')
            cancel_button = 1;

        var xhr = new XMLHttpRequest();
        xhr.open("POST", url, true);
        xhr.setRequestHeader('Content-Type', 'application/json');
        xhr.onreadystatechange = function () {
            if (xhr.readyState == 2) {
                if(cancel_button)
                    window.location = "/";
                else
                    document.location.reload();
            }
        }

        formData["justification_type"] = "justification";
        formData["_uj_category_id"] = "10158";
        formData["web_category"] = "10158";
        formData["policy"] = "Partner Trusted Blocked Categories";
        formData["_uj_dest_ip"] = "104.18.6.192";
        formData["uj_response_file_name"] = "";
        formData["app"] = "OpenAI";
        formData["from_user"] = "";
        formData["instance_id"] = "";
        for (var i=0; i<justifyFields.length; i++) {
            var field = justifyFields[i];
            var key = field.getAttribute('name');
            var value = field.value;
            if ((key == "justification_type") && (!field.checked)) {
                continue;
            }
            formData[key] = value;
        }

        if (this.value) {
            formData.submitId = this.value;
        } else {
            formData.submitId = 'cancel';
        }
        xhr.send(JSON.stringify(formData));
    }

    validateForm();
    // add events
    if (descriptionField) {
        descriptionField.addEventListener('input', validateForm);
    }

    if(justifyRadio) {
        justifyRadio.addEventListener('click', function() {
            descriptionField.style.display = 'block';
            justification_req = 1;
            validateForm();
        });
    }

    if(falsePositiveRadio) {
        falsePositiveRadio.addEventListener('click', function() {
            descriptionField.style.display = 'none';
            descriptionField.value = '';
            justification_req = 0;
            validateForm();
        });
    }

    for (var i=0; i<justifySubmitBtns.length; i++) {
        justifySubmitBtns[i].addEventListener('click', submitModal);
    }

    if (doc.querySelector('#ns-justify-description-box')) {
        var keydownfunc = function(e) {
            e.stopPropagation();
        }
        doc.querySelector('#ns-justify-description-box').addEventListener("keydown", keydownfunc, false);

        var keypressfunc = function(e) {
            e.stopPropagation();
        }
        doc.querySelector('#ns-justify-description-box').addEventListener("keypress", keypressfunc, false);
    }
    var_timeout = setTimeout(submitModal, 60000);
}

renderMessage({
    "msg" : "Your attempt to access this site has been restricted",
    "expire" : 600000,

### conversion codes

### Conversion code

In [2]:
import json

with open("../../react_ideation/mori/backend/jsons/gpt_output/suggested_va.json","r") as f1:
    input_data = json.load(f1)
with open("../../react_ideation/mori/backend/jsons/output/suggestion_output.json","r") as f2:
    output_data = json.load(f2)

In [3]:
input_data

{'strategy_linked_value_areas': ['Operational Efficiency',
  'Decision Intelligence And Reporting',
  'Technology Effectiveness',
  'Strategic Planning And Risk Management']}

In [4]:
output_data

[{'id': 1,
  'text': 'Operational Efficiency',
  'recommended': True,
  'question': 'Could you please provide a few examples of implementing operational efficiency?',
  'examples': ['Faster claim processing by a claims manager.',
   'Faster claim classification/segmentation by a claims manager.',
   'Quicker replies to positive emails by a sales manager.',
   'Faster conversions of meetings by a sales manager.'],
  'selected': False},
 {'id': 2,
  'text': 'Customer Value',
  'recommended': True,
  'question': 'Could you please provide a few examples of enhancing customer value?',
  'examples': ['Implementing customer feedback loops.',
   'Offering personalized experiences based on customer data.'],
  'selected': False},
 {'id': 3,
  'text': 'Competitive Advantage',
  'recommended': True,
  'question': 'Could you please provide a few examples of achieving competitive advantage?',
  'examples': ['Developing unique selling propositions in marketing.',
   'Leveraging exclusive partnerships.'],
  'selected': False},
 {'id': 4,
  'text': 'Innovation',
  'recommended': False,
  'question': 'Could you please provide a few examples of fostering innovation?',
  'examples': ['Encouraging employee-led brainstorming sessions.',
   'Investing in R&D for new technologies.'],
  'selected': False},
 {'id': 5,
  'text': 'Market Share',
  'recommended': False,
  'question': 'Could you please provide a few examples of increasing market share?',
  'examples': ['Launching targeted marketing campaigns.',
   'Offering competitive pricing strategies.'],
  'selected': False},
 {'id': 6,
  'text': 'Employee Satisfaction',
  'recommended': False,
  'question': 'Could you please provide a few examples of enhancing employee satisfaction?',
  'examples': ['Implementing flexible work arrangements.',
   'Conducting regular employee feedback surveys.'],
  'selected': False},
 {'id': 7,
  'text': 'Sustainability',
  'recommended': False,
  'question': 'Could you please provide a few examples of promoting sustainability?',
  'examples': ['Reducing carbon footprint in operations.',
   'Adopting sustainable sourcing practices.'],
  'selected': False}]

In [5]:
# Update the recommended key based on input data
for item in output_data:
    if item["text"] in input_data["strategy_linked_value_areas"]:
        item["recommended"] = True

# Print the updated output data
print(json.dumps(output_data, indent=4))

[
    {
        "id": 1,
        "text": "Operational Efficiency",
        "recommended": true,
        "question": "Could you please provide a few examples of implementing operational efficiency?",
        "examples": [
            "Faster claim processing by a claims manager.",
            "Faster claim classification/segmentation by a claims manager.",
            "Quicker replies to positive emails by a sales manager.",
            "Faster conversions of meetings by a sales manager."
        ],
        "selected": false
    },
    {
        "id": 2,
        "text": "Customer Value",
        "recommended": true,
        "question": "Could you please provide a few examples of enhancing customer value?",
        "examples": [
            "Implementing customer feedback loops.",
            "Offering personalized experiences based on customer data."
        ],
        "selected": false
    },
    {
        "id": 3,
        "text": "Competitive Advantage",
        "recommended": true,
        "question": "Could you please provide a few examples of achieving competitive advantage?",
        "examples": [
            "Developing unique selling propositions in marketing.",
            "Leveraging exclusive partnerships."
        ],
        "selected": false
    },
    {
        "id": 4,
        "text": "Innovation",
        "recommended": false,
        "question": "Could you please provide a few examples of fostering innovation?",
        "examples": [
            "Encouraging employee-led brainstorming sessions.",
            "Investing in R&D for new technologies."
        ],
        "selected": false
    },
    {
        "id": 5,
        "text": "Market Share",
        "recommended": false,
        "question": "Could you please provide a few examples of increasing market share?",
        "examples": [
            "Launching targeted marketing campaigns.",
            "Offering competitive pricing strategies."
        ],
        "selected": false
    },
    {
        "id": 6,
        "text": "Employee Satisfaction",
        "recommended": false,
        "question": "Could you please provide a few examples of enhancing employee satisfaction?",
        "examples": [
            "Implementing flexible work arrangements.",
            "Conducting regular employee feedback surveys."
        ],
        "selected": false
    },
    {
        "id": 7,
        "text": "Sustainability",
        "recommended": false,
        "question": "Could you please provide a few examples of promoting sustainability?",
        "examples": [
            "Reducing carbon footprint in operations.",
            "Adopting sustainable sourcing practices."
        ],
        "selected": false
    }
]

In [7]:
import json

with open("../../react_ideation/mori/backend/jsons/gpt_output/suggested_va.json","r") as f1:
    input_data = json.load(f1)
with open("../../react_ideation/mori/backend/jsons/output/suggestion_output.json","r") as f2:
    output_data = json.load(f2)

# Update the recommended key based on input data
for item in output_data:
    if item["text"] in input_data["strategy_linked_value_areas"]:
        item["recommended"] = True

# Print the updated output data
print(json.dumps(output_data, indent=4))



with open("../../react_ideation/mori/backend/jsons/input/suggestion_input copy.json","r") as f1:
    suggestions_json = json.load(f1)
 

# Extract value_area and answered_examples into a new JSON structure
extracted_data = [
    {
        "value_area": item["value_area"],
        "answered_examples": item["answered_examples"]
    }
    for item in suggestions_json
]

# Convert the extracted data to JSON format
extracted_json = json.dumps(extracted_data, indent=4)

# Print the extracted JSON
print(extracted_json)

[
    {
        "value_area": "Operational Efficiency",
        "answered_examples": "using AI to monitor IT systems and predict potential failures before they occur. Optimizing resource allocation based on usage patterns."
    },
    {
        "value_area": "Decision Intelligence And Reporting",
        "answered_examples": "using AI to monitor IT systems and predict potential failures before they occur. Optimizing resource allocation based on usage patterns."
    },
    {
        "value_area": "Technology Effectiveness",
        "answered_examples": "using AI to monitor IT systems and predict potential failures before they occur. Optimizing resource allocation based on usage patterns."
    },
    {
        "value_area": "Strategic Planning & Risk Management",
        "answered_examples": "using AI to monitor IT systems and predict potential failures before they occur. Optimizing resource allocation based on usage patterns."
    }
]

In [8]:
extracted_json

'[\n    {\n        "value_area": "Operational Efficiency",\n        "answered_examples": "using AI to monitor IT systems and predict potential failures before they occur. Optimizing resource allocation based on usage patterns."\n    },\n    {\n        "value_area": "Decision Intelligence And Reporting",\n        "answered_examples": "using AI to monitor IT systems and predict potential failures before they occur. Optimizing resource allocation based on usage patterns."\n    },\n    {\n        "value_area": "Technology Effectiveness",\n        "answered_examples": "using AI to monitor IT systems and predict potential failures before they occur. Optimizing resource allocation based on usage patterns."\n    },\n    {\n        "value_area": "Strategic Planning & Risk Management",\n        "answered_examples": "using AI to monitor IT systems and predict potential failures before they occur. Optimizing resource allocation based on usage patterns."\n    }\n]'

In [9]:
# save to gpt_inputs/